"use client";
import { useId, useState, type ReactNode, type ComponentProps } from "react";
import { Dialog, AlertDialog } from "radix-ui";
import { X, ArrowUpRight, Sprout, LoaderCircle, BadgeCheck } from "lucide-react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Field, FieldLabel } from "@/components/ui/field";
import type { Profile } from "@/lib/community/types";
import { useCommunity } from "./context";

export function Action({secondary=false,className="",...props}:ComponentProps<typeof Button>&{secondary?:boolean}){return <Button {...props} variant={secondary?"outline":"default"} className={`u-button ${secondary?"u-secondary":""} ${className}`} />;}
export function IconAction({label,children,type="button",...props}:ComponentProps<typeof Button>&{label:string}){return <Button {...props} type={type} variant="ghost" size="icon" className="u-icon-button" aria-label={label} title={label}>{children}</Button>;}
export function Avatar({person,size="normal"}:{person?:Profile;size?:"small"|"normal"|"large"}){const dimension=size==="large"?76:size==="small"?30:42;return <span className={`u-avatar u-avatar-${person?.color??0} u-avatar-${size}`} aria-hidden="true">{person?.avatar_url?<Image src={person.avatar_url} alt="" width={dimension} height={dimension} className="u-avatar-image" />:person?.name.split(/\s+/).map(s=>s[0]).slice(0,2).join("")||"U"}</span>;}
export function Person({id,detail,clickable=false}:{id:string;detail?:ReactNode;clickable?:boolean}){const {data,c,go,demo}=useCommunity();const person=data.profiles.find(p=>p.user_id===id);return <div className="u-person"><Avatar person={person}/><div>{clickable?<button type="button" className="u-person-name" onClick={()=>go("people")}>{person?.name??c("student")}</button>:<strong>{person?.name??c("student")}</strong>}{!demo&&<BadgeCheck className="u-verified" aria-label={c("verified")}/>}<div className="u-muted u-small">{detail??person?.campus}</div></div></div>;}
export function Empty({title,body,action}:{title:string;body?:string;action?:ReactNode}){return <div className="u-empty"><Sprout aria-hidden="true"/><h3>{title}</h3>{body&&<p>{body}</p>}{action}</div>;}
export function Loading({label}:{label:string}){return <div className="u-loading" role="status"><LoaderCircle className="u-spinner" aria-hidden="true"/><p>{label}</p></div>;}
export function Modal({open,onOpenChange,title,description,children,wide=false}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){const {c,feedback}=useCommunity();return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="u-overlay"/><Dialog.Content className={`u-dialog community-surface ${wide?"u-dialog-wide":""}`} {...(!description?{"aria-describedby":undefined}:{})}><div className="u-dialog-heading"><div><Dialog.Title>{title}</Dialog.Title>{description&&<Dialog.Description>{description}</Dialog.Description>}</div><Dialog.Close asChild><IconAction label={c("close")}><X/></IconAction></Dialog.Close></div>{children}{feedback?.error&&<p className="u-form-notice" role="alert">{feedback.text}</p>}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Confirm({title,description,onConfirm,children}:{title:string;description:string;onConfirm:()=>Promise<boolean>;children:ReactNode}){const {c,busy}=useCommunity();const [open,setOpen]=useState(false);return <AlertDialog.Root open={open} onOpenChange={setOpen}><AlertDialog.Trigger asChild>{children}</AlertDialog.Trigger><AlertDialog.Portal><AlertDialog.Overlay className="u-overlay"/><AlertDialog.Content className="u-dialog community-surface"><AlertDialog.Title>{title}</AlertDialog.Title><AlertDialog.Description className="u-muted u-confirm-description">{description}</AlertDialog.Description><div className="u-form-actions"><AlertDialog.Cancel asChild><Action secondary disabled={busy}>{c("cancel")}</Action></AlertDialog.Cancel><Action className="u-danger" disabled={busy} onClick={async()=>{if(await onConfirm())setOpen(false);}}>{busy?c("publishing"):c("delete")}</Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>;}
export function TextField({label,...props}:ComponentProps<typeof Input>&{label:string}){const id=useId();return <Field className="u-field"><FieldLabel htmlFor={id}>{label}</FieldLabel><Input {...props} id={id} className="u-input"/></Field>;}
export function TextArea({label,...props}:ComponentProps<"textarea">&{label:string}){const id=useId();return <Field className="u-field"><FieldLabel htmlFor={id}>{label}</FieldLabel><textarea {...props} id={id} className="u-input u-textarea"/></Field>;}
export function SelectField({label,children,...props}:ComponentProps<"select">&{label:string}){const id=useId();return <Field className="u-field"><FieldLabel htmlFor={id}>{label}</FieldLabel><select {...props} id={id} className="u-input">{children}</select></Field>;}
export function Chips({options,value,onChange,label}:{options:{value:string;label:string}[];value:string;onChange:(value:string)=>void;label:string}){return <div className="u-chips" role="group" aria-label={label}>{options.map(o=><button key={o.value} type="button" className={value===o.value?"u-chip active":"u-chip"} aria-pressed={value===o.value} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div>;}
export function ExternalLink({href,children}:{href:string;children:ReactNode}){return <a className="u-text-link" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight aria-hidden="true"/></a>;}
