"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, CircleHelp, Compass, Gift, Heart, Home, MapPin, MessageCircle, Package, PartyPopper, Search, Sparkles, Users } from "lucide-react";
import { Action } from "./controls";
import { useCommunity } from "./context";
import type { Locale } from "@/lib/i18n/routes";

type DiscoveryId = "blind-date" | "weekly" | "roll-call" | "meet-someone" | "confessions" | "study-buddy" | "roommates" | "market" | "clubs" | "challenges" | "campus-spots" | "my-week";
type DiscoveryItem = { id: DiscoveryId; icon: typeof Sparkles; tone: "lime" | "plum" | "peach" | "sky"; title: [string, string]; summary: [string, string]; detail: [string, string]; bullets: [[string, string], [string, string], [string, string]]; cta: [string, string] };
type DiscoveryGroup = { id: "connect" | "plan" | "community" | "campus"; icon: typeof Sparkles; tone: "lime" | "plum" | "peach" | "sky"; title: [string, string]; summary: [string, string]; items: DiscoveryId[] };

const ITEMS: DiscoveryItem[] = [
  { id: "blind-date", icon: Heart, tone: "plum", title: ["Cita a ciegas", "Cita a cegues"], summary: ["Una conversación sin fotos ni presión.", "Una conversa sense fotos ni pressió."], detail: ["El evento semanal para conocer a alguien con curiosidad y buen humor.", "L’esdeveniment setmanal per a conéixer algú amb curiositat i bon humor."], bullets: [["Jueves · 19:30–21:00", "Dijous · 19:30–21:00"], ["Conversación escrita · +18", "Conversa escrita · +18"], ["Parejas de 12 minutos", "Parelles de 12 minuts"]], cta: ["Quiero apuntarme", "Vull apuntar-me"] },
  { id: "weekly", icon: CalendarDays, tone: "lime", title: ["Esta semana", "Esta setmana"], summary: ["Lo que está pasando cerca de ti.", "El que està passant prop de tu."], detail: ["Un vistazo editorial a los planes con más conversación de la semana.", "Una ullada editorial als plans amb més conversa de la setmana."], bullets: [["5 planes seleccionados", "5 plans seleccionats"], ["Actualizado cada lunes", "Actualitzat cada dilluns"], ["Filtra por campus", "Filtra per campus"]], cta: ["Ver agenda", "Vore agenda"] },
  { id: "roll-call", icon: Users, tone: "sky", title: ["¿Quién se apunta?", "Qui s’apunta?"], summary: ["Encuentra compañía para el plan que ya tienes.", "Troba companyia per al pla que ja tens."], detail: ["Publica una idea rápida y deja que tu gente se sume en un toque.", "Publica una idea ràpida i deixa que la teua gent se sume en un toc."], bullets: [["Respuesta rápida", "Resposta ràpida"], ["Solo comunidad verificada", "Només comunitat verificada"], ["Cierra el grupo cuando quieras", "Tanca el grup quan vulgues"]], cta: ["Crear convocatoria", "Crear convocatòria"] },
  { id: "meet-someone", icon: MessageCircle, tone: "peach", title: ["Conoce a alguien", "Coneix algú"], summary: ["Una presentación con contexto, no un swipe.", "Una presentació amb context, no un swipe."], detail: ["Descubre perfiles que comparten una clase, una afición o un rincón de València contigo.", "Descobrix perfils que comparteixen una classe, una afició o un racó de València amb tu."], bullets: [["3 afinidades en común", "3 afinitats en comú"], ["Presentación sugerida", "Presentació suggerida"], ["Tú decides si saludar", "Tu decideixes si saludar"]], cta: ["Ver sugerencias", "Vore suggeriments"] },
  { id: "confessions", icon: CircleHelp, tone: "plum", title: ["Confesiones del campus", "Confessions del campus"], summary: ["Lo que todos piensan y nadie publica.", "El que tots pensen i ningú publica."], detail: ["Un espacio anónimo para compartir la parte rara, divertida o tierna de la vida universitaria.", "Un espai anònim per a compartir la part rara, divertida o tendra de la vida universitària."], bullets: [["Anónimo por defecto", "Anònim per defecte"], ["Moderación comunitaria", "Moderació comunitària"], ["Reacciones sin ruido", "Reaccions sense soroll"]], cta: ["Leer confesiones", "Llegir confessions"] },
  { id: "study-buddy", icon: Search, tone: "sky", title: ["Compañero de estudio", "Company d’estudi"], summary: ["Encuentra tu ritmo para preparar el examen.", "Troba el teu ritme per a preparar l’examen."], detail: ["Conecta por asignatura, horario y forma de estudiar antes de abrir los apuntes.", "Connecta per assignatura, horari i manera d’estudiar abans d’obrir els apunts."], bullets: [["Por asignatura", "Per assignatura"], ["Horarios compatibles", "Horaris compatibles"], ["Sesiones en biblioteca", "Sessions a la biblioteca"]], cta: ["Buscar compañero", "Buscar company"] },
  { id: "roommates", icon: Home, tone: "peach", title: ["Pisos y compañeros", "Pisos i companys"], summary: ["Vivir cerca también es formar comunidad.", "Viure prop també és fer comunitat."], detail: ["Anuncios cuidados para encontrar habitación, piso o alguien con quien buscarlo.", "Anuncis cuidats per a trobar habitació, pis o algú amb qui buscar-lo."], bullets: [["Zonas de València", "Zones de València"], ["Preferencias claras", "Preferències clares"], ["Contacto universitario", "Contacte universitari"]], cta: ["Explorar anuncios", "Explorar anuncis"] },
  { id: "market", icon: Package, tone: "lime", title: ["Mercadillo universitario", "Mercat universitari"], summary: ["Lo que ya no usas puede servirle a alguien.", "El que ja no uses pot servir a algú."], detail: ["Intercambia libros, calculadoras, muebles y pequeños hallazgos entre campus.", "Intercanvia llibres, calculadores, mobles i xicotetes troballes entre campus."], bullets: [["Compra y vende cerca", "Compra i ven prop"], ["Categorías útiles", "Categories útils"], ["Entrega en punto de campus", "Entrega en punt de campus"]], cta: ["Ver mercadillo", "Vore mercat"] },
  { id: "clubs", icon: PartyPopper, tone: "plum", title: ["Clubes y quedadas", "Clubs i quedades"], summary: ["Aficiones que salen de la pantalla.", "Aficions que ixen de la pantalla."], detail: ["Encuentra grupos abiertos, prueba algo nuevo y pon fecha a la próxima quedada.", "Troba grups oberts, prova alguna cosa nova i posa data a la pròxima quedada."], bullets: [["Arte, deporte y cultura", "Art, esport i cultura"], ["Quedadas abiertas", "Quedades obertes"], ["Crea tu propio club", "Crea el teu propi club"]], cta: ["Ver clubes", "Vore clubs"] },
  { id: "challenges", icon: Gift, tone: "lime", title: ["Retos de la semana", "Reptes de la setmana"], summary: ["Pequeños planes para salir del piloto automático.", "Xicotets plans per a eixir del pilot automàtic."], detail: ["Un reto compartido cada lunes: conocer un sitio, saludar a alguien o hacer algo distinto.", "Un repte compartit cada dilluns: conéixer un lloc, saludar algú o fer alguna cosa diferent."], bullets: [["Reto nuevo cada lunes", "Repte nou cada dilluns"], ["Se completa en comunidad", "Es completa en comunitat"], ["Premios en ClasiCoins", "Premis en ClasiCoins"]], cta: ["Ver reto actual", "Vore repte actual"] },
  { id: "campus-spots", icon: MapPin, tone: "sky", title: ["Rincones del campus", "Racons del campus"], summary: ["Los sitios que merecen una pausa.", "Els llocs que mereixen una pausa."], detail: ["Recomendaciones de estudiantes para comer, estudiar, respirar o quedarse hablando.", "Recomanacions d’estudiants per a menjar, estudiar, respirar o quedar-se parlant."], bullets: [["Mapa de recomendaciones", "Mapa de recomanacions"], ["Fotos de la comunidad", "Fotos de la comunitat"], ["Guías por campus", "Guies per campus"]], cta: ["Explorar rincones", "Explorar racons"] },
  { id: "my-week", icon: Compass, tone: "peach", title: ["Mi semana", "La meua setmana"], summary: ["Tu agenda social, sin llenar cada hueco.", "La teua agenda social, sense omplir cada buit."], detail: ["Reúne tus planes, retos y sesiones de estudio para ver qué te apetece de verdad.", "Reunix els teus plans, reptes i sessions d’estudi per a vore què et ve de gust de veritat."], bullets: [["Vista de lunes a domingo", "Vista de dilluns a diumenge"], ["Añade planes con un toque", "Afig plans amb un toc"], ["Espacio para improvisar", "Espai per a improvisar"]], cta: ["Montar mi semana", "Muntar la meua setmana"] },
];

const iconLabels: Record<DiscoveryId, [string, string]> = { "blind-date": ["Evento romántico", "Esdeveniment romàntic"], weekly: ["Agenda", "Agenda"], "roll-call": ["Convocatoria", "Convocatòria"], "meet-someone": ["Conexiones", "Connexions"], confessions: ["Comunidad", "Comunitat"], "study-buddy": ["Estudio", "Estudi"], roommates: ["Vivienda", "Habitatge"], market: ["Intercambio", "Intercanvi"], clubs: ["Aficiones", "Aficions"], challenges: ["Participación", "Participació"], "campus-spots": ["Campus", "Campus"], "my-week": ["Organización", "Organització"] };
const GROUPS: DiscoveryGroup[] = [
  { id: "connect", icon: Users, tone: "plum", title: ["Conectar", "Connectar"], summary: ["Personas, conversaciones y esa chispa que no se fuerza.", "Persones, converses i eixa espurna que no es força."], items: ["blind-date", "meet-someone", "roll-call"] },
  { id: "plan", icon: CalendarDays, tone: "lime", title: ["Planear", "Planificar"], summary: ["Una semana con algo que esperar y espacio para improvisar.", "Una setmana amb alguna cosa a esperar i espai per a improvisar."], items: ["weekly", "my-week", "challenges"] },
  { id: "community", icon: PartyPopper, tone: "peach", title: ["Comunidad", "Comunitat"], summary: ["Aficiones, intercambio y las historias que pasan entre clases.", "Aficions, intercanvi i les històries que passen entre classes."], items: ["confessions", "clubs", "market"] },
  { id: "campus", icon: MapPin, tone: "sky", title: ["Campus", "Campus"], summary: ["Estudiar, vivir y encontrar tu rincón en València.", "Estudiar, viure i trobar el teu racó a València."], items: ["study-buddy", "campus-spots", "roommates"] },
];
function text(value: [string, string], locale: Locale) { return value[locale === "va" ? 1 : 0]; }

export function Discover() {
  const { locale } = useCommunity();
  const [selectedId, setSelectedId] = useState<DiscoveryId | null>(null);
  const [selectedGroupId, setSelectedGroupId] = useState<DiscoveryGroup["id"] | null>(null);
  const [saved, setSaved] = useState<DiscoveryId[]>([]);
  const selected = useMemo(() => ITEMS.find(item => item.id === selectedId) ?? null, [selectedId]);
  const selectedGroup = useMemo(() => GROUPS.find(group => group.id === selectedGroupId) ?? null, [selectedGroupId]);
  const toggleSaved = (id: DiscoveryId) => setSaved(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);

  if (selected) {
    const Icon = selected.icon;
    const isSaved = saved.includes(selected.id);
    const next = ITEMS[(ITEMS.findIndex(item => item.id === selected.id) + 1) % ITEMS.length];
    return <section className="u-discover-detail" aria-labelledby="discover-detail-title"><button type="button" className="u-discover-back" onClick={() => setSelectedId(null)}><ArrowLeft aria-hidden="true" />{locale === "va" ? "Tornar a descobrir" : "Volver a descubrir"}</button><div className={`u-discover-detail-card ${selected.tone}`}><div className="u-discover-detail-icon"><Icon aria-hidden="true" /></div><p className="u-eyebrow">{text(iconLabels[selected.id], locale)}</p><h2 id="discover-detail-title">{text(selected.title, locale)}</h2><p className="u-discover-detail-copy">{text(selected.detail, locale)}</p><div className="u-discover-bullets">{selected.bullets.map((bullet, index) => <div key={index}><Check aria-hidden="true" /><span>{text(bullet, locale)}</span></div>)}</div><div className="u-discover-detail-actions"><Action onClick={() => toggleSaved(selected.id)}>{isSaved ? <><Check aria-hidden="true" />{locale === "va" ? "Apuntat" : "Apuntado"}</> : <>{text(selected.cta, locale)}<ArrowRight aria-hidden="true" /></>}</Action><Action secondary onClick={() => setSelectedId(null)}>{locale === "va" ? "Veure totes" : "Ver todas"}</Action></div>{isSaved && <p className="u-discover-confirm" role="status">{locale === "va" ? "Ho hem guardat per a tu en esta visita." : "Lo hemos guardado para ti en esta visita."}</p>}</div><div className="u-discover-next"><span>{locale === "va" ? "Continua explorant" : "Sigue explorando"}</span><button type="button" onClick={() => setSelectedId(next.id)}>{locale === "va" ? "Següent" : "Siguiente"}<ArrowRight aria-hidden="true" /></button></div></section>;
  }

  if (selectedGroup) {
    const GroupIcon = selectedGroup.icon;
    return <section className="u-discover-detail" aria-labelledby="discover-group-title"><button type="button" className="u-discover-back" onClick={() => setSelectedGroupId(null)}><ArrowLeft aria-hidden="true" />{locale === "va" ? "Tornar a descobrir" : "Volver a descubrir"}</button><div className={`u-discover-detail-card ${selectedGroup.tone}`}><div className="u-discover-detail-icon"><GroupIcon aria-hidden="true" /></div><p className="u-eyebrow">{locale === "va" ? "Secció d’Entreclase" : "Sección de Entreclase"}</p><h2 id="discover-group-title">{text(selectedGroup.title, locale)}</h2><p className="u-discover-detail-copy">{text(selectedGroup.summary, locale)}</p><div className="u-discover-subpages">{selectedGroup.items.map(id => { const item = ITEMS.find(candidate => candidate.id === id)!; const Icon = item.icon; return <button type="button" className="u-discover-subpage" key={item.id} onClick={() => { setSelectedGroupId(null); setSelectedId(item.id); }}><span className={`u-discover-subpage-icon ${item.tone}`}><Icon aria-hidden="true" /></span><span><strong>{text(item.title, locale)}</strong><small>{text(item.summary, locale)}</small></span><ArrowRight aria-hidden="true" /></button>; })}</div></div></section>;
  }

  return <section className="u-discover" aria-labelledby="discover-grid-title"><div className="u-discover-intro"><div><p className="u-eyebrow">{locale === "va" ? "Noves maneres de coincidir" : "Nuevas formas de coincidir"}</p><h2 id="discover-grid-title">{locale === "va" ? "Tria què et ve de gust esta setmana." : "Elige qué te apetece esta semana."}</h2><p>{locale === "va" ? "Quatre espais per a trobar gent, plans i eixos moments que no ixen en cap horari." : "Cuatro espacios para encontrar gente, planes y esos momentos que no salen en ningún horario."}</p></div><div className="u-discover-intro-mark" aria-hidden="true"><Sparkles /></div></div><div className="u-discover-grid">{GROUPS.map(group => { const Icon = group.icon; const savedCount = group.items.filter(id => saved.includes(id)).length; return <article className={`u-discover-card ${group.tone}`} key={group.id}><div className="u-discover-card-top"><div className="u-discover-card-icon"><Icon aria-hidden="true" /></div>{savedCount > 0 && <span className="u-discover-saved"><Check aria-hidden="true" />{savedCount} {locale === "va" ? "guardat" : "guardado"}</span>}</div><p className="u-eyebrow">{group.items.length} {locale === "va" ? "espais" : "espacios"}</p><h3>{text(group.title, locale)}</h3><p>{text(group.summary, locale)}</p><button type="button" className="u-discover-open" onClick={() => setSelectedGroupId(group.id)}>{locale === "va" ? "Obrir secció" : "Abrir sección"}<ArrowRight aria-hidden="true" /></button></article>; })}</div></section>;
}
