"use client";
import { useRef, useState } from "react";
import Image from "next/image";
import { Input } from "@/components/ui/input";
import { ArrowUpRight, Heart, MessageCircle, Plus, Send, Trash2, ArrowLeft, HelpCircle, ThumbsDown } from "lucide-react";
import { useCommunity, matches } from "./context";
import { Action, Avatar, Chips, Confirm, Empty, IconAction, Person, SelectField } from "./controls";
import { relativeDate } from "@/lib/community/copy";
import { COIN_RULES } from "@/lib/community/unicoins";
import { unicoinCopy } from "@/lib/i18n/unicoins";
import { CoinAmount, SpendNotice, RewardHint } from "./unicoins";
import type { Post } from "@/lib/community/types";
export function Feed({compact=false,home=false}:{compact?:boolean;home?:boolean}={}){const {c,locale,data,me,query,groupId,go}=useCommunity();const [filter,setFilter]=useState("all");const group=data.groups.find(g=>g.id===groupId),mine=data.groupMembers.filter(m=>m.user_id===me.user_id).map(m=>m.group_id);const posts=data.posts.filter(p=>(group?p.group_id===group.id:filter==="all"||!!p.group_id&&mine.includes(p.group_id))&&matches(query,p.body,data.profiles.find(a=>a.user_id===p.author_id)?.name));return <div className="u-feed">{!compact&&!group&&!query&&<section className="u-welcome"><div><span className="u-eyebrow">València · {locale==="va"?"Ens veiem fora":"Nos vemos fuera"}</span><h2>{c("welcome")}<br/><em>{c("welcomeLine")}</em></h2><p>{c("welcomeBody")}</p><Action onClick={()=>go("plans")}>{c("findPlan")}<ArrowUpRight/></Action></div><Image src="/images/campus-walk.webp" alt={c("welcomeAlt")} width={620} height={760} priority/><span className="u-welcome-sticker" aria-hidden="true">{locale==="va"?"Ei, anem?":"Ey, ¿vamos?"}</span></section>}{group&&<div className="u-group-heading"><IconAction label={c("groups")} onClick={()=>go("groups")}><ArrowLeft/></IconAction><div><p className="u-eyebrow">{c("groups")} · {group.campus}</p><h2>{group.name}</h2><p>{group.description}</p></div></div>}<Composer key={group?.id??"all"} groupId={group?.id??null}/><div className="u-section-heading"><h2>{group?group.name:home?c("forumSection"):c("wall")}</h2>{!group&&<Chips label={home?c("forumSection"):c("wall")} options={[{value:"all",label:c("all")},{value:"groups",label:c("following")}]} value={filter} onChange={setFilter}/>}</div>{posts.length?posts.map(p=><PostCard key={p.id} post={p}/>):<Empty title={c("noPosts")} body={c("noPostsBody")}/>}</div>;}
export function Composer({groupId}:{groupId:string|null}){const {me,data,c,repo,run,busy}=useCommunity();const requestId=useRef<string|null>(null);const [body,setBody]=useState(""),[kind,setKind]=useState<Post["kind"]>("post"),[audience,setAudience]=useState(groupId??"");const groups=data.groups.filter(g=>data.groupMembers.some(m=>m.group_id===g.id&&m.user_id===me.user_id));if(groupId&&!groups.some(g=>g.id===groupId))return <p className="u-info">{c("groupOnly")}</p>;const selected=groupId??audience;return <form className="u-card u-composer" onSubmit={async e=>{e.preventDefault();const action=requestId.current??=crypto.randomUUID();if(await run(()=>repo.publish(body,kind,selected||null,action),c("posted"))){setBody(current=>current===body?"":current);requestId.current=null;}}}><div className="u-composer-body"><Avatar person={me}/><label className="u-composer-label"><span className="sr-only">{c("composer")}</span><textarea value={body} onChange={e=>{setBody(e.target.value);requestId.current=null;}} placeholder={c("composer")} maxLength={2000} required rows={2}/></label></div><div className="u-composer-footer"><div><Chips label={c("post")} options={[{value:"post",label:c("post")},{value:"question",label:c("question")}]} value={kind} onChange={v=>{setKind(v as Post["kind"]);requestId.current=null;}}/>{!groupId&&<SelectField label={c("audience")} value={audience} onChange={e=>{setAudience(e.target.value);requestId.current=null;}}><option value="">{c("audience")}</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</SelectField>}</div><Action type="submit" disabled={busy||!body.trim()||data.wallet.balance<COIN_RULES.createThread}><Plus/>{c("publish")}<CoinAmount amount={-COIN_RULES.createThread}/></Action></div><SpendNotice amount={COIN_RULES.createThread}/></form>;}
export function PostCard({post}:{post:Post}){
 const {c,data,me,locale,repo,run,busy,go}=useCommunity();
 const [open,setOpen]=useState(false),[body,setBody]=useState(""),[disliked,setDisliked]=useState(false);
 const likes=data.likes.filter(l=>l.post_id===post.id),liked=likes.some(l=>l.user_id===me.user_id),comments=data.comments.filter(x=>x.post_id===post.id),group=data.groups.find(g=>g.id===post.group_id);
 const toggleDislike=async()=>{if(!disliked&&liked)await run(()=>repo.like(post.id,false),"");setDisliked(value=>!value);};
 const toggleLike=async()=>{if(disliked)setDisliked(false);await run(()=>repo.like(post.id,!liked),"");};
 return <article className="u-card u-post"><header><Person id={post.author_id} detail={<>{data.profiles.find(p=>p.user_id===post.author_id)?.campus} <span aria-hidden="true">·</span> <time dateTime={post.created_at}>{relativeDate(post.created_at,locale)}</time></>}/>{post.author_id===me.user_id&&<Confirm title={c("deletePost")} description={`${c("deleteHelp")} ${unicoinCopy(locale)("noRefund")}`} onConfirm={()=>run(()=>repo.removePost(post.id),c("removed"))}><IconAction label={c("delete")}><Trash2/></IconAction></Confirm>}</header>{group&&<button className="u-group-tag" onClick={()=>go("home",{groupId:group.id})}>{group.name}<ArrowUpRight aria-hidden="true"/></button>}{post.kind==="question"&&<span className="u-question"><HelpCircle aria-hidden="true"/>{c("question")}</span>}<p className="u-post-body">{post.body}</p>{post.image_url&&<Image className="u-post-image" src={post.image_url} width={920} height={480} alt={c("exampleImage")}/>}<div className="u-post-actions"><button type="button" disabled={busy} className={liked?"liked":""} aria-pressed={liked} onClick={()=>void toggleLike()}><Heart fill={liked?"currentColor":"none"} aria-hidden="true"/>{liked?c("liked"):c("like")}<span>{likes.length}</span></button><button type="button" disabled={busy} className={disliked?"disliked":""} aria-pressed={disliked} onClick={()=>void toggleDislike()}><ThumbsDown aria-hidden="true"/>{c("dislike")}</button><button type="button" aria-expanded={open} aria-controls={`comments-${post.id}`} onClick={()=>setOpen(!open)}><MessageCircle aria-hidden="true"/>{c("comment")}<span>{comments.length}</span></button></div>{open&&<section className="u-comments" id={`comments-${post.id}`} aria-label={c("comments")}>{comments.map(comment=><div className="u-comment" key={comment.id}><Avatar size="small" person={data.profiles.find(p=>p.user_id===comment.author_id)}/><div><strong>{data.profiles.find(p=>p.user_id===comment.author_id)?.name??c("student")}</strong><p>{comment.body}</p></div></div>)}<RewardHint kind="thread" resourceId={post.id} own={post.author_id===me.user_id} participated={comments.some(comment=>comment.author_id===me.user_id)}/><form onSubmit={async e=>{e.preventDefault();if(await run(()=>repo.comment(post.id,body),""))setBody(current=>current===body?"":current);}}><label className="sr-only" htmlFor={`comment-${post.id}`}>{c("comment")}</label><Input className="u-input" id={`comment-${post.id}`} value={body} onChange={e=>setBody(e.target.value)} placeholder={c("commentPlaceholder")} maxLength={600} required/><IconAction label={c("send")} disabled={busy||!body.trim()} type="submit"><Send/></IconAction></form></section>}</article>;
}
