"use client";
import { useRef, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpRight, Check, ImagePlus, Save, Send, Trash2 } from "lucide-react";
import { safeWebUrl, type MagazinePhoto, type Submission, type SubmissionStatus } from "@/lib/community/studio/types";
import { canEditProposal, magazineSections, proposalStatus, statusLabel, validateProposal } from "@/lib/community/studio/proposals";
import { useCommunity } from "./context";
import { useStudio } from "./studio-context";
import { Action, SelectField, TextArea, TextField } from "./controls";
import { MagazinePhotoView, MagazineStoryBody, prepareMagazinePhoto, uploadMagazinePhotos } from "./magazine-media";

export function ProposalForm({ initial, onDone, onCancel }: { initial?: Submission; onDone: () => void; onCancel: () => void }) {
 const { data: community, me, locale, demo } = useCommunity(), { data, act, busy } = useStudio();
 const t = (es: string, va: string) => locale === "va" ? va : es;
 const [kind,setKind]=useState<Submission["kind"]>(initial?.kind??"story");
 const [source,setSource]=useState(initial?.source_id??""),[title,setTitle]=useState(initial?.title??""),[body,setBody]=useState(initial?.body??""),[url,setUrl]=useState(initial?.source_url??"");
 const [summary,setSummary]=useState(initial?.summary??""),[section,setSection]=useState(initial?.section??"Vida de campus"),[layout,setLayout]=useState<Submission["layout"]>(initial?.layout??"classic");
 const [images,setImages]=useState<MagazinePhoto[]>(initial?.images??[]),[note,setNote]=useState(initial?.author_note??"");
 const [consent,setConsent]=useState(false),[rights,setRights]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const locked=useRef(false), fileInput=useRef<HTMLInputElement>(null);
 const disabled=busy||saving;
 const enabled=demo||data.magazine_version===2;
 const [confirmClose,setConfirmClose]=useState(false);
 const sources=kind==="project"?data.projects.filter(x=>x.owner===me.user_id).map(x=>({id:x.id,title:x.title})):kind==="plan"?community.plans.filter(x=>x.creator_id===me.user_id).map(x=>({id:x.id,title:x.title})):kind==="post"?community.posts.filter(x=>x.author_id===me.user_id&&!x.group_id).map(x=>({id:x.id,title:x.body.slice(0,100)})):[];
 async function addFiles(files: File[]) {
  if(locked.current)return;
  setError("");
  if(files.length+images.length>4){setError(t("Puedes añadir hasta cuatro imágenes.","Pots afegir fins a quatre imatges."));return;}
  locked.current=true;setSaving(true);
  try {
   const additions:MagazinePhoto[]=[];
   for(const file of files) additions.push({path:await prepareMagazinePhoto(file),alt:"",caption:"",credit:me.name});
   if(new Set([...images,...additions].map(photo=>photo.path)).size!==images.length+additions.length)throw Error(t("Esta imagen ya está añadida.","Esta imatge ja està afegida."));
   setImages(current=>[...current,...additions]);setConsent(false);setRights(false);
  } catch(e){setError(e instanceof Error?e.message:t("No se pudo leer la imagen.","No s’ha pogut llegir la imatge."));}
  finally{locked.current=false;setSaving(false);}
 }
 function updatePhoto(index:number,change:Partial<MagazinePhoto>){setImages(current=>current.map((photo,i)=>i===index?{...photo,...change}:photo));setConsent(false);}
 function movePhoto(index:number,offset:number){setImages(current=>{const next=[...current];[next[index],next[index+offset]]=[next[index+offset],next[index]];return next;});setConsent(false);}
 async function save(send:boolean){
  if(locked.current||busy)return;
  locked.current=true;setSaving(true);setError("");
  const input={id:initial?.id,revision:initial?.revision,kind,source_id:source,source_url:url,title,body,summary,section,layout,images,author_note:note,consent,image_rights:rights,send};
  try {
   validateProposal(input,send);
   if(!demo&&data.magazine_version!==2)throw Error(t("Las propuestas ampliadas todavía no están activadas en este campus.","Les propostes ampliades encara no estan activades en este campus."));
   const uploaded=await uploadMagazinePhotos(images,me.user_id,demo);
   if(await act("save_submission",{...input,images:uploaded.images}))onDone();
   else {await uploaded.cleanup();setError(t("No se ha guardado. Conservamos lo que has escrito; revisa el aviso y vuelve a intentarlo.","No s’ha guardat. Conservem el que has escrit; revisa l’avís i torna a intentar-ho."));}
  } catch(e){setError(e instanceof Error?e.message:t("No se ha podido guardar. Tu borrador sigue aquí.","No s’ha pogut guardar. L’esborrany continua ací."));}
  finally{locked.current=false;setSaving(false);}
 }
 return <form className="mz-composer" onSubmit={e=>{e.preventDefault();void save(true);}} onChangeCapture={e=>{const input=e.target;if(!(input instanceof HTMLInputElement)|| (input.name!=="consent"&&input.name!=="image-rights"))setConsent(false);}}>
  <header className="mz-composer-heading"><div><p className="mz-folio">{t("TU MESA DE REDACCIÓN","LA TEUA TAULA DE REDACCIÓ")}</p><h2>{initial?t("Dale otra vuelta.","Dona-li una altra volta."):t("Aquí empieza tu historia.","Ací comença la teua història.")}</h2><p>{t("Escribe, añade imágenes y decide cómo se lee. Puedes dejarlo a medias y volver a tu borrador.","Escriu, afig imatges i decidix com es llig. Pots deixar-ho a mitges i tornar a l’esborrany.")}</p></div><button type="button" className="mz-link" disabled={disabled} onClick={()=>setConfirmClose(true)}>{t("Cerrar editor","Tancar editor")}</button></header>
  {confirmClose&&<div className="mz-withdraw-confirm"><p>{t("Si cierras ahora, se perderán los cambios sin guardar. Puedes guardar el borrador al final del editor.","Si tanques ara, es perdran els canvis sense guardar. Pots guardar l’esborrany al final de l’editor.")}</p><button type="button" className="mz-link" onClick={()=>setConfirmClose(false)}>{t("Seguir escribiendo","Continuar escrivint")}</button><button type="button" className="mz-link" onClick={onCancel}>{t("Cerrar sin guardar","Tancar sense guardar")}</button></div>}
  {!enabled&&<p role="status" className="mz-form-error">{t("El editor está en vista previa. El guardado y los envíos estarán disponibles cuando se active la nueva revista en este campus.","L’editor està en vista prèvia. Es podrà guardar i enviar quan s’active la nova revista en este campus.")}</p>}
  <div className="mz-composer-grid"><fieldset disabled={disabled} className="mz-composer-fields">
   <div className="mz-form-part"><h3><span>01</span>{t("Lo que quieres contar","El que vols contar")}</h3>
    <div className="mz-field-pair"><SelectField label={t("Tipo de historia","Tipus d’història")} value={kind} onChange={e=>{setKind(e.target.value as Submission["kind"]);setSource("");}}><option value="story">{t("Una historia propia","Una història pròpia")}</option><option value="project">{t("Mi proyecto","El meu projecte")}</option><option value="plan">{t("Mi plan","El meu pla")}</option><option value="post">{t("Mi hilo público","El meu fil públic")}</option><option value="initiative">{t("Una iniciativa con fuente","Una iniciativa amb font")}</option></SelectField>
    <SelectField label={t("Sección propuesta","Secció proposada")} value={section} onChange={e=>setSection(e.target.value)}>{magazineSections.map((s,i)=><option value={s} key={s}>{locale==="va"?["Vida de campus","Projectes","Plans","Cultura","Opinió"][i]:s}</option>)}</SelectField></div>
    {["project","plan","post"].includes(kind)&&<SelectField label={t("Tu contenido original","El teu contingut original")} value={source} onChange={e=>setSource(e.target.value)}><option value="">{t("Selecciona tu contenido","Selecciona el teu contingut")}</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</SelectField>}
    {kind==="initiative"&&<TextField label={t("Enlace a la fuente","Enllaç a la font")} value={url} onChange={e=>setUrl(e.target.value)} type="url" maxLength={500}/>}
    <TextField label={t("Titular · hasta 120 caracteres","Titular · fins a 120 caràcters")} value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder={t("Empieza por lo que merece ser contado.","Comença pel que mereix ser contat.")}/>
    <TextArea label={t("Entradilla · opcional, hasta 240 caracteres","Entradeta · opcional, fins a 240 caràcters")} value={summary} onChange={e=>setSummary(e.target.value)} maxLength={240} rows={2}/>
    <TextArea label={t("Tu historia","La teua història")} value={body} onChange={e=>setBody(e.target.value)} maxLength={8000} rows={12} placeholder={t("¿Qué pasó? ¿Qué estás intentando? ¿Qué te falta? Cuéntalo con tus palabras.","Què va passar? Què estàs intentant? Què et falta? Conta-ho amb les teues paraules.")}/><p className="mz-field-help">{body.length.toLocaleString()} / 8.000 · {t("Mínimo 40 al enviar. Los saltos de párrafo se conservan.","Mínim 40 en enviar. Els salts de paràgraf es conserven.")}</p>
   </div>
   <div className="mz-form-part"><h3><span>02</span>{t("Las imágenes también cuentan","Les imatges també conten")}</h3><p className="mz-field-help">{t("Hasta 4 imágenes · JPG, PNG o WebP · 6 MB por archivo. La primera será la principal. Las optimizamos para la lectura.","Fins a 4 imatges · JPG, PNG o WebP · 6 MB per fitxer. La primera serà la principal. Les optimitzem per a la lectura.")}</p>
    <input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" aria-label={t("Añadir imágenes a la propuesta","Afegir imatges a la proposta")} onChange={e=>{void addFiles(Array.from(e.target.files??[]));e.target.value="";}}/>
    <button type="button" className="mz-image-upload" disabled={images.length>=4} onClick={()=>fileInput.current?.click()}><ImagePlus/>{t("Añadir imágenes","Afegir imatges")}<small>{images.length}/4</small></button>
    {images.map((photo,index)=><div className="mz-photo-editor" key={index}><MagazinePhotoView photo={photo}/><div><div className="mz-photo-tools"><strong>{index===0?t("Imagen principal","Imatge principal"):`${t("Imagen","Imatge")} ${index+1}`}</strong><button type="button" aria-label={`${t("Subir imagen","Pujar imatge")} ${index+1}`} disabled={index===0} onClick={()=>movePhoto(index,-1)}><ArrowUp/></button><button type="button" aria-label={`${t("Bajar imagen","Baixar imatge")} ${index+1}`} disabled={index===images.length-1} onClick={()=>movePhoto(index,1)}><ArrowDown/></button><button type="button" aria-label={`${t("Quitar imagen","Llevar imatge")} ${index+1}`} onClick={()=>{setImages(current=>current.filter((_,i)=>i!==index));setConsent(false);}}><Trash2/></button></div>
    <TextField label={t("Descripción accesible","Descripció accessible")} value={photo.alt} maxLength={200} onChange={e=>updatePhoto(index,{alt:e.target.value})}/><TextField label={t("Pie de foto · opcional","Peu de foto · opcional")} value={photo.caption} maxLength={300} onChange={e=>updatePhoto(index,{caption:e.target.value})}/><TextField label={t("Crédito de la imagen","Crèdit de la imatge")} value={photo.credit} maxLength={120} onChange={e=>updatePhoto(index,{credit:e.target.value})}/></div></div>)}
   </div>
   <div className="mz-form-part"><h3><span>03</span>{t("Cómo quieres presentarla","Com vols presentar-la")}</h3><SelectField label={t("Presentación","Presentació")} value={layout} onChange={e=>setLayout(e.target.value as Submission["layout"])}><option value="classic">{t("Texto primero · imágenes al final","Text primer · imatges al final")}</option><option value="photo">{t("Foto de apertura · a todo el ancho","Foto d’obertura · a tota l’amplària")}</option><option value="split">{t("Foto junto al texto","Foto al costat del text")}</option></SelectField><p className="mz-field-help">{t("Tu presentación se conserva al publicar. En móvil, la imagen lateral pasa encima del texto.","La presentació es conserva en publicar. En mòbil, la imatge lateral passa damunt del text.")}</p>
    <TextArea label={t("Nota para el equipo editorial · privada","Nota per a l’equip editorial · privada")} value={note} maxLength={1000} rows={3} onChange={e=>setNote(e.target.value)} placeholder={t("Una fecha importante, algo que convenga saber…","Una data important, alguna cosa que convinga saber…")}/>
   </div>
  </fieldset><aside className="mz-composer-preview"><p className="mz-folio">{t("VISTA PREVIA · TU VERSIÓN","VISTA PRÈVIA · LA TEUA VERSIÓ")}</p><article className="mz-story mz-preview-story"><div className="mz-story-copy"><p className="mz-folio">{section}</p><h3>{title||t("Aquí va ese titular.","Ací va eixe titular.")}</h3><MagazineStoryBody body={body||t("Empieza a escribir. Tu historia aparecerá aquí, con las imágenes y la presentación que elijas.","Comença a escriure. La teua història apareixerà ací, amb les imatges i la presentació que tries.")} summary={summary} images={images} layout={layout}/><footer><span>{t("Por","Per")} <strong>{me.name}</strong></span></footer></div></article><p className="mz-field-help">{t("El texto, el orden de las imágenes y sus créditos son los que autorizas. El tamaño se adapta a cada pantalla.","El text, l’ordre de les imatges i els crèdits són els que autoritzes. La mida s’adapta a cada pantalla.")}</p></aside></div>
  <footer className="mz-composer-submit">{images.length>0&&<label className="st-checkbox"><input name="image-rights" type="checkbox" checked={rights} disabled={disabled} onChange={e=>{setRights(e.target.checked);setConsent(false);}}/>{t("Tengo derecho a publicar estas imágenes y permiso de las personas que aparecen cuando es necesario.","Tinc dret a publicar estes imatges i permís de les persones que hi apareixen quan és necessari.")}</label>}
  <label className="st-checkbox"><input name="consent" type="checkbox" checked={consent} disabled={disabled} onChange={e=>setConsent(e.target.checked)}/>{t("Autorizo esta versión del texto, las imágenes y los créditos para la revista y su adelanto en Inicio, dentro de la comunidad verificada. Puedo retirar el permiso también del archivo.","Autoritze esta versió del text, les imatges i els crèdits per a la revista i el seu avanç en Inici, dins de la comunitat verificada. Puc retirar el permís també de l’arxiu.")}</label>
  <p className="mz-field-help">{t("Guardar un borrador no lo envía. Autorizar y enviar no garantiza que se acepte. Cualquier cambio posterior se vuelve a revisar.","Guardar un esborrany no l’envia. Autoritzar i enviar no garantix que s’accepte. Qualsevol canvi posterior es torna a revisar.")}</p>
  {error&&<p role="alert" className="mz-form-error">{error}</p>}<div className="mz-submit-actions"><Action type="button" secondary disabled={disabled||!enabled} onClick={()=>void save(false)}><Save/>{t("Guardar borrador","Guardar esborrany")}</Action><Action type="submit" disabled={disabled||!enabled}><Send/>{saving?t("Guardando…","Guardant…"):t("Autorizar y enviar a revisión","Autoritzar i enviar a revisió")}</Action></div>
  </footer>
 </form>;
}

export function MyMagazineProposals({ onEdit }: { onEdit: (s: Submission) => void }) {
 const { me,locale }=useCommunity(),{data,act,busy}=useStudio(); const t=(es:string,va:string)=>locale==="va"?va:es;
 const [filter,setFilter]=useState(""),[confirm,setConfirm]=useState("");
 const own=data.submissions.filter(s=>s.author===me.user_id), shown=own.filter(s=>!filter||proposalStatus(s)===filter);
 return <section id="revista-mis-propuestas" className="mz-proposal-tracker"><header><div><p className="mz-folio">{t("DEL BORRADOR A LA REVISTA","DE L’ESBORRANY A LA REVISTA")}</p><h2>{t("Mis propuestas","Les meues propostes")}<span>.</span></h2><p>{t("Aquí ves qué has enviado, qué te han respondido y qué falta para publicarlo.","Ací veus què has enviat, què t’han respost i què falta per a publicar-ho.")}</p></div><SelectField label={t("Filtrar por estado","Filtrar per estat")} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{t("Todas mis propuestas","Totes les meues propostes")} ({own.length})</option>{(["draft","pending","changes_requested","accepted","rejected","published","withdrawn"] as SubmissionStatus[]).map(s=><option value={s} key={s}>{statusLabel(s,locale==="va")}</option>)}</SelectField></header>
  {!shown.length&&<p className="mz-empty">{own.length?t("No tienes propuestas con este estado.","No tens propostes amb este estat."):t("Tu primera historia puede empezar arriba. Los borradores y las respuestas aparecerán aquí.","La primera història pot començar dalt. Els esborranys i les respostes apareixeran ací.")}</p>}
  {shown.map(s=>{const status=proposalStatus(s), edition=data.editions.find(e=>e.id===s.edition_id);return <article key={s.id} className="mz-tracker-row"><div className="mz-tracker-title"><span className={`mz-status-tag mz-status-${status}`}>{statusLabel(status,locale==="va")}</span><time dateTime={s.updated_at??s.created_at}>{new Date(s.updated_at??s.created_at).toLocaleDateString(locale==="va"?"ca-ES":"es-ES",{day:"numeric",month:"short"})}</time><h3>{s.title||t("Borrador sin título","Esborrany sense títol")}</h3><p>{s.section??"Vida de campus"} · {(s.images??[]).length} {(s.images??[]).length===1?t("imagen","imatge"):t("imágenes","imatges")}{edition&&` · ${edition.title}`}</p></div>
   {s.editorial_note&&<div className="mz-editor-response"><strong>{t("Respuesta editorial","Resposta editorial")}</strong><p>{s.editorial_note}</p></div>}
   {status==="accepted"&&<p className="mz-field-help">{edition?t("Seleccionada para una edición. Todavía no está publicada.","Seleccionada per a una edició. Encara no està publicada."):t("Aceptada. Pendiente de asignar una edición.","Acceptada. Pendent d’assignar una edició.")}</p>}
   {status==="pending"&&<p className="mz-field-help">{t("El equipo editorial todavía no ha decidido. Si necesitas editarla, retírala primero.","L’equip editorial encara no ha decidit. Si necessites editar-la, retira-la primer.")}</p>}
   <div className="mz-tracker-actions">{canEditProposal(s)&&<button className="mz-link" disabled={busy} onClick={()=>onEdit(s)}>{status==="draft"?t("Continuar borrador","Continuar esborrany"):t("Editar y volver a enviar","Editar i tornar a enviar")}<ArrowUpRight/></button>}{s.consent&&<button className="mz-link" disabled={busy} onClick={()=>setConfirm(s.id)}>{t("Retirar permiso","Retirar permís")}</button>}</div>
   {confirm===s.id&&<div className="mz-withdraw-confirm"><p>{t("Se retirará de la revista y del archivo. Conservarás la propuesta para editarla o enviarla de nuevo.","Es retirarà de la revista i de l’arxiu. Conservaràs la proposta per a editar-la o enviar-la de nou.")}</p><button className="mz-link" disabled={busy} onClick={async()=>{if(await act("withdraw",{id:s.id}))setConfirm("");}}>{t("Sí, retirar permiso","Sí, retirar permís")}</button><button className="mz-link" disabled={busy} onClick={()=>setConfirm("")}>{t("Cancelar","Cancel·lar")}</button></div>}
   <details className="mz-proposal-detail"><summary>{t("Ver propuesta e historial","Vore proposta i historial")}</summary><article className="mz-story mz-preview-story"><div className="mz-story-copy"><h3>{s.title}</h3><MagazineStoryBody body={s.body} summary={s.summary} images={s.images} layout={s.layout}/><footer>{s.attribution}</footer></div></article>{s.author_note&&<p><strong>{t("Tu nota privada: ","La teua nota privada: ")}</strong>{s.author_note}</p>}<ol className="mz-proposal-timeline">{(s.history??[]).map((entry,i)=><li key={i}><strong>{statusLabel(entry.status,locale==="va")}</strong><time dateTime={entry.at}>{new Date(entry.at).toLocaleString(locale==="va"?"ca-ES":"es-ES")}</time>{entry.note&&<p>{entry.note}</p>}</li>)}</ol></details>
  </article>;})}
 </section>;
}

export function EditorialReviewQueue(){
 const {data,busy}=useStudio(),{locale,demo}=useCommunity();const t=(es:string,va:string)=>locale==="va"?va:es;
 const pending=data.submissions.filter(s=>s.consent&&proposalStatus(s)==="pending");
 return <details className="mz-review-queue"><summary>{t("Revisar propuestas","Revisar propostes")} · {pending.length}{demo&&t(" · simulación editorial"," · simulació editorial")}</summary><p className="mz-field-help">{t("La aceptación no publica la pieza: después debes asignarla a una edición. Pide cambios para que el autor revise y autorice una nueva versión.","L’acceptació no publica la peça: després has d’assignar-la a una edició. Demana canvis perquè l’autor revise i autoritze una nova versió.")}</p>{!pending.length&&<p className="mz-empty">{t("No quedan propuestas pendientes.","No queden propostes pendents.")}</p>}{pending.map(s=><ReviewProposal key={`${s.id}-${s.revision}`} submission={s} busy={busy}/>)}</details>;
}
function ReviewProposal({submission:s,busy}:{submission:Submission;busy:boolean}){
 const {act}=useStudio(),{locale}=useCommunity();const t=(es:string,va:string)=>locale==="va"?va:es;
 const [decision,setDecision]=useState("accepted"),[note,setNote]=useState("");
 return <article className="mz-review-item"><p className="mz-folio">{s.section} · {s.attribution}</p><h3>{s.title}</h3><details><summary>{t("Leer la propuesta completa","Llegir la proposta completa")}</summary><div className="mz-story"><div className="mz-story-copy"><MagazineStoryBody body={s.body} summary={s.summary} images={s.images} layout={s.layout}/></div></div>{safeWebUrl(s.source_url)&&<a className="mz-link" href={s.source_url} target="_blank" rel="noopener noreferrer">{t("Consultar fuente","Consultar font")}</a>}{s.author_note&&<p className="mz-editor-response">{t("Nota del autor: ","Nota de l’autor: ")}{s.author_note}</p>}</details><form onSubmit={e=>{e.preventDefault();void act("review_submission",{id:s.id,status:decision,note});}}><SelectField label={t("Decisión editorial","Decisió editorial")} value={decision} onChange={e=>setDecision(e.target.value)}><option value="accepted">{t("Aceptar","Acceptar")}</option><option value="changes_requested">{t("Pedir cambios","Demanar canvis")}</option><option value="rejected">{t("Rechazar","Rebutjar")}</option></SelectField><TextArea label={t("Respuesta para el autor","Resposta per a l’autor")} required={decision!=="accepted"} minLength={decision!=="accepted"?5:undefined} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} rows={3}/><Action disabled={busy}><Check/>{t("Guardar decisión","Guardar decisió")}</Action></form></article>;
}
