"use client";
import { useState } from "react";
import { ArrowUpRight, BookOpen, Check, Newspaper, Plus } from "lucide-react";
import type { Submission } from "@/lib/community/studio/types";
import { safeWebUrl } from "@/lib/community/studio/types";
import { matches, useCommunity } from "./context";
import { Action, SelectField, TextArea, TextField } from "./controls";
import { StudioStatus, useStudio } from "./studio-context";

export function MagazineTeaser() {
  const {locale,go} = useCommunity(), {data} = useStudio();
  const latest = data.editions.find(e=>e.published);
  return <section className="st-magazine-teaser"><div className="st-paper-icon" aria-hidden="true"><Newspaper/><span>E.</span></div><div><p className="st-kicker">{locale==="va"?"LA REVISTA DE LA COMUNITAT":"LA REVISTA DE LA COMUNIDAD"}</p><h2>{locale==="va"?"Esta setmana en Entreclase":"Esta semana en Entreclase"}</h2><p>{latest?.title??(locale==="va"?"El que estem fent junts mereix que es conte.":"Lo que estamos haciendo juntos merece que se cuente.")}</p></div><button className="st-text-action" onClick={()=>go("magazine")}>{latest?(locale==="va"?"Llegir l’edició":"Leer la edición"):(locale==="va"?"Conéixer la revista":"Conocer la revista")}<ArrowUpRight/></button></section>;
}
export function Magazine() {
  const {locale,me,query} = useCommunity(), {data,loading,unavailable,act,busy} = useStudio();
  const t=(es:string,va:string)=>locale==="va"?va:es;
  const [edition,setEdition] = useState(""), [proposing,setProposing] = useState(false);
  const published=data.editions.filter(x=>x.published), selected=published.find(x=>x.id===edition)??published[0];
  const pieces=data.submissions.filter(x=>x.consent&&x.edition_id===selected?.id&&matches(query,x.title,x.body,x.attribution));
  return <div className="st-page st-magazine"><header className="st-masthead"><div className="st-issue-line"><span>ENTRECLASE · VALÈNCIA</span><span>{selected?new Intl.DateTimeFormat(locale==="va"?"ca-ES":"es-ES",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Madrid"}).format(new Date(`${selected.date}T12:00:00Z`)):t("PRIMERA EDICIÓN EN PREPARACIÓN","PRIMERA EDICIÓ EN PREPARACIÓ")}</span></div><p className="st-kicker">{t("LA REVISTA","LA REVISTA")}</p><h1>{t("Esta semana","Esta setmana")}<br/><em>en Entreclase.</em></h1><div className="st-masthead-footer"><p>{t("Gente de aquí. Cosas que están pasando. Y un hueco para ti.","Gent d’ací. Coses que estan passant. I un lloc per a tu.")}</p><span aria-hidden="true">E<span>↗</span></span></div></header>
    <StudioStatus/>
    <div className="st-edition-bar"><SelectField label={t("Archivo de ediciones","Arxiu d’edicions")} value={selected?.id??""} onChange={e=>setEdition(e.target.value)}>{!published.length&&<option value="">{t("Sin ediciones publicadas","Sense edicions publicades")}</option>}{published.map(e=><option key={e.id} value={e.id}>{e.date} · {e.title}</option>)}</SelectField><button disabled={loading||unavailable||busy} className="st-text-action" onClick={()=>setProposing(x=>!x)}><Plus/>{proposing?t("Cerrar propuesta","Tancar proposta"):t("Proponer para la edición semanal","Proposar per a l’edició setmanal")}</button></div>
    {proposing&&<ProposalForm onDone={()=>setProposing(false)}/>}
    {selected&&<section aria-labelledby="edition-heading"><div className="st-edition-intro"><p className="st-kicker">{t("ESTA EDICIÓN","ESTA EDICIÓ")}</p><h2 id="edition-heading">{selected.title}</h2><span>{pieces.length} {pieces.length===1?t("historia para entrar a formar parte","història per a entrar a formar part"):t("historias para entrar a formar parte","històries per a entrar a formar part")}</span></div><div className="st-editorial-grid">{pieces.map((piece,index)=><MagazinePiece key={piece.id} piece={piece} index={index}/>)}</div>{!pieces.length&&<p className="st-empty">{query?t("No hay piezas que coincidan con tu búsqueda.","No hi ha peces que coincidisquen amb la cerca."):t("Las piezas de esta edición ya no están disponibles. Sus autores pueden retirar el permiso en cualquier momento.","Les peces d’esta edició ja no estan disponibles. Els autors poden retirar el permís en qualsevol moment.")}</p>}</section>}
    {!loading&&!selected&&<div className="st-first-issue"><BookOpen aria-hidden="true"/><h2>{t("La primera página aún está por escribir.","La primera pàgina encara està per escriure.")}</h2><p>{t("Un proyecto que necesita manos. Algo que habéis terminado. Un plan al que todavía se puede llegar. La primera edición empieza con vuestras propuestas.","Un projecte que necessita mans. Alguna cosa que heu acabat. Un pla al qual encara es pot arribar. La primera edició comença amb les vostres propostes.")}</p></div>}
    <section className="st-editorial-note"><span>01—06</span><div><h3>{t("Seis piezas. Una razón para estar aquí.","Sis peces. Una raó per a estar ací.")}</h3><p>{t("Seleccionamos por utilidad, actualidad y variedad de carreras y campus. También hay sitio para quien acaba de empezar. Los likes y los ClasiCoins no compran un hueco.","Seleccionem per utilitat, actualitat i varietat de carreres i campus. També hi ha lloc per a qui acaba de començar. Els likes i els ClasiCoins no compren un lloc.")}</p><p>{t("Solo dentro de la comunidad verificada. Publicar fuera, por correo o en redes necesitaría otra autorización.","Només dins de la comunitat verificada. Publicar fora, per correu o en xarxes necessitaria una altra autorització.")}</p></div></section>
    {data.submissions.some(x=>x.author===me.user_id)&&<section className="st-my-proposals"><h2>{t("Tus propuestas. Tú decides.","Les teues propostes. Tu decidixes.")}</h2>{data.submissions.filter(x=>x.author===me.user_id).map(s=><article key={s.id}><div><h3>{s.title}</h3><p>{!s.consent?t("Permiso retirado. No aparece en ninguna edición.","Permís retirat. No apareix en cap edició."):s.edition_id?t("Seleccionada para una edición","Seleccionada per a una edició"):t("Autorizada · pendiente de selección editorial","Autoritzada · pendent de selecció editorial")}</p><details><summary>{t("Ver la versión autorizada","Vore la versió autoritzada")}</summary><p>{s.body}</p><small>{s.attribution}</small></details></div>{s.consent&&<button className="st-text-action" disabled={busy} onClick={()=>void act("withdraw",{id:s.id})}>{t("Retirar permiso","Retirar permís")}</button>}</article>)}</section>}
    {data.editor&&<EditorialDesk/>}
  </div>;
}
function MagazinePiece({piece:s,index}:{piece:Submission;index:number}) {
  const {go,locale}=useCommunity(); const t=(es:string,va:string)=>locale==="va"?va:es;
  function openSource() {
    go(s.kind==="project"?"projects":s.kind==="plan"?"plans":"messages");
    if(s.kind==="project"){const url=new URL(location.href);url.searchParams.set("project",s.source_id);history.replaceState(null,"",url);}
  }
  return <article className={`st-piece st-piece-${index%3}`}><div className="st-piece-art" aria-hidden="true"><span>{s.kind==="project"?"↗":s.kind==="plan"?"✳":"“"}</span><i>{String(index+1).padStart(2,"0")}</i><div className="st-piece-orbit"/></div><div className="st-piece-copy"><p className="st-kicker">{s.kind==="project"?t("ALGO POR HACER JUNTOS","ALGUNA COSA PER A FER JUNTS"):s.kind==="plan"?t("HAY SITIO","HI HA LLOC"):s.kind==="post"?t("UNA CONVERSACIÓN QUE MERECE LA PENA","UNA CONVERSA QUE VAL LA PENA"):t("DESDE EL CAMPUS","DES DEL CAMPUS")}</p><h3>{s.title}</h3><p>{s.body}</p><footer><span>{s.attribution}</span>{s.kind==="initiative"?safeWebUrl(s.source_url)&&<a className="st-text-action" href={s.source_url} target="_blank" rel="noopener noreferrer">{t("Ver fuente","Vore font")}<ArrowUpRight/></a>:<button className="st-text-action" onClick={openSource}>{s.kind==="project"?t("Quiero saber más","Vull saber-ne més"):s.kind==="plan"?t("Ver los planes","Vore els plans"):t("Ir al foro","Anar al fòrum")}<ArrowUpRight/></button>}</footer></div></article>;
}
function ProposalForm({onDone}:{onDone:()=>void}) {
  const {data:community,me,locale}=useCommunity(),{data,act,busy}=useStudio();
  const t=(es:string,va:string)=>locale==="va"?va:es;
  const [kind,setKind]=useState<Submission["kind"]>("project"),[source,setSource]=useState(""),[title,setTitle]=useState(""),[body,setBody]=useState(""),[url,setUrl]=useState("");
  const sources=kind==="project"?data.projects.filter(x=>x.owner===me.user_id).map(x=>({id:x.id,title:x.title})):kind==="plan"?community.plans.filter(x=>x.creator_id===me.user_id).map(x=>({id:x.id,title:x.title})):kind==="post"?community.posts.filter(x=>x.author_id===me.user_id&&!x.group_id).map(x=>({id:x.id,title:x.body.slice(0,100)})):[];
  return <form className="st-form st-proposal" onSubmit={async e=>{e.preventDefault();if(await act("submit",{kind,source_id:source,source_url:url,title,body,consent:new FormData(e.currentTarget).has("consent")}))onDone();}}><div><p className="st-kicker">{t("TU PROPUESTA","LA TEUA PROPOSTA")}</p><h2>{t("Lo que autorizas es lo que se publica.","El que autoritzes és el que es publica.")}</h2><SelectField label={t("Qué quieres proponer","Què vols proposar")} value={kind} onChange={e=>{setKind(e.target.value as Submission["kind"]);setSource("");}}><option value="project">{t("Mi proyecto","El meu projecte")}</option><option value="plan">{t("Mi plan","El meu pla")}</option><option value="post">{t("Mi hilo público","El meu fil públic")}</option><option value="initiative">{t("Una iniciativa con fuente","Una iniciativa amb font")}</option></SelectField>{kind!=="initiative"?<SelectField label={t("Contenido propio","Contingut propi")} value={source} onChange={e=>setSource(e.target.value)} required><option value="">{t("Selecciona tu contenido","Selecciona el teu contingut")}</option>{sources.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</SelectField>:<TextField type="url" pattern="https?://.*" label={t("Fuente identificada · enlace","Font identificada · enllaç")} required value={url} maxLength={500} onChange={e=>setUrl(e.target.value)}/>}
    <TextField label={t("Titular de la tarjeta","Titular de la targeta")} required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/><TextArea label={t("Texto exacto · escrito por ti","Text exacte · escrit per tu")} required minLength={20} maxLength={800} value={body} onChange={e=>setBody(e.target.value)}/></div><div><p className="st-kicker">{t("ASÍ SE VERÁ TU PIEZA","AIXÍ ES VORÀ LA TEUA PEÇA")}</p><article className="st-consent-preview"><span className="st-preview-mark" aria-hidden="true">↗</span><h3>{title||t("Tu titular aquí","El teu titular ací")}</h3><p>{body||t("Tu texto aparecerá aquí, con tus palabras.","El teu text apareixerà ací, amb les teues paraules.")}</p><footer>{me.name}</footer></article><p className="st-caption">{t("Se conservan exactamente el titular, el texto y la atribución. El tamaño se adapta a la portada y al archivo. No se incluyen imágenes, respuestas de otras personas ni mensajes privados.","Es conserven exactament el titular, el text i l’atribució. La mida s’adapta a la portada i a l’arxiu. No s’inclouen imatges, respostes d’altres persones ni missatges privats.")}</p><label className="st-checkbox"><input name="consent" type="checkbox" required/>{t("Soy autor de este texto y autorizo esta versión en la revista y su adelanto en Inicio, solo para la comunidad verificada. Puedo retirar el permiso también del archivo.","Soc autor d’este text i autoritze esta versió en la revista i el seu avanç en Inici, només per a la comunitat verificada. Puc retirar el permís també de l’arxiu.")}</label><Action disabled={busy}><Check/>{t("Autorizar y enviar propuesta","Autoritzar i enviar proposta")}</Action><p className="st-caption">{t("Autorizar no garantiza la selección. Para cambiar el texto, retira esta propuesta y envía una nueva.","Autoritzar no garantix la selecció. Per a canviar el text, retira esta proposta i envia’n una nova.")}</p></div></form>;
}
function EditorialDesk() {
  const {data,act,busy}=useStudio(),{locale,demo}=useCommunity();const t=(es:string,va:string)=>locale==="va"?va:es;
  const [edition,setEdition]=useState("");
  const drafts=data.editions.filter(e=>!e.published), selected=drafts.find(e=>e.id===edition)??drafts[0];
  return <details className="st-editorial-desk"><summary>{t("Mesa de edición","Taula d’edició")} {demo&&t("· simulación editorial","· simulació editorial")}<Plus/></summary><p>{t("Selección manual de hasta seis piezas autorizadas. Revisa las fuentes y alterna carreras, campus y autores.","Selecció manual de fins a sis peces autoritzades. Revisa les fonts i alterna carreres, campus i autors.")}</p><form className="st-form-grid" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await act("create_edition",Object.fromEntries(new FormData(form))))form.reset();}}><TextField name="title" label={t("Título de la edición","Títol de l’edició")} required minLength={3} maxLength={120}/><TextField name="date" label={t("Fecha de edición","Data d’edició")} type="date" required/><Action disabled={busy}>{t("Crear borrador","Crear esborrany")}</Action></form>{selected&&<><SelectField label={t("Edición en preparación","Edició en preparació")} value={selected.id} onChange={e=>setEdition(e.target.value)}>{drafts.map(x=><option key={x.id} value={x.id}>{x.date} · {x.title}</option>)}</SelectField><div className="st-editorial-candidates">{data.submissions.filter(s=>s.consent&&(!s.edition_id||s.edition_id===selected.id)).map(s=><article key={s.id}><label className="st-checkbox"><input type="checkbox" checked={s.edition_id===selected.id} disabled={busy} onChange={e=>void act("select",{id:s.id,edition:selected.id,on:e.target.checked})}/><strong>{s.title}</strong></label><p>{s.body}</p><small>{s.attribution} · {s.kind==="project"?t("Proyecto","Projecte"):s.kind==="plan"?t("Plan","Pla"):s.kind==="post"?t("Hilo","Fil"):t("Iniciativa","Iniciativa")}</small>{safeWebUrl(s.source_url)&&<a href={s.source_url} target="_blank" rel="noopener noreferrer">{t("Revisar fuente","Revisar font")}</a>}</article>)}</div><form onSubmit={async e=>{e.preventDefault();await act("publish_edition",{edition:selected.id});}}><label className="st-checkbox"><input required type="checkbox"/>{t("He revisado la selección, sus fuentes y las autorizaciones. Esta edición será visible para toda la comunidad verificada.","He revisat la selecció, les fonts i les autoritzacions. Esta edició serà visible per a tota la comunitat verificada.")}</label><Action disabled={busy||!data.submissions.some(s=>s.edition_id===selected.id&&s.consent)}>{t("Publicar edición","Publicar edició")}</Action></form></>}</details>;
}
