"use client";
import { useEffect, useRef, useState } from "react";
import { CalendarDays, MapPin, Plus, ArrowUpRight, Coffee, Waves, Sun, Lightbulb, Footprints, Check } from "lucide-react";
import { useCommunity, matches } from "./context";
import { Action, Avatar, Chips, Confirm, Empty, ExternalLink, Modal, Person, SelectField, TextArea, TextField } from "./controls";
import { places, type Plan } from "@/lib/community/types";
import { formatDate, localName } from "@/lib/community/copy";
import { CoinAmount, SpendNotice, RewardHint } from "./unicoins";
import { useClock } from "@/lib/community/use-clock";
import { COIN_RULES } from "@/lib/community/unicoins";
import { unicoinCopy } from "@/lib/i18n/unicoins";
import { gameForKind, spotOf } from "@/lib/community/places";
import { gameById, languageIndex } from "@/lib/community/games/catalog";
import { GameLink } from "./games";
import type { Locale } from "@/lib/i18n/routes";
const icons=[Coffee,Footprints,Waves,Sun,Lightbulb];
export function Plans(){const {c,locale,data,me,query,repo,run}=useCommunity();const [filter,setFilter]=useState("all"),[place,setPlace]=useState(""),[creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null);const plans=data.plans.filter(p=>(filter!=="mine"||data.planMembers.some(m=>m.plan_id===p.id&&m.user_id===me.user_id))&&(!place||p.place===place)&&matches(query,p.title,p.description,p.place)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));const detail=data.plans.find(p=>p.id===selected);return <><div className="u-toolbar"><Chips label={c("plans")} value={filter} onChange={setFilter} options={[{value:"all",label:c("discover")},{value:"mine",label:c("myPlans")}]}/><Action onClick={()=>setCreating(true)}><Plus/>{c("createPlan")}<CoinAmount amount={-COIN_RULES.createEvent}/></Action></div><div className="u-filter-row"><SelectField label={c("place")} value={place} onChange={e=>setPlace(e.target.value)}><option value="">{c("all")}</option>{places.map(p=><option key={p} value={p}>{localName(p,locale)}</option>)}</SelectField><p className="u-muted u-small">{c("valenciaTime")}</p></div><div className="u-plan-grid">{plans.map(plan=><PlanCard key={plan.id} plan={plan} onOpen={()=>setSelected(plan.id)}/>)}</div>{!plans.length&&<Empty title={c("noPlans")} body={c("noPlansBody")}/>}<CreatePlanModal open={creating} onOpenChange={setCreating}/><Modal open={!!detail} onOpenChange={open=>{if(!open)setSelected(null);}} title={detail?.title??c("planDetails")} description={detail?formatDate(detail.starts_at,locale):undefined}>{detail&&<><div className="u-plan-detail"><span className="u-location"><MapPin/>{localName(detail.place,locale)}</span><p>{detail.description}</p><div className="u-meeting"><strong>{c("meeting")}</strong><p>{detail.meeting_point}</p><ExternalLink href={mapUrl(detail)}>{c("location")}</ExternalLink></div><Person id={detail.creator_id}/><h3>{c("attendees")} · {data.planMembers.filter(m=>m.plan_id===detail.id).length}/{detail.capacity}</h3><div className="u-attendees">{data.planMembers.filter(m=>m.plan_id===detail.id).map(m=><Person key={m.user_id} id={m.user_id}/>)}</div><Attendance plan={detail}/><RewardHint kind="event" resourceId={detail.id} own={detail.creator_id===me.user_id} participated={data.planMembers.some(m=>m.plan_id===detail.id&&m.user_id===me.user_id)}/>{detail.creator_id===me.user_id&&<Confirm title={c("cancelPlan")} description={`${c("cancelPlanHelp")} ${unicoinCopy(locale)("noRefund")}`} onConfirm={async()=>{const ok=await run(()=>repo.removePlan(detail.id),c("removed"));if(ok)setSelected(null);return ok;}}><Action secondary className="u-danger-text">{c("cancelPlan")}</Action></Confirm>}</div></>}</Modal></>;}
export function mapUrl(plan:Plan){return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(plan.place.replace(" · "," ")+", Valencia");}
export function Attendance({plan}:{plan:Plan}){const now=useClock();const {c,me,data,repo,run,busy}=useCommunity();const joined=data.planMembers.some(m=>m.plan_id===plan.id&&m.user_id===me.user_id),full=data.planMembers.filter(m=>m.plan_id===plan.id).length>=plan.capacity,past=new Date(plan.starts_at).getTime()<now,own=plan.creator_id===me.user_id;return <Action secondary={joined} disabled={busy||past||own||full&&!joined} onClick={()=>void run(()=>repo.joinPlan(plan.id,!joined),"")}>{past?c("ended"):own?<><Check/>{c("organiser")}</>:joined?<><Check/>{c("leave")}</>:full?c("full"):c("join")}</Action>;}
function PlanCard({plan,onOpen}:{plan:Plan;onOpen:()=>void}){const now=useClock();const {c,locale,data,me}=useCommunity();const index=Math.max(0,places.indexOf(plan.place));const Icon=icons[index%icons.length]??MapPin;const members=data.planMembers.filter(m=>m.plan_id===plan.id);return <article className="u-card u-plan"><button className={`u-plan-cover u-cover-${index%4}`} onClick={onOpen} aria-label={`${c("planDetails")}: ${plan.title}`}><span className="u-place-tag"><MapPin aria-hidden="true"/>{localName(plan.place,locale)}</span><Icon className="u-plan-doodle" aria-hidden="true"/><span className="u-cover-note" aria-hidden="true">{index===0?"un café?":index===1?"fora!":index===2?"sol i sal":index===3?"a poqueta nit":"i si…?"}</span></button><div className="u-plan-content"><p className="u-plan-date"><CalendarDays aria-hidden="true"/><time dateTime={plan.starts_at}>{formatDate(plan.starts_at,locale)}</time></p><h2><button onClick={onOpen}>{plan.title}</button></h2><p className="u-plan-description">{plan.description}</p><div className="u-plan-members"><div className="u-avatar-stack">{members.slice(0,4).map(m=><Avatar key={m.user_id} size="small" person={data.profiles.find(p=>p.user_id===m.user_id)}/>)}</div><span>{Math.max(0,plan.capacity-members.length)} {c("placesLeft")}</span></div><div className="u-plan-footer"><Attendance plan={plan}/><button className="u-text-link" onClick={onOpen}>{c("planDetails")}<ArrowUpRight aria-hidden="true"/></button></div>{new Date(plan.starts_at).getTime()>now&&<RewardHint kind="event" resourceId={plan.id} own={plan.creator_id===me.user_id} participated={members.some(m=>m.user_id===me.user_id)}/>}</div></article>;}

export function CreatePlanModal({open,onOpenChange,defaultPlace}:{open:boolean;onOpenChange:(value:boolean)=>void;defaultPlace?:string}){const {c,locale,data,repo,run,busy}=useCommunity();const requestId=useRef<string|null>(null);useEffect(()=>{if(open)requestId.current=null;},[open]);return <Modal open={open} onOpenChange={onOpenChange} title={c("createPlan")} description={c("plansSub")}><form className="u-form" onChange={()=>{requestId.current=null;}} onSubmit={async e=>{e.preventDefault();const action=requestId.current??=crypto.randomUUID();const f=new FormData(e.currentTarget);const date=new Date(String(f.get("date")));if(await run(()=>repo.createPlan({title:String(f.get("title")),description:String(f.get("description")),place:String(f.get("place")),meeting_point:String(f.get("meeting")),starts_at:date.toISOString(),capacity:Number(f.get("capacity"))},action))){requestId.current=null;onOpenChange(false);}}}><TextField label={c("title")} name="title" placeholder={c("planPlaceholder")} required minLength={3} maxLength={100}/><TextArea label={c("description")} name="description" rows={3} maxLength={1200}/><SelectField label={c("place")} name="place" defaultValue={defaultPlace||places[0]}>{places.map(p=><option key={p} value={p}>{localName(p,locale)}</option>)}</SelectField><TextField label={c("meeting")} name="meeting" placeholder={c("meetingPlaceholder")} required minLength={2} maxLength={160}/><div className="u-field-grid"><TextField label={c("date")} name="date" type="datetime-local" required/><TextField label={c("capacity")} name="capacity" type="number" min={2} max={60} defaultValue={8} required/></div><SpendNotice amount={COIN_RULES.createEvent}/><p className="u-coin-terms">{unicoinCopy(locale)("noRefund")}</p><Action type="submit" disabled={busy||data.wallet.balance<COIN_RULES.createEvent}>{busy?c("publishing"):c("create")}<CoinAmount amount={-COIN_RULES.createEvent}/><ArrowUpRight/></Action></form></Modal>;}
/* «Aquí también: <juego>»: el juego que encaja con el tipo de sitio. Lo usan el panel del mapa de Inicio y los filtros de Explorar. */
export function PlaceGame({place,className}:{place:string;className?:string}){const {c,locale}=useCommunity();const kind=spotOf(place)?.kind;const game=kind?gameById(gameForKind[kind]):undefined;if(!game)return null;return <p className={`u-place-game ${className??""}`}><span>{c("alsoHere")}</span> <GameLink id={game.id} className="u-text-link">{game.title[languageIndex(locale)]}<ArrowUpRight aria-hidden="true"/></GameLink></p>;}
/* El vacío de un lugar concreto, con las mismas palabras en Inicio y en Explorar. */
export function planHereEmpty(c:(key:"planHereEmpty")=>string,place:string,locale:Locale){return c("planHereEmpty").replace("{place}",localName(place,locale));}
