import { unicoinCopy } from "../i18n/unicoins";
import type { Locale } from "../i18n/routes";
const messages = {
 projectsTitle: ["Ideas que se hacen entre varios.", "Idees que es fan entre diversos."], projectsSub: ["Encuentra gente para hacerlo realidad.", "Troba gent per a fer-ho realitat."], magazine: ["Revista", "Revista"], magazineTitle: ["Esta semana en Entreclase", "Esta setmana en Entreclase"], magazineSub: ["Lo que estamos haciendo juntos.", "El que estem fent junts."],
 explore: ["Explorar", "Explorar"], exploreTitle: ["Hay más formas de encontrarse.", "Hi ha més formes de trobar-se."], exploreSub: ["Planes, gente, grupos e ideas para moverte por tu campus.", "Plans, gent, grups i idees per a moure’t pel teu campus."], exploreSections: ["Secciones para explorar", "Seccions per explorar"], exploreOverview: ["Ideas", "Idees"],
 unicoins:["ClasiCoins","ClasiCoins"],unicoinsTitle:["La moneda que se gana estando.","La moneda que es guanya participant."],unicoinsSub:["Participa. Gana ClasiCoins. Monta lo siguiente.","Participa. Guanya ClasiCoins. Munta el que vinga després."],
 home: ["Inicio", "Inici"], plans: ["Planes", "Plans"], groups: ["Grupos", "Grups"], campus: ["Campus", "Campus"], people: ["Gente", "Gent"], messages: ["Mensajes", "Missatges"], profile: ["Mi perfil", "El meu perfil"], discover: ["Descubrir", "Descobrir"],
 homeTitle: ["Tu gente. Por aquí.", "La teua gent. Per ací."], plansTitle: ["El «algún día» era hoy.", "L’«algun dia» era hui."], groupsTitle: ["Lo tuyo tiene grupo.", "Això teu té grup."], campusTitle: ["Mañana hay examen.", "Demà hi ha examen."], peopleTitle: ["El primer hola lo pones tú.", "El primer hola el poses tu."], messagesTitle: ["El foro donde empieza el plan.", "El fòrum on comença el pla."], profileTitle: ["Tú. Sin filtros raros.", "Tu. Sense filtres estranys."], discoverTitle: ["Hay más formas de encontrarse.", "Hi ha més formes de trobar-se."],
 homeSub: ["La universidad sigue después de clase.", "La universitat continua després de classe."], plansSub: ["Un sitio, una hora y alguien que se apunta.", "Un lloc, una hora i algú que s’apunta."], groupsSub: ["Para estudiar juntos. O para hablar de cualquier otra cosa.", "Per a estudiar junts. O per a parlar de qualsevol altra cosa."], campusSub: ["Encuentra apuntes, comparte los tuyos y localiza tu biblioteca.", "Troba apunts, compartix els teus i localitza la biblioteca."], peopleSub: ["Quizá os habéis cruzado veinte veces. Hoy podéis hablar.", "Potser vos heu trobat vint vegades. Hui podeu parlar."], messagesSub: ["Publica en el foro o habla en privado.", "Publica al fòrum o parla en privat."], profileSub: ["Lo justo para que tu gente te encuentre.", "El que cal perquè la teua gent et trobe."], discoverSub: ["Cuatro espacios para que cada semana tenga una historia distinta.", "Quatre espais perquè cada setmana tinga una història distinta."],
 demo: ["Estás en la demo", "Estàs en la demo"], demoHelp: ["Perfiles de ejemplo. Tus cambios solo duran esta visita y no se comparten con otras personas.", "Perfils d’exemple. Els canvis només duren esta visita i no es compartixen amb altres persones."], realAccess: ["Ir al acceso real", "Anar a l’accés real"], backLanding: ["Volver a la landing", "Tornar a la pàgina inicial"], more: ["Más", "Més"], navigation: ["Navegación de Entreclase", "Navegació d’Entreclase"], close: ["Cerrar", "Tancar"], search: ["Buscar en esta sección…", "Buscar en esta secció…"], refresh: ["Actualizar", "Actualitzar"], loading: ["Buscando a tu gente…", "Buscant la teua gent…"], retry: ["Volver a intentarlo", "Tornar a intentar-ho"], preparing: ["Estamos preparando tu campus.", "Estem preparant el teu campus."], preparingBody: ["El acceso con correo universitario todavía no está activo. Mientras, puedes recorrer la aplicación de ejemplo.", "L’accés amb correu universitari encara no està actiu. Mentrestant, pots recórrer l’aplicació d’exemple."], exploreDemo: ["Dar una vuelta por dentro", "Fer una volta per dins"], login: ["Iniciar sesión", "Iniciar sessió"], logout: ["Cerrar sesión", "Tancar sessió"], accessError: ["No hemos podido abrir tu campus.", "No hem pogut obrir el teu campus."],
 welcome: ["Valencia ya pone el sitio.", "València ja posa el lloc."], welcomeLine: ["Tú pon el primer hola.", "Tu posa el primer hola."], welcomeBody: ["El algoritmo no baja al Turia. Tú sí puedes.", "L’algoritme no baixa al Túria. Tu sí que pots."], findPlan: ["Encontrar un plan", "Trobar un pla"], welcomeAlt: ["Un grupo de estudiantes camina y conversa por el campus.", "Un grup d’estudiants camina i conversa pel campus."],
 wall: ["Foro del campus", "Fòrum del campus"], forum: ["Foro", "Fòrum"], privateMessages: ["Chat privado", "Xat privat"], messagesModes: ["Modos de mensajes", "Modes de missatges"], forumHelp: ["Un espacio abierto para publicar ideas, preguntas y planes del campus.", "Un espai obert per a publicar idees, preguntes i plans del campus."], privateMessagesHelp: ["Conversaciones privadas uno a uno con gente de tu campus.", "Converses privades u a u amb gent del teu campus."], following: ["Mis grupos", "Els meus grups"], all: ["Todo", "Tot"], post: ["Publicación", "Publicació"], question: ["Pregunta", "Pregunta"], composer: ["¿Qué se mueve por tu campus?", "Què es mou pel teu campus?"], composerHelp: ["Un plan, una duda o ese apunte que te falta.", "Un pla, un dubte o eixe apunt que et falta."], publish: ["Abrir hilo", "Obrir fil"], publishing: ["Guardando…", "Guardant…"], audience: ["Comunidad universitaria", "Comunitat universitària"], groupAudience: ["Publicar en un grupo", "Publicar en un grup"], liked: ["Te gusta", "T’agrada"], like: ["Me gusta", "M’agrada"], comments: ["Comentarios", "Comentaris"], comment: ["Comentar", "Comentar"], commentPlaceholder: ["Sigue la conversación…", "Continua la conversa…"], send: ["Enviar", "Enviar"], delete: ["Eliminar", "Eliminar"], deletePost: ["¿Eliminar esta publicación?", "Vols eliminar esta publicació?"], deleteHelp: ["También se eliminarán sus comentarios y me gusta.", "També s’eliminaran els comentaris i els m’agrada."], cancel: ["Cancelar", "Cancel·lar"], noPosts: ["Aquí cabe el primer hola.", "Ací cap el primer hola."], noPostsBody: ["Todavía no hay publicaciones con este filtro. Puedes empezar tú.", "Encara no hi ha publicacions amb este filtre. Pots començar tu."], student: ["Estudiante", "Estudiant"], verified: ["Correo universitario verificado", "Correu universitari verificat"], exampleImage: ["Imagen de ejemplo de una conversación en el campus.", "Imatge d’exemple d’una conversa al campus."],
 upcoming: ["Lo próximo", "El que ve ara"], myPlans: ["Mis planes", "Els meus plans"], createPlan: ["Montar un plan", "Muntar un pla"], planDetails: ["El plan", "El pla"], join: ["Me apunto", "M’apunte"], joined: ["Estás dentro", "Estàs dins"], leave: ["Ya no puedo ir", "Ja no puc anar"], organiser: ["Lo organizas tú", "L’organitzes tu"], full: ["Completo", "Complet"], ended: ["Ya ha pasado", "Ja ha passat"], placesLeft: ["plazas libres", "places lliures"], going: ["Se apuntan", "S’apunten"], attendees: ["Quién viene", "Qui ve"], location: ["Ver ubicación", "Vore la ubicació"], map: ["Mapa de lugares", "Mapa de llocs"], list: ["Ver planes", "Vore plans"], mapTitle: ["Valencia. Aquí fuera.", "València. Ací fora."], mapHelp: ["Elige un lugar para situarlo en el mapa y ver sus planes.", "Tria un lloc per a situar-lo al mapa i vore els plans."], mapFrame: ["Mapa del punto de encuentro", "Mapa del punt de trobada"], noPlans: ["La tarde está libre.", "La vesprada està lliure."], noPlansBody: ["No hay planes con este filtro. Monta el primero o prueba otro lugar.", "No hi ha plans amb este filtre. Munta el primer o prova un altre lloc."], noMyPlans: ["Todavía no tienes plan. Eso se arregla.", "Encara no tens pla. Això s’arregla."], title: ["Título", "Títol"], planPlaceholder: ["¿Café en Benimaclet?", "Café a Benimaclet?"], description: ["Cuéntalo un poco", "Conta-ho un poc"], date: ["Fecha y hora (hora de tu dispositivo)", "Data i hora (hora del teu dispositiu)"], valenciaTime: ["Los planes se muestran en hora de Valencia.", "Els plans es mostren en hora de València."], place: ["Lugar", "Lloc"], meeting: ["Punto de encuentro", "Punt de trobada"], meetingPlaceholder: ["Por ejemplo: junto a la entrada principal", "Per exemple: al costat de l’entrada principal"], capacity: ["Plazas, incluyéndote a ti", "Places, incloent-te a tu"], create: ["Crear", "Crear"], cancelPlan: ["Cancelar el plan", "Cancel·lar el pla"], cancelPlanHelp: ["El plan y las inscripciones se eliminarán para todos los participantes.", "El pla i les inscripcions s’eliminaran per a tots els participants."],
 createGroup: ["Crear un grupo", "Crear un grup"], study: ["Estudio", "Estudi"], leisure: ["Planes y aficiones", "Plans i aficions"], projects: ["Proyectos", "Projectes"], members: ["miembros", "membres"], member: ["Ya eres del grupo", "Ja eres del grup"], joinGroup: ["Unirme al grupo", "Unir-me al grup"], leaveGroup: ["Salir del grupo", "Eixir del grup"], viewGroup: ["Entrar al grupo", "Entrar al grup"], groupName: ["Nombre del grupo", "Nom del grup"], category: ["Tipo de grupo", "Tipus de grup"], groupPlaceholder: ["Los del tema 4", "Els del tema 4"], noGroups: ["Tu grupo puede empezar aquí.", "El teu grup pot començar ací."], groupOnly: ["Únete al grupo para publicar aquí.", "Unix-te al grup per a publicar ací."], groupCommunity: ["Grupos abiertos a la comunidad verificada.", "Grups oberts a la comunitat verificada."],
 notes: ["Apuntes", "Apunts"], libraries: ["Bibliotecas", "Biblioteques"], upload: ["Compartir apuntes", "Compartir apunts"], subject: ["Asignatura", "Assignatura"], download: ["Descargar", "Descarregar"], pdf: ["Archivo PDF · Máximo 10 MB", "Fitxer PDF · Màxim 10 MB"], file: ["Archivo", "Fitxer"], notePlaceholder: ["Tema 4. Ahora sí.", "Tema 4. Ara sí."], ownNotes: ["Los míos", "Els meus"], noNotes: ["El PDF todavía no ha aparecido.", "El PDF encara no ha aparegut."], noNotesBody: ["Prueba otra asignatura o comparte los apuntes que tienes.", "Prova una altra assignatura o compartix els apunts que tens."], deleteNote: ["¿Eliminar estos apuntes?", "Vols eliminar estos apunts?"], deleteNoteHelp: ["Se retirará la publicación y el archivo compartido.", "Es retirarà la publicació i el fitxer compartit."], libraryIntro: ["El sitio para estudiar también cuenta.", "El lloc per a estudiar també compta."], officialHours: ["Consulta horarios y salas en la web oficial.", "Consulta horaris i sales en el web oficial."], officialLink: ["Ver bibliotecas y horarios", "Vore biblioteques i horaris"],
 allCampuses: ["Todos los campus", "Tots els campus"], editProfile: ["Editar mi perfil", "Editar el meu perfil"], yourName: ["Tu nombre", "El teu nom"], yourCampus: ["Tu campus", "El teu campus"], yourDegree: ["Qué estudias", "Què estudies"], year: ["Curso", "Curs"], biography: ["Un poco de ti", "Un poc de tu"], interests: ["Lo que te mueve", "El que et mou"], chooseInterests: ["Elige hasta 5 intereses.", "Tria fins a 5 interessos."], color: ["Color de tu avatar", "Color del teu avatar"], save: ["Guardar", "Guardar"], sayHi: ["Decir hola", "Dir hola"], connect: ["Conectar", "Connectar"], noPeople: ["Prueba otra búsqueda.", "Prova una altra cerca."], relationshipFilter: ["Situación sentimental", "Situació sentimental"], allRelationships: ["Todas", "Totes"], relationshipStatus: ["Situación sentimental", "Situació sentimental"], relationshipStatusHelp: ["Elige qué quieres compartir. Puedes cambiarlo cuando quieras.", "Tria què vols compartir. Pots canviar-ho quan vulgues."], single: ["Soltero/a", "Solter/a"], in_relationship: ["En pareja", "En parella"], seeing_someone: ["Estoy conociendo a alguien", "Estic coneixent algú"], complicated: ["Es complicado", "És complicat"], prefer_not_to_say: ["Prefiero no decirlo", "Preferisc no dir-ho"], connectHelp: ["Si os apetece hablar, abrid una conversación privada.", "Si vos ve de gust parlar, obriu una conversa privada."], introTitle: ["Antes del primer hola.", "Abans del primer hola."], introBody: ["Sitúa tu campus y cuenta qué te gusta. La gente necesita algo más que tu matrícula.", "Situa el teu campus i conta què t’agrada. La gent necessita alguna cosa més que la matrícula."], start: ["Entrar a mi campus", "Entrar al meu campus"], profileVisible: ["Este perfil será visible para la comunidad universitaria. Tu correo no se publica.", "Este perfil serà visible per a la comunitat universitària. El teu correu no es publica."], profileSections: ["Secciones de perfil", "Seccions del perfil"], publications: ["Publicaciones", "Publicacions"], about: ["Sobre mí", "Sobre mi"], profileStats: ["Resumen del perfil", "Resum del perfil"], profilePostsCount: ["publicaciones", "publicacions"], profilePlansCount: ["planes creados", "plans creats"], profileGroupsCount: ["grupos", "grups"], profileAboutTitle: ["Más sobre ti", "Més sobre tu"], profileAboutBody: ["Tu campus, tus intereses y las cosas que te mueven.", "El teu campus, els teus interessos i les coses que et mouen."], myPosts: ["Lo que has compartido", "El que has compartit"], noBio: ["El primer hola todavía está por escribir.", "El primer hola encara està per escriure."],
 noMessages: ["Empieza con un hola.", "Comença amb un hola."], noMessagesBody: ["Encuentra a alguien en Gente y abre una conversación.", "Troba algú en Gent i obri una conversa."], selectChat: ["Elige una conversación.", "Tria una conversa."], privateChat: ["Solo podéis leerla las dos personas de la conversación.", "Només poden llegir-la les dos persones de la conversa."], messagePlaceholder: ["¿Te apuntas?", "T’apuntes?"], demoMessages: ["Esta conversación es de ejemplo. Nadie recibe lo que escribes aquí.", "Esta conversa és d’exemple. Ningú rep el que escrius ací."], conversation: ["Conversación", "Conversa"], backChats: ["Volver a conversaciones", "Tornar a les converses"],
 noteCleanup: ["El archivo se retiró, pero falta quitar su ficha. Vuelve a pulsar Eliminar.", "El fitxer s’ha retirat, però falta llevar-ne la fitxa. Torna a prémer Eliminar."],
 done: ["Guardado.", "Guardat."], posted: ["Ya está en tu campus.", "Ja està al teu campus."], refreshAfterSave: ["El cambio se guardó. Pulsa Actualizar para volver a cargar la pantalla.", "El canvi s’ha guardat. Prem Actualitzar per a tornar a carregar la pantalla."], genericError: ["No hemos podido completar este paso. Revisa tu conexión y vuelve a intentarlo.", "No hem pogut completar este pas. Revisa la connexió i torna a intentar-ho."], setupError: ["El campus todavía no está conectado. Puedes explorar la demo mientras se prepara el acceso.", "El campus encara no està connectat. Pots explorar la demo mentre es prepara l’accés."], fullError: ["Alguien se ha adelantado. Este plan ya está completo.", "Algú s’ha avançat. Este pla ja està complet."], pastError: ["Elige una fecha futura. Ese plan ya ha pasado.", "Tria una data futura. Eixe pla ja ha passat."], validationError: ["Revisa los campos marcados y completa lo que falta.", "Revisa els camps marcats i completa el que falta."], fileError: ["Necesitas un PDF válido de hasta 10 MB.", "Necessites un PDF vàlid de fins a 10 MB."], peerError: ["Esta persona ya no está disponible para nuevas conversaciones.", "Esta persona ja no està disponible per a converses noves."], removed: ["Eliminado.", "Eliminat."], emptySearch: ["No hay resultados para esa búsqueda.", "No hi ha resultats per a eixa cerca."],
 greetMorning: ["Buenos días", "Bon dia"], greetAfternoon: ["Buenas tardes", "Bona vesprada"], greetEvening: ["Buenas noches", "Bona nit"], homeHeroLine: ["¿Qué te apetece hoy?", "Què et ve de gust hui?"], homeHeroBody: ["Elige un punto del mapa, apúntate a un plan o monta el tuyo. Aquí se empieza haciendo.", "Tria un punt del mapa, apunta’t a un pla o munta el teu. Ací es comença fent."], homeStatsPeople: ["personas cerca", "persones a prop"], homeStatsPlans: ["planes esta semana", "plans esta setmana"], homeStatsGroups: ["grupos activos", "grups actius"],
 quickActions: ["Atajos", "Dreceres"], quickActionsHelp: ["Todo lo que puedes hacer sin salir de aquí.", "Tot el que pots fer sense eixir d’ací."], quickPlan: ["Montar un plan", "Muntar un pla"], quickPlanHelp: ["Sitio, hora y plazas.", "Lloc, hora i places."], quickThread: ["Abrir un hilo", "Obrir un fil"], quickThreadHelp: ["Una duda o una idea.", "Un dubte o una idea."], quickNotes: ["Subir apuntes", "Pujar apunts"], quickNotesHelp: ["Comparte tu PDF.", "Compartix el teu PDF."], quickGroup: ["Crear un grupo", "Crear un grup"], quickGroupHelp: ["Junta a los tuyos.", "Junta els teus."], quickGames: ["Jugar un rato", "Jugar una estona"], quickGamesHelp: ["Rompe el hielo.", "Trenca el gel."], quickPeople: ["Conocer gente", "Conéixer gent"], quickPeopleHelp: ["Da el primer hola.", "Dona el primer hola."],
 planOne: ["plan", "pla"], quietSpot: ["sin plan aún", "sense pla encara"], mapSection: ["Mapa", "Mapa"], mapPick: ["Toca un punto para ver sus planes.", "Toca un punt per a vore els seus plans."], allPlaces: ["Toda Valencia", "Tota València"], activityTitle: ["Qué se mueve", "Què es mou"], activityHere: ["Qué se mueve aquí", "Què es mou ací"], activityAll: ["En toda Valencia", "A tota València"], thisWeek: ["Esta semana", "Esta setmana"], noActivityHere: ["Aquí todavía no hay nada.", "Ací encara no hi ha res."], noActivityHereBody: ["Sé quien lo empieza y monta el primer plan en este sitio.", "Sigues qui ho comença i munta el primer pla en este lloc."], planHere: ["Montar algo aquí", "Muntar algo ací"], openMaps: ["Cómo llegar", "Com arribar"], spotsWithPlans: ["puntos con plan", "punts amb pla"], seeAll: ["Ver todo", "Vore-ho tot"],
 forumSection: ["Lo que se habla aquí", "El que es parla ací"], forumSectionSub: ["Abre un hilo, pregunta algo o entra en el grupo que te interesa.", "Obri un fil, pregunta alguna cosa o entra en el grup que t’interessa."], newPeople: ["Gente nueva por aquí", "Gent nova per ací"], sayHiShort: ["Saludar", "Saludar"],
 pulse: ["Lo que pasa por aquí", "El que passa per ací"], pulseNow: ["Hoy, por aquí", "Hui, per ací"], pulseThread: ["ha abierto un hilo", "ha obert un fil"], pulseReply: ["ha respondido en un hilo", "ha respost en un fil"], pulsePlan: ["ha montado un plan", "ha muntat un pla"], pulseNote: ["ha subido apuntes", "ha pujat apunts"], pulseJoin: ["ya está en Entreclase", "ja està en Entreclase"], pulseEmpty: ["Hoy está tranquilo. Empieza tú.", "Hui està tranquil. Comença tu."], seeMore: ["Ver más", "Vore més"], showLess: ["Ver menos", "Vore menys"], goForum: ["Ver el foro", "Vore el fòrum"],
 dislike: ["No me gusta", "No m’agrada"],
} as const;
export type CopyKey = keyof typeof messages;
export function communityCopy(locale: Locale) { return (key: CopyKey): string => messages[key][locale === "va" ? 1 : 0]; }
const localNames: Record<string, string> = { "Otra sede en Valencia": "Una altra seu a València", "La Malvarrosa": "La Malva-rosa", "Torres de Serranos": "Torres dels Serrans", "Café": "Café", "Música": "Música", "Deporte": "Esport", "Cine": "Cine", "Tecnología": "Tecnologia", "Arte": "Art", "Naturaleza": "Naturalesa", "Proyectos": "Projectes" };
export function localName(value: string, locale: Locale) { return locale === "va" ? localNames[value] ?? value : value; }
export function formatDate(value: string, locale: Locale) { return new Intl.DateTimeFormat(locale === "va" ? "ca-ES-valencia" : "es-ES", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Madrid" }).format(new Date(value)); }
export function relativeDate(value: string, locale: Locale) { const hours = Math.floor((Date.now() - new Date(value).getTime()) / 3_600_000); return new Intl.RelativeTimeFormat(locale === "va" ? "ca" : "es", { numeric: "auto" }).format(-Math.max(0, hours < 24 ? hours : Math.floor(hours / 24)), hours < 24 ? "hour" : "day"); }
export function communityError(error: unknown, locale: Locale) {
 const c = communityCopy(locale); const raw = error && typeof error === "object" ? error as { code?: string; message?: string } : {};
 const message=raw.message ?? "";
 if(message.includes("UNICOINS_INSUFFICIENT")) return unicoinCopy(locale)("insufficient");
 if(message.includes("UNICOINS_REQUEST_USED")) return unicoinCopy(locale)("requestConflict");
 if(message.includes("PLAN_FULL")) return c("fullError");
 if(message.includes("PLAN_PAST") || raw.code === "past_date") return c("pastError");
 if(raw.code === "note_cleanup") return c("noteCleanup");
 if(raw.code === "invalid_file") return c("fileError");
 if(raw.code === "validation") return c("validationError");
 if(message.includes("PEER_UNAVAILABLE")) return c("peerError");
 if(["PGRST202", "PGRST205", "42P01", "not_configured"].includes(raw.code ?? "")) return c("setupError");
 return c("genericError");
}
