import { emptyWallet, type CoinWallet } from "./unicoins";
export type View = "home" | "explore" | "projects" | "magazine" | "plans" | "groups" | "campus" | "people" | "messages" | "profile" | "unicoins" | "discover";
export const views: View[] = ["home", "explore", "projects", "magazine", "plans", "groups", "campus", "people", "messages", "profile", "unicoins", "discover"];
export const relationshipStatuses = ["single", "in_relationship", "seeing_someone", "complicated", "prefer_not_to_say"] as const;
export type RelationshipStatus = typeof relationshipStatuses[number];
export type Profile = { user_id: string; name: string; university: string; campus: string; degree: string; year: number; bio: string; interests: string[]; color: number; avatar_url?: string; relationship_status?: RelationshipStatus; created_at: string };
export type ProfileInput = Pick<Profile, "name" | "campus" | "degree" | "year" | "bio" | "interests" | "color"> & { relationship_status: RelationshipStatus };
export type Post = { id: string; author_id: string; body: string; kind: "post" | "question"; group_id: string | null; image_url?: string; created_at: string };
export type Comment = { id: string; post_id: string; author_id: string; body: string; created_at: string };
export type Like = { post_id: string; user_id: string };
export type Group = { id: string; creator_id: string; name: string; description: string; category: string; campus: string; created_at: string };
export type GroupMember = { group_id: string; user_id: string };
export type Plan = { id: string; creator_id: string; title: string; description: string; place: string; meeting_point: string; starts_at: string; capacity: number; created_at: string };
export type PlanMember = { plan_id: string; user_id: string };
export type Note = { id: string; author_id: string; title: string; subject: string; description: string; campus: string; file_name: string; file_path: string; file_size: number; created_at: string };
export type Thread = { id: string; user_a: string; user_b: string; created_at: string };
export type Message = { id: string; thread_id: string; sender_id: string; body: string; created_at: string };
export type CommunityData = { wallet: CoinWallet; profiles: Profile[]; posts: Post[]; comments: Comment[]; likes: Like[]; groups: Group[]; groupMembers: GroupMember[]; plans: Plan[]; planMembers: PlanMember[]; notes: Note[]; threads: Thread[] };
export const emptyCommunity = (): CommunityData => ({ wallet: emptyWallet(), profiles: [], posts: [], comments: [], likes: [], groups: [], groupMembers: [], plans: [], planMembers: [], notes: [], threads: [] });
export type PlanInput = Pick<Plan, "title" | "description" | "place" | "meeting_point" | "starts_at" | "capacity">;
export type GroupInput = Pick<Group, "name" | "description" | "category" | "campus">;
export type NoteInput = Pick<Note, "title" | "subject" | "description" | "campus">;
export interface CommunityRepository {
  read(): Promise<CommunityData>;
  saveProfile(input: ProfileInput): Promise<Profile>;
  publish(body: string, kind: Post["kind"], groupId: string | null, requestId?: string): Promise<void>;
  removePost(id: string): Promise<void>;
  like(postId: string, on: boolean): Promise<void>;
  comment(postId: string, body: string): Promise<void>;
  createPlan(input: PlanInput, requestId?: string): Promise<void>;
  joinPlan(id: string, join: boolean): Promise<void>;
  removePlan(id: string): Promise<void>;
  createGroup(input: GroupInput): Promise<void>;
  joinGroup(id: string, join: boolean): Promise<void>;
  uploadNote(input: NoteInput, file: File): Promise<void>;
  downloadNote(note: Note): Promise<string>;
  removeNote(note: Note): Promise<void>;
  openThread(peerId: string): Promise<string>;
  messages(threadId: string): Promise<Message[]>;
  sendMessage(threadId: string, body: string): Promise<void>;
  dispose(): void;
}
export const campuses = ["Tarongers", "Blasco Ibáñez", "Vera", "Burjassot-Paterna", "Otra sede en Valencia"] as const;
export const places = ["Benimaclet", "Torres de Serranos", "La Malvarrosa", "L’Albufera · Gola de Pujol", "Campus de Vera · Ágora"] as const;
export const interests = ["Café", "Música", "Deporte", "Cine", "Tecnología", "Arte", "Naturaleza", "Proyectos"] as const;
