import type { Locale } from "../i18n/routes";
import type { LegalKind } from "./config";

type Pair = readonly [string, string];
type Section = { id: string; title: Pair; paragraphs?: Pair[]; bullets?: Pair[] };
const content: Record<LegalKind, Section[]> = {
 legal: [
  { id: "servicio", title: ["1. El servicio", "1. El servici"], paragraphs: [
   ["Entreclases es una comunidad digital para conectar personas del entorno universitario, compartir publicaciones y apuntes, organizar planes, conversar y colaborar en proyectos. El sitio principal es https://www.entreclases.com.", "Entreclases és una comunitat digital per a connectar persones de l’entorn universitari, compartir publicacions i apunts, organitzar plans, conversar i col·laborar en projectes. El lloc principal és https://www.entreclases.com."],
   ["Es un proyecto independiente. La verificación de un correo institucional no implica que la universidad patrocine Entreclases, supervise su contenido o garantice la identidad completa, la matrícula actual o la conducta de quien participa.", "És un projecte independent. La verificació d’un correu institucional no implica que la universitat patrocine Entreclases, supervise el contingut o garantisca la identitat completa, la matrícula actual o la conducta de qui participa."],
  ]},
  { id: "titular", title: ["2. Titular y contacto", "2. Titular i contacte"], paragraphs: [
   ["La identificación del titular y responsable del tratamiento figura en el bloque de datos del titular de esta página. El contacto de atención, privacidad y comunicaciones sobre contenido es hola@entreclases.com. Atendemos en español y valenciano; indica el asunto para que podamos tramitarlo.", "La identificació del titular i responsable del tractament figura en el bloc de dades del titular d’esta pàgina. El contacte d’atenció, privacitat i comunicacions sobre contingut és hola@entreclases.com. Atenem en espanyol i valencià; indica l’assumpte perquè puguem tramitar-lo."],
   ["Las autoridades pueden utilizar ese mismo contacto identificando el organismo, el expediente, la base de la solicitud y un canal oficial de respuesta. Este canal no sustituye a los servicios de emergencia.", "Les autoritats poden utilitzar el mateix contacte identificant l’organisme, l’expedient, la base de la sol·licitud i un canal oficial de resposta. Este canal no substituïx els servicis d’emergència."],
  ]},
  { id: "propiedad", title: ["3. Propiedad intelectual y enlaces", "3. Propietat intel·lectual i enllaços"], paragraphs: [
   ["El diseño, los textos propios, la marca y el software están protegidos por los derechos de sus respectivos titulares y las licencias aplicables. Acceder al sitio no transfiere esos derechos. Las aportaciones de las personas usuarias se rigen por las condiciones de uso; compartir un archivo no lo convierte en material libre de derechos.", "El disseny, els textos propis, la marca i el programari estan protegits pels drets dels titulars respectius i les llicències aplicables. Accedir al lloc no transferix eixos drets. Les aportacions de les persones usuàries es regixen per les condicions d’ús; compartir un arxiu no el convertix en material lliure de drets."],
   ["Los enlaces a otros sitios y las fichas de catálogos identifican recursos de terceros. No implican respaldo ni control sobre sus condiciones. Las imágenes, portadas y datos conservan sus atribuciones y licencias. Puedes comunicar una infracción desde Denunciar contenido.", "Els enllaços a altres llocs i les fitxes de catàlegs identifiquen recursos de tercers. No impliquen suport ni control sobre les seues condicions. Les imatges, portades i dades conserven les atribucions i llicències. Pots comunicar una infracció des de Denunciar contingut."],
  ]},
  { id: "marco", title: ["4. Documentos y normativa", "4. Documents i normativa"], paragraphs: [
   ["Las condiciones regulan el uso de la cuenta; la política de privacidad explica los tratamientos; la política de cookies describe el almacenamiento en el dispositivo; las normas de comunidad y el canal de denuncias explican la convivencia y la revisión de contenido. Cada documento muestra su versión.", "Les condicions regulen l’ús del compte; la política de privacitat explica els tractaments; la política de cookies descriu l’emmagatzematge en el dispositiu; les normes de comunitat i el canal de denúncies expliquen la convivència i la revisió de contingut. Cada document mostra la versió."],
   ["Se aplica la normativa española y europea que corresponda, sin privarte de la protección imperativa de tu lugar de residencia ni de los tribunales que legalmente te correspondan como consumidor. No se exige renunciar a derechos ni acudir exclusivamente a los tribunales del domicilio del titular.", "S’aplica la normativa espanyola i europea que corresponga, sense privar-te de la protecció imperativa del lloc de residència ni dels tribunals que legalment et corresponguen com a consumidor. No s’exigix renunciar a drets ni acudir exclusivament als tribunals del domicili del titular."],
  ]},
 ],
 terms: [
  { id: "aceptacion", title: ["1. Aceptación y alcance", "1. Acceptació i abast"], paragraphs: [
   ["Estas condiciones regulan tu relación con el titular identificado en el aviso legal. Puedes leerlas sin registrarte y guardarlas o imprimirlas. Al solicitar una cuenta debes aceptarlas expresamente. La política de privacidad se facilita como información: aceptarla no constituye una autorización general para tratar tus datos ni recibir publicidad.", "Estes condicions regulen la relació amb el titular identificat en l’avís legal. Pots llegir-les sense registrar-te i guardar-les o imprimir-les. En sol·licitar un compte has d’acceptar-les expressament. La política de privacitat es facilita com a informació: acceptar-la no constituïx una autorització general per a tractar les dades ni rebre publicitat."],
   ["La comunidad, los mensajes y las funciones disponibles se ofrecen sin una cuota de acceso en esta versión. Si en el futuro se ofrecen servicios de pago, se informará previamente de su precio y condiciones y se solicitará la contratación correspondiente; el mero uso actual no autoriza cobros.", "La comunitat, els missatges i les funcions disponibles s’oferixen sense una quota d’accés en esta versió. Si en el futur s’oferixen servicis de pagament, s’informarà prèviament del preu i les condicions i se sol·licitarà la contractació corresponent; el simple ús actual no autoritza cobraments."],
  ]},
  { id: "acceso", title: ["2. Edad, cuenta y verificación", "2. Edat, compte i verificació"], bullets: [
   ["El acceso a la comunidad se reserva a personas de 18 años o más, también cuando entran por invitación. Es una regla de este servicio, no una afirmación de que todas las redes sociales deban exigir esa edad.", "L’accés a la comunitat es reserva a persones de 18 anys o més, també quan entren per invitació. És una regla d’este servici, no una afirmació que totes les xarxes socials hagen d’exigir eixa edat."],
   ["Utiliza un correo universitario admitido en una región abierta o una invitación válida para tu dirección. Debes confirmar el correo, proporcionar información veraz y mantener tus credenciales privadas. No compres, vendas ni compartas cuentas.", "Utilitza un correu universitari admés en una regió oberta o una invitació vàlida per a la teua adreça. Has de confirmar el correu, proporcionar informació veraç i mantindre les credencials privades. No compres, vengues ni compartisques comptes."],
   ["Puedes corregir los datos del formulario antes de enviarlo y editar tu perfil después. La verificación de correo no es una comprobación documental de edad o identidad. Comunica accesos no autorizados y no utilices identidades ajenas.", "Pots corregir les dades del formulari abans d’enviar-lo i editar el perfil després. La verificació del correu no és una comprovació documental d’edat o identitat. Comunica accessos no autoritzats i no utilitzes identitats alienes."],
  ]},
  { id: "invitaciones", title: ["3. Tu +1", "3. El teu +1"], paragraphs: [
   ["Cada cuenta universitaria verificada puede invitar a una persona después de completar el perfil y participar. La invitación queda vinculada al correo indicado, tiene la caducidad que se muestra al emitirla y no puede utilizarse dos veces. Las cuentas invitadas no generan nuevas invitaciones. Una invitación consumida no recupera su plaza al borrar la cuenta.", "Cada compte universitari verificat pot convidar una persona després de completar el perfil i participar. La invitació queda vinculada al correu indicat, té la caducitat que es mostra en emetre-la i no es pot utilitzar dos vegades. Els comptes convidats no generen noves invitacions. Una invitació consumida no recupera la plaça en esborrar el compte."],
   ["Invita únicamente a alguien que haya pedido o aceptado recibir la invitación. No introduzcas direcciones obtenidas de listas ni la uses para publicidad. Puedes compartir el enlace reservado con su destinatario; no publiques el token. La persona invitada acepta estas mismas reglas y responde por sus propias actuaciones.", "Convida únicament algú que haja demanat o acceptat rebre la invitació. No introduïsques adreces obtingudes de llistes ni la uses per a publicitat. Pots compartir l’enllaç reservat amb la persona destinatària; no publiques el token. La persona convidada accepta les mateixes regles i respon per les seues actuacions."],
  ]},
  { id: "contenido", title: ["4. Tus aportaciones y sus derechos", "4. Les teues aportacions i els seus drets"], paragraphs: [
   ["Conservas los derechos sobre tus publicaciones, apuntes y archivos. Nos autorizas, de forma no exclusiva y sin remuneración, a alojarlos, realizar las copias técnicas necesarias, adaptarlos al formato de pantalla y mostrarlos a la audiencia del espacio donde los compartes. Esta autorización se limita a prestar el servicio y no transfiere tu propiedad intelectual.", "Conserves els drets sobre les publicacions, els apunts i els arxius. Ens autoritzes, de manera no exclusiva i sense remuneració, a allotjar-los, fer les còpies tècniques necessàries, adaptar-los al format de pantalla i mostrar-los a l’audiència de l’espai on els compartixes. Esta autorització es limita a prestar el servici i no transferix la propietat intel·lectual."],
   ["La autorización termina al retirar el contenido, salvo las copias técnicas temporales y la conservación restringida legalmente necesaria. No permite usar tu imagen o tus aportaciones en campañas externas: una promoción que lo requiera tendrá una autorización específica. La retirada no elimina las copias que otras personas hayan obtenido legítimamente; sus usos siguen sujetos a la ley.", "L’autorització acaba en retirar el contingut, excepte les còpies tècniques temporals i la conservació restringida legalment necessària. No permet usar la teua imatge o les aportacions en campanyes externes: una promoció que ho requerisca tindrà una autorització específica. La retirada no elimina les còpies que altres persones hagen obtingut legítimament; els seus usos continuen subjectes a la llei."],
   ["Comparte solo material propio, autorizado o amparado por una excepción aplicable. No subas libros completos, exámenes restringidos, datos de alumnos o profesores, fotografías ajenas sin permiso ni conversaciones privadas. La finalidad educativa no autoriza cualquier reproducción.", "Compartix només material propi, autoritzat o emparat per una excepció aplicable. No puges llibres complets, exàmens restringits, dades d’alumnes o professors, fotografies alienes sense permís ni converses privades. La finalitat educativa no autoritza qualsevol reproducció."],
  ]},
  { id: "planes", title: ["5. Planes, encuentros y proyectos", "5. Plans, trobades i projectes"], paragraphs: [
   ["Quien organiza un plan debe describir de forma veraz fecha, lugar, plazas, requisitos y cualquier coste externo, y avisar de cambios o cancelaciones. Una inscripción no acredita asistencia. Cuando Entreclases no figure expresamente como organizador, facilita el contacto y no contrata el transporte, el local ni otros servicios del encuentro.", "Qui organitza un pla ha de descriure de manera veraç data, lloc, places, requisits i qualsevol cost extern, i avisar de canvis o cancel·lacions. Una inscripció no acredita assistència. Quan Entreclases no figure expressament com a organitzador, facilita el contacte i no contracta el transport, el local ni altres servicis de la trobada."],
   ["En un proyecto, acordad por escrito las tareas, gastos, plazos, derechos sobre código y diseños, uso de marcas, créditos y condiciones de salida. Fichar a alguien no crea por sí solo una relación laboral, sociedad, inversión ni cesión de derechos. Entreclases no garantiza financiación, contratación, promoción ni resultados.", "En un projecte, acordeu per escrit les tasques, despeses, terminis, drets sobre codi i dissenys, ús de marques, crèdits i condicions d’eixida. Fitxar algú no crea per si mateix una relació laboral, societat, inversió ni cessió de drets. Entreclases no garantix finançament, contractació, promoció ni resultats."],
   ["Respeta las decisiones de otras personas, su privacidad y las normas del lugar. Puedes abandonar un encuentro. Ante un peligro inmediato, contacta con los servicios de emergencia; el canal de soporte no presta vigilancia en tiempo real.", "Respecta les decisions d’altres persones, la seua privacitat i les normes del lloc. Pots abandonar una trobada. Davant d’un perill immediat, contacta amb els servicis d’emergència; el canal de suport no presta vigilància en temps real."],
  ]},
  { id: "monedas", title: ["6. ClasiCoins", "6. ClasiCoins"], paragraphs: [
   ["Son puntos internos de participación, sin valor monetario, compra, venta, transferencia entre cuentas ni conversión a dinero. Completar el primer perfil verificado concede 20. Crear un plan cuesta 10. El primer hilo es gratuito para una cuenta que no haya utilizado esa oportunidad ni tenga hilos cobrados anteriormente; los siguientes cuestan 5.", "Són punts interns de participació, sense valor monetari, compra, venda, transferència entre comptes ni conversió a diners. Completar el primer perfil verificat en concedix 20. Crear un pla en costa 10. El primer fil és gratuït per a un compte que no haja utilitzat eixa oportunitat ni tinga fils cobrats anteriorment; els següents en costen 5."],
   ["La primera respuesta en un hilo ajeno puede dar 2 puntos, con un máximo de 3 hilos recompensados al día según Europe/Madrid. Apuntarse a un plan no da puntos. Repetir acciones, responderse a uno mismo o borrar contenido no reinicia las oportunidades ni devuelve los puntos gastados. Las reglas y el saldo se muestran en el monedero; comunica cualquier discrepancia.", "La primera resposta en un fil alié pot donar 2 punts, amb un màxim de 3 fils recompensats al dia segons Europe/Madrid. Apuntar-se a un pla no dona punts. Repetir accions, respondre’s a un mateix o esborrar contingut no reinicia les oportunitats ni retorna els punts gastats. Les regles i el saldo es mostren en el moneder; comunica qualsevol discrepància."],
   ["No uses cuentas múltiples, automatizaciones o acuerdos de respuestas artificiales para obtener puntos. Los errores o abusos pueden corregirse con explicación y posibilidad de revisión. Los cambios de reglas se comunicarán antes de aplicarse; no se cobrarán retroactivamente acciones que eran gratuitas.", "No uses comptes múltiples, automatitzacions o acords de respostes artificials per a obtindre punts. Els errors o abusos es poden corregir amb explicació i possibilitat de revisió. Els canvis de regles es comunicaran abans d’aplicar-se; no es cobraran retroactivament accions que eren gratuïtes."],
  ]},
  { id: "moderacion", title: ["7. Moderación y reclamaciones", "7. Moderació i reclamacions"], paragraphs: [
   ["Se aplican las normas de comunidad. Una infracción puede dar lugar a un aviso, retirada de contenido, limitación de una función o suspensión temporal o definitiva de la cuenta, según gravedad, contexto y reiteración. No se toman medidas por el mero desacuerdo con una opinión lícita.", "S’apliquen les normes de comunitat. Una infracció pot donar lloc a un avís, retirada de contingut, limitació d’una funció o suspensió temporal o definitiva del compte, segons gravetat, context i reiteració. No es prenen mesures pel simple desacord amb una opinió lícita."],
   ["Se comunicará el motivo, el alcance y la duración de una restricción, así como la vía de revisión, salvo las limitaciones legales aplicables. Puedes impugnarla gratuitamente por el canal de denuncias durante al menos seis meses desde la notificación. La revisión debe considerar tus alegaciones y no basarse únicamente en una respuesta automática.", "Es comunicarà el motiu, l’abast i la duració d’una restricció, així com la via de revisió, excepte les limitacions legals aplicables. Pots impugnar-la gratuïtament pel canal de denúncies durant almenys sis mesos des de la notificació. La revisió ha de considerar les teues al·legacions i no basar-se únicament en una resposta automàtica."],
  ]},
  { id: "baja", title: ["8. Baja, cambios y responsabilidad", "8. Baixa, canvis i responsabilitat"], paragraphs: [
   ["Puedes solicitar la baja y la supresión de datos desde Tus datos y tu cuenta. Cerrar sesión o dejar de usar la aplicación no elimina la cuenta. Se revisarán los datos propios y las aportaciones compartidas para respetar también los derechos de otras personas y las obligaciones de conservación.", "Pots sol·licitar la baixa i la supressió de dades des de Les teues dades i el teu compte. Tancar sessió o deixar d’usar l’aplicació no elimina el compte. Es revisaran les dades pròpies i les aportacions compartides per a respectar també els drets d’altres persones i les obligacions de conservació."],
   ["Puede haber mantenimiento, errores o interrupciones. Adoptaremos medidas razonables para resolverlos y avisaremos de cambios relevantes. Estas condiciones no excluyen responsabilidades que la ley imponga, ni limitan tus derechos por dolo, negligencia u otros incumplimientos imputables al titular.", "Pot haver-hi manteniment, errors o interrupcions. Adoptarem mesures raonables per a resoldre’ls i avisarem de canvis rellevants. Estes condicions no exclouen responsabilitats que la llei impose, ni limiten els teus drets per dol, negligència o altres incompliments imputables al titular."],
   ["Las modificaciones sustanciales se comunicarán con antelación razonable, explicando su entrada en vigor y cómo darte de baja si no las aceptas. Si requieren una nueva aceptación, se solicitará. La legislación aplicable y los derechos de reclamación se describen en el aviso legal.", "Les modificacions substancials es comunicaran amb antelació raonable, explicant l’entrada en vigor i com donar-te de baixa si no les acceptes. Si requerixen una nova acceptació, se sol·licitarà. La legislació aplicable i els drets de reclamació es descriuen en l’avís legal."],
  ]},
 ],
 privacy: [
  { id: "responsable", title: ["1. Responsable y alcance", "1. Responsable i abast"], paragraphs: [
   ["El responsable es el titular identificado en esta página y en el aviso legal. Puedes contactar en hola@entreclases.com. Esta política comprende la web y su comunidad; los servicios externos enlazados tienen sus propias políticas. La cuenta universitaria no entrega tus datos a tu universidad por el mero hecho de verificar el dominio.", "El responsable és el titular identificat en esta pàgina i en l’avís legal. Pots contactar en hola@entreclases.com. Esta política comprén la web i la comunitat; els servicis externs enllaçats tenen les seues polítiques. El compte universitari no entrega les dades a la universitat pel simple fet de verificar el domini."],
  ]},
  { id: "datos", title: ["2. Datos y procedencia", "2. Dades i procedència"], bullets: [
   ["Cuenta: nombre, correo, credencial gestionada por el proveedor de autenticación, confirmación del correo e identificador de cuenta. No debes enviarnos contraseñas por soporte.", "Compte: nom, correu, credencial gestionada pel proveïdor d’autenticació, confirmació del correu i identificador del compte. No has d’enviar-nos contrasenyes per suport."],
   ["Perfil: campus, estudios, curso y los campos que completas, como biografía, intereses, gustos, imagen, cabecera y situación sentimental. Los campos señalados como obligatorios permiten crear y presentar el perfil; los demás pueden quedar vacíos o en «prefiero no decirlo».", "Perfil: campus, estudis, curs i els camps que completes, com biografia, interessos, gustos, imatge, capçalera i situació sentimental. Els camps assenyalats com a obligatoris permeten crear i presentar el perfil; els altres poden quedar buits o en «preferisc no dir-ho»."],
   ["Actividad: publicaciones, respuestas, reacciones, grupos, apuntes, archivos, inscripciones, proyectos, solicitudes a equipos, mensajes, juegos, aportaciones a la revista, puntos e historial necesario para impedir duplicidades.", "Activitat: publicacions, respostes, reaccions, grups, apunts, arxius, inscripcions, projectes, sol·licituds a equips, missatges, jocs, aportacions a la revista, punts i historial necessari per a impedir duplicitats."],
   ["Invitaciones: quien invita facilita el correo de su destinatario. Conservamos la relación con la cuenta que invita, el token y su estado. Si no tienes cuenta, puedes solicitar información o eliminación de la invitación. Esta información se facilita en el enlace de invitación antes del registro; el remitente debe compartirla contigo.", "Invitacions: qui convida facilita el correu de la persona destinatària. Conservem la relació amb el compte que convida, el token i l’estat. Si no tens compte, pots sol·licitar informació o eliminació de la invitació. Esta informació es facilita en l’enllaç d’invitació abans del registre; la persona remitent ha de compartir-la amb tu."],
   ["Datos técnicos y soporte: solicitudes al alojamiento, dirección IP y registros de seguridad que generen los proveedores, así como los datos que incluyas en consultas o denuncias. Los buscadores de gustos reciben los términos que introduces; evita incluir datos personales en esas búsquedas.", "Dades tècniques i suport: peticions a l’allotjament, adreça IP i registres de seguretat que generen els proveïdors, així com les dades que inclogues en consultes o denúncies. Els buscadors de gustos reben els termes que introduïxes; evita incloure dades personals en eixes cerques."],
   ["Uso operativo: mientras tienes una sesión autenticada, guardamos un identificador técnico de sesión, las rutas de la aplicación, los cambios de pantalla y el tiempo con la pestaña visible. Lo usamos para saber cuántas personas entran, qué experiencias funcionan y mejorar el servicio; no guardamos el contenido de mensajes ni enviamos estos datos a redes publicitarias. El acceso a los agregados queda limitado al equipo autorizado.", "Ús operatiu: mentre tens una sessió autenticada, guardem un identificador tècnic de sessió, les rutes de l’aplicació, els canvis de pantalla i el temps amb la pestanya visible. Ho usem per a saber quantes persones entren, quines experiències funcionen i millorar el servici; no guardem el contingut dels missatges ni enviem aquestes dades a xarxes publicitàries. L’accés als agregats queda limitat a l’equip autoritzat."],
  ]},
  { id: "finalidades", title: ["3. Finalidades y bases jurídicas", "3. Finalitats i bases jurídiques"], bullets: [
   ["Crear y mantener la cuenta, verificar el acceso, prestar las funciones que solicitas y gestionar ClasiCoins: ejecución de la relación de servicio y medidas previas que solicitas (art. 6.1.b RGPD). Sin los datos necesarios no podemos prestar esas funciones.", "Crear i mantindre el compte, verificar l’accés, prestar les funcions que sol·licites i gestionar ClasiCoins: execució de la relació de servici i mesures prèvies que sol·licites (art. 6.1.b RGPD). Sense les dades necessàries no podem prestar eixes funcions."],
   ["Mostrar los campos opcionales que eliges añadir: tu decisión de publicarlos y el consentimiento que corresponda (art. 6.1.a). Puedes retirarlos editando el perfil sin perder la cuenta. No uses esos campos para divulgar datos sensibles de otras personas; que un espacio sea una comunidad no lo convierte en un espacio público ilimitado.", "Mostrar els camps opcionals que tries afegir: la teua decisió de publicar-los i el consentiment que corresponga (art. 6.1.a). Pots retirar-los editant el perfil sense perdre el compte. No uses eixos camps per a divulgar dades sensibles d’altres persones; que un espai siga una comunitat no el convertix en un espai públic il·limitat."],
   ["Proteger cuentas, prevenir spam, fraude e inscripciones repetidas y tramitar incidencias: interés legítimo en mantener un servicio seguro (art. 6.1.f), ponderado con tus derechos. Puedes oponerte por motivos de tu situación particular. Las obligaciones de atender derechos, requerimientos válidos y contenido ilícito se apoyan en la normativa aplicable (art. 6.1.c).",
    "Protegir comptes, previndre spam, frau i inscripcions repetides i tramitar incidències: interés legítim a mantindre un servici segur (art. 6.1.f), ponderat amb els teus drets. Pots oposar-t’hi per motius de la teua situació particular. Les obligacions d’atendre drets, requeriments vàlids i contingut il·lícit es basen en la normativa aplicable (art. 6.1.c)."],
   ["Reservar una invitación solicitada por un miembro para una persona que espera recibirla: interés legítimo en facilitar ese contacto limitado; no se incorpora ese correo a listas comerciales. La invitación no permite enviar campañas a quien no se registra.", "Reservar una invitació sol·licitada per un membre per a una persona que espera rebre-la: interés legítim a facilitar eixe contacte limitat; no s’incorpora el correu a llistes comercials. La invitació no permet enviar campanyes a qui no es registra."],
   ["No se solicita consentimiento para publicidad al aceptar las condiciones. Una futura comunicación comercial que requiera consentimiento tendrá una opción separada, libre y revocable. Los avisos necesarios de cuenta y seguridad son comunicaciones de servicio.", "No se sol·licita consentiment per a publicitat en acceptar les condicions. Una futura comunicació comercial que requerisca consentiment tindrà una opció separada, lliure i revocable. Els avisos necessaris de compte i seguretat són comunicacions de servici."],
  ]},
  { id: "visibilidad", title: ["4. Quién puede ver tus datos", "4. Qui pot vore les teues dades"], paragraphs: [
   ["El perfil y las aportaciones se muestran a las personas con acceso a cada espacio. Los mensajes y archivos de equipos o grupos restringidos se limitan según sus permisos; esto no significa cifrado de extremo a extremo. Personal autorizado puede acceder cuando sea necesario para soporte, seguridad o cumplir obligaciones, con acceso limitado a la tarea.", "El perfil i les aportacions es mostren a les persones amb accés a cada espai. Els missatges i arxius d’equips o grups restringits es limiten segons els permisos; açò no significa xifrat d’extrem a extrem. Personal autoritzat pot accedir quan siga necessari per a suport, seguretat o complir obligacions, amb accés limitat a la tasca."],
   ["Antes de enviar una propuesta a la revista o permitir promoción externa, revisa el alcance de su autorización específica. No autorizas campañas con tu imagen por aceptar esta política. Otras personas pueden copiar o descargar contenido al que tengan acceso; no publiques información que no quieras compartir con esa audiencia.", "Abans d’enviar una proposta a la revista o permetre promoció externa, revisa l’abast de l’autorització específica. No autoritzes campanyes amb la teua imatge per acceptar esta política. Altres persones poden copiar o descarregar contingut al qual tinguen accés; no publiques informació que no vulgues compartir amb eixa audiència."],
  ]},
  { id: "proveedores", title: ["5. Proveedores y transferencias", "5. Proveïdors i transferències"], paragraphs: [
   ["La web se aloja en Vercel y utiliza Supabase para autenticación, base de datos, almacenamiento y funciones de comunidad. El proyecto está preparado para correo con Resend; debe confirmarse el proveedor efectivo del entorno. Los proveedores que actúen por cuenta del titular deben estar sujetos al contrato y las garantías correspondientes.", "La web s’allotja en Vercel i utilitza Supabase per a autenticació, base de dades, emmagatzematge i funcions de comunitat. El projecte està preparat per a correu amb Resend; s’ha de confirmar el proveïdor efectiu de l’entorn. Els proveïdors que actuen per compte del titular han d’estar subjectes al contracte i les garanties corresponents."],
   ["Los mapas solicitan teselas a tile.openstreetmap.de. Las búsquedas y portadas de gustos pueden contactar con TVMaze, TMDB, OMDb, Wikimedia/Wikidata, IGDB, RAWG, Spotify, MusicBrainz y Cover Art Archive, según la configuración y el contenido mostrado. Sus servidores reciben al menos la solicitud y la IP, y las búsquedas cuando se realizan. No se les entrega tu contraseña; sus políticas regulan los tratamientos propios que realicen.", "Els mapes sol·liciten tessel·les a tile.openstreetmap.de. Les cerques i portades de gustos poden contactar amb TVMaze, TMDB, OMDb, Wikimedia/Wikidata, IGDB, RAWG, Spotify, MusicBrainz i Cover Art Archive, segons la configuració i el contingut mostrat. Els servidors reben almenys la petició i la IP, i les cerques quan es fan. No se’ls entrega la contrasenya; les seues polítiques regulen els tractaments propis que realitzen."],
   ["«Estudiar con estos apuntes» envía a OpenAI el texto extraído del PDF, su título y su asignatura para preparar el resumen, las tarjetas y el test, y la pregunta que escribes en «Pregunta» junto a ese texto. No se envía tu nombre ni tu correo. Las preguntas no se guardan en Entreclases; el resultado del apunte y su texto se conservan mientras el apunte siga publicado y se borran con él. Se solicita a OpenAI que no almacene las respuestas y, cuando esté configurado, el tratamiento en la región de la UE. El material generado puede contener errores y no sustituye a los apuntes.", "«Estudiar amb estos apunts» envia a OpenAI el text extret del PDF, el títol i l’assignatura per a preparar el resum, les targetes i el test, i la pregunta que escrius en «Pregunta» junt amb eixe text. No s’envia el teu nom ni el teu correu. Les preguntes no es guarden a Entreclases; el resultat de l’apunt i el seu text es conserven mentre l’apunt continue publicat i s’esborren amb ell. Se sol·licita a OpenAI que no emmagatzeme les respostes i, quan estiga configurat, el tractament a la regió de la UE. El material generat pot contindre errors i no substituïx els apunts."],
   ["Puede haber acceso o tratamiento fuera del Espacio Económico Europeo. La región efectiva, las entidades contratadas y el mecanismo aplicable a cada transferencia deben constar en la ficha de proveedores antes de publicar la versión definitiva. No afirmamos que todos los datos permanezcan en España o en la UE ni que todos los proveedores estén cubiertos por una misma garantía.", "Pot haver-hi accés o tractament fora de l’Espai Econòmic Europeu. La regió efectiva, les entitats contractades i el mecanisme aplicable a cada transferència han de constar en la fitxa de proveïdors abans de publicar la versió definitiva. No afirmem que totes les dades romanguen a Espanya o a la UE ni que tots els proveïdors estiguen coberts per una mateixa garantia."],
  ]},
  { id: "conservacion", title: ["6. Conservación y eliminación", "6. Conservació i eliminació"], paragraphs: [
   ["Los datos de cuenta y actividad se mantienen mientras prestemos el servicio y sean necesarios para las funciones elegidas. Puedes retirar campos opcionales y contenido propio cuando exista esa función, o solicitarlo por correo. La baja requiere revisar también archivos, mensajes y aportaciones compartidas; no se anuncia un borrado automático al cerrar sesión.", "Les dades de compte i activitat es mantenen mentre prestem el servici i siguen necessàries per a les funcions triades. Pots retirar camps opcionals i contingut propi quan existisca eixa funció, o sol·licitar-ho per correu. La baixa requerix revisar també arxius, missatges i aportacions compartides; no s’anuncia un esborrat automàtic en tancar sessió."],
   ["La invitación caduca a los siete días si no se usa, pero caducar no equivale a borrar su registro. Los identificadores de invitaciones consumidas y los historiales de puntos evitan reutilizaciones. En una solicitud de supresión se revisará la necesidad de cada dato, eliminando o anonimizando lo que no deba conservarse; no se justifica guardar indefinidamente el correo por este motivo.", "La invitació caduca als set dies si no s’usa, però caducar no equival a esborrar el registre. Els identificadors d’invitacions consumides i els historials de punts eviten reutilitzacions. En una sol·licitud de supressió es revisarà la necessitat de cada dada, eliminant o anonimitzant allò que no s’haja de conservar; no es justifica guardar indefinidament el correu per este motiu."],
   ["Tras la baja, solo se conservará de forma restringida lo necesario para obligaciones o reclamaciones durante el plazo aplicable a cada finalidad. Los registros técnicos y copias de seguridad dependen del entorno: sus plazos concretos y la ejecución del borrado deben confirmarse en la ficha de conservación. No prometemos un plazo de purga de copias que todavía no se ha verificado.", "Després de la baixa, només es conservarà de manera restringida allò necessari per a obligacions o reclamacions durant el termini aplicable a cada finalitat. Els registres tècnics i còpies de seguretat depenen de l’entorn: els terminis concrets i l’execució de l’esborrat s’han de confirmar en la fitxa de conservació. No prometem un termini de purga de còpies que encara no s’ha verificat."],
  ]},
  { id: "derechos", title: ["7. Tus derechos", "7. Els teus drets"], paragraphs: [
   ["Puedes solicitar acceso, rectificación, supresión, limitación, oposición y portabilidad cuando proceda, y retirar consentimientos sin afectar al tratamiento previo lícito. Consulta Tus datos y tu cuenta para preparar la solicitud. Respondemos en el plazo legal, normalmente un mes desde su recepción; si procede ampliarlo por complejidad o número de solicitudes, se te informará dentro de ese primer mes con los motivos.", "Pots sol·licitar accés, rectificació, supressió, limitació, oposició i portabilitat quan pertoque, i retirar consentiments sense afectar el tractament previ lícit. Consulta Les teues dades i el teu compte per a preparar la sol·licitud. Responem en el termini legal, normalment un mes des de la recepció; si correspon ampliar-lo per complexitat o nombre de sol·licituds, se t’informarà dins d’eixe primer mes amb els motius."],
   ["Puedes reclamar ante la Agencia Española de Protección de Datos (www.aepd.es) o la autoridad competente. No necesitas una cuenta para solicitar información sobre una invitación o denunciar un tratamiento que te afecte.", "Pots reclamar davant de l’Agència Espanyola de Protecció de Dades (www.aepd.es) o l’autoritat competent. No necessites un compte per a sol·licitar informació sobre una invitació o denunciar un tractament que t’afecte."],
  ]},
  { id: "automatizacion", title: ["8. Recomendaciones y datos delicados", "8. Recomanacions i dades delicades"], paragraphs: [
   ["Las coincidencias y filtros utilizan los datos que compartes, como campus, intereses y gustos. Los juegos y sus resultados son lúdicos, no evaluaciones psicológicas ni garantías de compatibilidad. El acceso y los puntos tienen reglas automáticas; puedes pedir revisión de un error por soporte. No se ha identificado en el código revisado un sistema de decisiones con efectos jurídicos basado en perfiles de IA.", "Les coincidències i filtres utilitzen les dades que compartixes, com campus, interessos i gustos. Els jocs i els resultats són lúdics, no avaluacions psicològiques ni garanties de compatibilitat. L’accés i els punts tenen regles automàtiques; pots demanar revisió d’un error per suport. No s’ha identificat en el codi revisat un sistema de decisions amb efectes jurídics basat en perfils d’IA."],
   ["No solicitamos documentos médicos, ideología, religión ni orientación sexual para darte acceso. Evita incluir esos datos en biografías, archivos o respuestas. Algunos contenidos pueden revelarlos indirectamente: su tratamiento exige una revisión específica y, cuando corresponda, consentimiento explícito; aceptar estas condiciones no lo sustituye.", "No sol·licitem documents mèdics, ideologia, religió ni orientació sexual per a donar-te accés. Evita incloure eixes dades en biografies, arxius o respostes. Alguns continguts poden revelar-les indirectament: el tractament exigix una revisió específica i, quan corresponga, consentiment explícit; acceptar estes condicions no el substituïx."],
   ["El acceso propuesto para esta versión es de mayores de 18 años. Si detectas un registro de un menor, comunícalo para revisar la cuenta con medidas proporcionadas y sin publicar sus datos.", "L’accés proposat per a esta versió és de majors de 18 anys. Si detectes un registre d’un menor, comunica-ho per a revisar el compte amb mesures proporcionades i sense publicar les seues dades."],
  ]},
 ],
 cookies: [
  { id: "alcance", title: ["1. Qué se almacena en tu dispositivo", "1. Què s’emmagatzema en el dispositiu"], paragraphs: [
   ["Además de cookies, un sitio puede utilizar localStorage y sessionStorage. El primero persiste entre visitas hasta su eliminación; el segundo se limita normalmente a la pestaña o sesión del navegador. Esta política describe los usos encontrados en el código de Entreclases; la auditoría del despliegue debe comprobar también lo que incorporen el alojamiento y los proveedores externos.", "A més de cookies, un lloc pot utilitzar localStorage i sessionStorage. El primer persistix entre visites fins a l’eliminació; el segon es limita normalment a la pestanya o sessió del navegador. Esta política descriu els usos trobats en el codi d’Entreclases; l’auditoria del desplegament ha de comprovar també el que incorporen l’allotjament i els proveïdors externs."],
   ["No se han encontrado etiquetas de analítica publicitaria ni un píxel de anuncios. La aplicación sí usa una medición propia de uso dentro de la sesión autenticada, descrita en la política de privacidad, sin publicidad comportamental.", "No s’han trobat etiquetes d’analítica publicitària ni un píxel d’anuncis. L’aplicació sí que usa una mesura pròpia d’ús dins de la sessió autenticada, descrita en la política de privacitat, sense publicitat comportamental."],
  ]},
  { id: "inventario", title: ["2. Inventario de la aplicación", "2. Inventari de l’aplicació"], bullets: [
   ["sb-<proyecto>-auth-token y claves auxiliares de Supabase: sesión y flujo seguro de verificación (PKCE), en almacenamiento del navegador. Necesarios para autenticarte; la sesión persiste hasta cerrarla, revocarla o eliminar el almacenamiento, según la configuración de Auth. No equivalen a una cookie publicitaria.", "sb-<projecte>-auth-token i claus auxiliars de Supabase: sessió i flux segur de verificació (PKCE), en emmagatzematge del navegador. Necessaris per a autenticar-te; la sessió persistix fins a tancar-la, revocar-la o eliminar l’emmagatzematge, segons la configuració d’Auth. No equivalen a una cookie publicitària."],
   ["entreclase.signup.email (sessionStorage): pasa el correo que has escrito desde la portada al formulario. Se elimina al leerlo en el registro o al terminar la sesión de la pestaña.", "entreclase.signup.email (sessionStorage): passa el correu que has escrit des de la portada al formulari. S’elimina en llegir-lo en el registre o en acabar la sessió de la pestanya."],
   ["entreclase.warmup (sessionStorage): recuerda la elección del juego solicitado durante esa sesión. La aplicación deja de usarla al cambiar el día en Europe/Madrid; el dato puede seguir almacenado hasta sobrescribirse o cerrar la sesión de la pestaña.", "entreclase.warmup (sessionStorage): recorda l’elecció del joc sol·licitat durant eixa sessió. L’aplicació deixa d’usar-la en canviar el dia en Europe/Madrid; la dada pot continuar emmagatzemada fins a sobreescriure’s o tancar la sessió de la pestanya."],
   ["entreclase.plus-one.demo.<usuario> (sessionStorage): conserva una invitación de demostración entre pantallas hasta terminar la sesión de la pestaña. No es una invitación real.", "entreclase.plus-one.demo.<usuari> (sessionStorage): conserva una invitació de demostració entre pantalles fins a acabar la sessió de la pestanya. No és una invitació real."],
   ["entreclase.emoji (localStorage): recuerda hasta 16 emojis recientes elegidos en el chat. No tiene un vencimiento programado; se sobrescribe con el uso o se elimina al borrar los datos del sitio.", "entreclase.emoji (localStorage): recorda fins a 16 emojis recents triats en el xat. No té un venciment programat; se sobreescriu amb l’ús o s’elimina en esborrar les dades del lloc."],
   ["entreclase:backoffice:session:v1 (localStorage): conserva el estado del panel de demostración, no una autorización administrativa de producción. Persiste hasta reiniciarlo o borrar los datos del sitio.", "entreclase:backoffice:session:v1 (localStorage): conserva l’estat del panell de demostració, no una autorització administrativa de producció. Persistix fins a reiniciar-lo o esborrar les dades del lloc."],
  ]},
  { id: "terceros", title: ["3. Mapas, catálogos y consentimiento", "3. Mapes, catàlegs i consentiment"], paragraphs: [
   ["Al visualizar mapas o portadas se realizan conexiones a terceros; algunas portadas se cargan al mostrar un perfil, sin iniciar una búsqueda. Una conexión externa no es por sí sola una cookie, pero comunica datos técnicos. Los proveedores posibles se enumeran en Privacidad. No puede afirmarse que todos esos recursos estén bloqueados por consentimiento en la versión actual.", "En visualitzar mapes o portades es fan connexions a tercers; algunes portades es carreguen en mostrar un perfil, sense iniciar una cerca. Una connexió externa no és per si mateixa una cookie, però comunica dades tècniques. Els proveïdors possibles s’enumeren en Privacitat. No es pot afirmar que tots eixos recursos estiguen bloquejats per consentiment en la versió actual."],
   ["Los usos estrictamente necesarios para una función solicitada no se presentan como publicidad opcional. Si se incorporan analítica, anuncios o almacenamiento no exceptuado, deberán permanecer desactivados hasta obtener el consentimiento correspondiente, con aceptar y rechazar igualmente accesibles y una forma permanente de cambiar la elección. Esta política por sí sola no activa ese mecanismo.", "Els usos estrictament necessaris per a una funció sol·licitada no es presenten com a publicitat opcional. Si s’incorporen analítica, anuncis o emmagatzematge no exceptuat, hauran de romandre desactivats fins a obtindre el consentiment corresponent, amb acceptar i rebutjar igualment accessibles i una forma permanent de canviar l’elecció. Esta política per si mateixa no activa eixe mecanisme."],
  ]},
  { id: "control", title: ["4. Cómo borrar o limitar el almacenamiento", "4. Com esborrar o limitar l’emmagatzematge"], paragraphs: [
   ["En los ajustes de privacidad de tu navegador puedes consultar y borrar los datos de www.entreclases.com, bloquear cookies de terceros o usar una sesión privada. Para revocar la sesión utiliza también Cerrar sesión. Borrar datos del navegador puede cerrar tu sesión y perder preferencias o borradores; no elimina tu cuenta ni los datos guardados en el servidor.", "En els ajustos de privacitat del navegador pots consultar i esborrar les dades de www.entreclases.com, bloquejar cookies de tercers o usar una sessió privada. Per a revocar la sessió utilitza també Tancar sessió. Esborrar dades del navegador pot tancar la sessió i perdre preferències o esborranys; no elimina el compte ni les dades guardades en el servidor."],
   ["Las funciones esenciales pueden no funcionar si bloqueas todo el almacenamiento. Para solicitar la supresión de datos del servidor, consulta Tus datos y tu cuenta. Si detectas una tecnología no descrita, comunícalo a hola@entreclases.com.", "Les funcions essencials poden no funcionar si bloqueges tot l’emmagatzematge. Per a sol·licitar la supressió de dades del servidor, consulta Les teues dades i el teu compte. Si detectes una tecnologia no descrita, comunica-ho a hola@entreclases.com."],
  ]},
 ],
 community: [
  { id: "respeto", title: ["1. Trato y seguridad", "1. Tracte i seguretat"], bullets: [
   ["Puedes debatir y discrepar. No se permite el acoso, las amenazas, el hostigamiento reiterado, la discriminación ni promover violencia. Respeta un «no» y no insistas mediante otras cuentas o canales.", "Pots debatre i discrepar. No es permet l’assetjament, les amenaces, l’hostilitat reiterada, la discriminació ni promoure violència. Respecta un «no» i no insistisques mitjançant altres comptes o canals."],
   ["No publiques domicilios, teléfonos, documentos, notas académicas, ubicaciones privadas o imágenes íntimas de otras personas sin una base legítima. No difundas conversaciones privadas ni contenido sexual sin consentimiento. El material de abuso sexual infantil está prohibido y debe denunciarse sin descargarlo ni redistribuirlo.", "No publiques domicilis, telèfons, documents, notes acadèmiques, ubicacions privades o imatges íntimes d’altres persones sense una base legítima. No difongues converses privades ni contingut sexual sense consentiment. El material d’abús sexual infantil està prohibit i s’ha de denunciar sense descarregar-lo ni redistribuir-lo."],
   ["No suplantes a personas, universidades o entidades. No organices fraudes, captación engañosa, venta de datos, malware, acceso no autorizado ni actividades ilícitas. No uses la plataforma para enviar spam o reclutar mediante promesas falsas.", "No suplantes persones, universitats o entitats. No organitzes fraus, captació enganyosa, venda de dades, programari maliciós, accés no autoritzat ni activitats il·lícites. No uses la plataforma per a enviar spam o reclutar mitjançant promeses falses."],
  ]},
  { id: "aportaciones", title: ["2. Apuntes, proyectos y publicidad", "2. Apunts, projectes i publicitat"], bullets: [
   ["Respeta las licencias y cita las fuentes. No compartas material reservado, trabajos robados ni datos personales de terceros. Ayudar a estudiar no equivale a suplantar al alumno en una evaluación.", "Respecta les llicències i cita les fonts. No compartisques material reservat, treballs robats ni dades personals de tercers. Ajudar a estudiar no equival a suplantar l’alumne en una avaluació."],
   ["Explica qué necesita tu proyecto, qué espera de cada persona y si existe remuneración o gastos. No presentes trabajo gratuito como empleo remunerado ni uses candidaturas para extraer datos o ideas sin permiso.", "Explica què necessita el projecte, què espera de cada persona i si existix remuneració o despeses. No presentes treball gratuït com a ocupació remunerada ni uses candidatures per a extraure dades o idees sense permís."],
   ["Identifica los intereses comerciales, patrocinios y enlaces promocionales. No publiques campañas masivas ni manipules respuestas, inscripciones o ClasiCoins. Una colaboración externa requiere las autorizaciones que correspondan.", "Identifica els interessos comercials, patrocinis i enllaços promocionals. No publiques campanyes massives ni manipules respostes, inscripcions o ClasiCoins. Una col·laboració externa requerix les autoritzacions que corresponguen."],
  ]},
  { id: "revision", title: ["3. Cómo se revisan los incumplimientos", "3. Com es revisen els incompliments"], paragraphs: [
   ["Usa Denunciar contenido y aporta la ubicación exacta y los hechos. Se valoran el contexto, la gravedad, el riesgo y la reiteración; no se retira contenido solo por acumular denuncias. Puede ser necesario limitar provisionalmente un contenido mientras se revisa un riesgo concreto.", "Usa Denunciar contingut i aporta la ubicació exacta i els fets. Es valoren el context, la gravetat, el risc i la reiteració; no es retira contingut només per acumular denúncies. Pot ser necessari limitar provisionalment un contingut mentre es revisa un risc concret."],
   ["Las medidas y su revisión siguen las condiciones de uso. Una denuncia de buena fe no se sanciona porque finalmente se descarte; sí puede actuarse frente al abuso deliberado del canal. No publiques acusaciones o datos de la persona denunciada en el foro para sustituir el procedimiento.", "Les mesures i la revisió seguixen les condicions d’ús. Una denúncia de bona fe no se sanciona perquè finalment es descarte; sí que es pot actuar davant de l’abús deliberat del canal. No publiques acusacions o dades de la persona denunciada en el fòrum per a substituir el procediment."],
  ]},
 ],
 rights: [
  { id: "solicitud", title: ["1. Solicitar acceso, cambios o eliminación", "1. Sol·licitar accés, canvis o eliminació"], paragraphs: [
   ["Escribe a hola@entreclases.com indicando qué necesitas: acceso o copia, rectificación, supresión o baja, limitación, oposición, portabilidad o retirada de un consentimiento. Si tienes cuenta, utiliza preferiblemente su correo; si ya no puedes acceder a él, indícalo para acordar una verificación proporcionada.", "Escriu a hola@entreclases.com indicant què necessites: accés o còpia, rectificació, supressió o baixa, limitació, oposició, portabilitat o retirada d’un consentiment. Si tens compte, utilitza preferiblement el seu correu; si ja no hi pots accedir, indica-ho per a acordar una verificació proporcionada."],
   ["Incluye el correo o identificador al que se refiere la solicitud y una descripción concreta. No envíes tu contraseña ni una copia de tu DNI de forma preventiva. Solo se pedirá información adicional cuando sea necesaria para confirmar tu identidad o localizar los datos, y se explicará el motivo.", "Inclou el correu o identificador al qual es referix la sol·licitud i una descripció concreta. No envies la contrasenya ni una còpia del DNI de manera preventiva. Només es demanarà informació addicional quan siga necessària per a confirmar la identitat o localitzar les dades, i s’explicarà el motiu."],
  ]},
  { id: "baja", title: ["2. Qué implica la baja", "2. Què implica la baixa"], paragraphs: [
   ["La solicitud se tramita por atención humana; el enlace de correo no ejecuta un borrado automático. Indica si deseas cerrar la cuenta y suprimir sus datos o retirar solo una aportación. Podemos aclarar el alcance antes de realizar una operación irreversible.", "La sol·licitud es tramita per atenció humana; l’enllaç de correu no executa un esborrat automàtic. Indica si vols tancar el compte i suprimir les dades o retirar només una aportació. Podem aclarir l’abast abans de fer una operació irreversible."],
   ["La revisión incluye autenticación, perfil, imágenes, archivos, mensajes, proyectos, invitaciones, puntos y registros asociados. Te informaremos de los datos eliminados y de cualquier conservación restringida que resulte necesaria, su motivo y criterio temporal. Salir de un grupo, borrar datos del navegador o cerrar sesión no equivale a eliminar la cuenta.", "La revisió inclou autenticació, perfil, imatges, arxius, missatges, projectes, invitacions, punts i registres associats. T’informarem de les dades eliminades i de qualsevol conservació restringida que resulte necessària, el motiu i criteri temporal. Eixir d’un grup, esborrar dades del navegador o tancar sessió no equival a eliminar el compte."],
  ]},
  { id: "respuesta", title: ["3. Respuesta y reclamación", "3. Resposta i reclamació"], paragraphs: [
   ["Las solicitudes se atienden gratuitamente, salvo las excepciones legales para peticiones manifiestamente infundadas o excesivas, que deben justificarse. El plazo ordinario de respuesta es un mes; puede ampliarse hasta dos meses adicionales cuando la ley lo permita, informándote en el primer mes.", "Les sol·licituds s’atenen gratuïtament, excepte les excepcions legals per a peticions manifestament infundades o excessives, que s’han de justificar. El termini ordinari de resposta és un mes; es pot ampliar fins a dos mesos addicionals quan la llei ho permeta, informant-te en el primer mes."],
   ["Si no atendemos tu solicitud o no estás conforme, puedes reclamar ante la AEPD o la autoridad competente y acudir a las vías judiciales que correspondan. Solicitar una revisión al soporte no supone renunciar a esas vías.", "Si no atenem la sol·licitud o no hi estàs conforme, pots reclamar davant de l’AEPD o l’autoritat competent i acudir a les vies judicials que corresponguen. Sol·licitar una revisió al suport no suposa renunciar a eixes vies."],
  ]},
 ],
 reports: [
  { id: "comunicar", title: ["1. Comunicar contenido ilícito o una infracción", "1. Comunicar contingut il·lícit o una infracció"], paragraphs: [
   ["Puedes comunicarlo sin tener cuenta, escribiendo a hola@entreclases.com con el asunto «Denuncia de contenido». El botón de esta página prepara un correo; debes enviarlo desde tu aplicación. No confirma por sí solo la recepción de una denuncia.", "Pots comunicar-ho sense tindre compte, escrivint a hola@entreclases.com amb l’assumpte «Denúncia de contingut». El botó d’esta pàgina prepara un correu; l’has d’enviar des de la teua aplicació. No confirma per si mateix la recepció d’una denúncia."],
  ], bullets: [
   ["Localización exacta: URL, identificador de publicación, perfil, grupo o archivo, y cualquier dato necesario para encontrarlo. Si es privado, describe el contexto sin divulgarlo públicamente.", "Localització exacta: URL, identificador de publicació, perfil, grup o arxiu, i qualsevol dada necessària per a trobar-lo. Si és privat, descriu el context sense divulgar-lo públicament."],
   ["Motivo: explica los hechos y por qué crees que el contenido es ilícito o infringe una norma. Si reclamas derechos de autor, identifica la obra, tu relación con el titular y el contenido infractor. Adjunta solo pruebas pertinentes y lícitas.", "Motiu: explica els fets i per què creus que el contingut és il·lícit o infringix una norma. Si reclames drets d’autor, identifica l’obra, la teua relació amb el titular i el contingut infractor. Adjunta només proves pertinents i lícites."],
   ["Contacto: nombre y correo para responder. No exigimos esos datos identificativos cuando resulte aplicable la excepción legal para avisos de abuso sexual infantil. No descargues ni adjuntes ese material: indica su ubicación.", "Contacte: nom i correu per a respondre. No exigim eixes dades identificatives quan resulte aplicable l’excepció legal per a avisos d’abús sexual infantil. No descarregues ni adjuntes eixe material: indica la ubicació."],
   ["Buena fe: indica que consideras de buena fe que la información y las alegaciones enviadas son precisas y completas.", "Bona fe: indica que consideres de bona fe que la informació i les al·legacions enviades són precises i completes."],
  ]},
  { id: "tramite", title: ["2. Qué ocurre después", "2. Què ocorre després"], paragraphs: [
   ["Cuando dispongamos de un contacto electrónico, acusaremos recibo sin dilación indebida y comunicaremos la decisión y las vías de revisión. Si falta información para identificar el contenido o entender el motivo, podemos solicitarla. Se evaluará cada aviso de forma diligente y objetiva; la presentación no garantiza la retirada.", "Quan disposem d’un contacte electrònic, acusarem recepció sense dilació indeguda i comunicarem la decisió i les vies de revisió. Si falta informació per a identificar el contingut o entendre el motiu, podem sol·licitar-la. S’avaluarà cada avís de manera diligent i objectiva; la presentació no garantix la retirada."],
   ["Los datos de la denuncia se utilizan para su gestión, defensa de derechos y cumplimiento de obligaciones. No se publican en el foro. Se limitará la comunicación al afectado o a autoridades a lo necesario y legalmente procedente; no se garantiza anonimato absoluto frente a una obligación legal de identificación.", "Les dades de la denúncia s’utilitzen per a la gestió, defensa de drets i compliment d’obligacions. No es publiquen en el fòrum. Es limitarà la comunicació a la persona afectada o a autoritats al que siga necessari i legalment procedent; no es garantix anonimat absolut davant d’una obligació legal d’identificació."],
  ]},
  { id: "reclamar", title: ["3. Pedir revisión de una decisión", "3. Demanar revisió d’una decisió"], paragraphs: [
   ["Responde al mensaje recibido o escribe con el asunto «Revisión de moderación», identificando la decisión, su fecha y tus motivos. Puedes solicitar revisión gratuitamente durante al menos seis meses. Se valorará por una persona la información aportada; si la decisión era incorrecta, se corregirá en lo que proceda y se te informará.", "Respon al missatge rebut o escriu amb l’assumpte «Revisió de moderació», identificant la decisió, la data i els motius. Pots sol·licitar revisió gratuïtament durant almenys sis mesos. Una persona valorarà la informació aportada; si la decisió era incorrecta, es corregirà en allò que corresponga i se t’informarà."],
   ["Estas vías no impiden acudir a autoridades, tribunales u otros mecanismos de resolución que resulten aplicables. Ante un riesgo inmediato llama al 112. No esperes una respuesta del soporte para protegerte de una emergencia.", "Estes vies no impedixen acudir a autoritats, tribunals o altres mecanismes de resolució que resulten aplicables. Davant d’un risc immediat telefona al 112. No esperes una resposta del suport per a protegir-te d’una emergència."],
  ]},
 ],
};

export function legalSections(kind: LegalKind, locale: Locale) {
 const i = locale === "va" ? 1 : 0;
 return content[kind].map(section => ({ id: section.id, title: section.title[i], paragraphs: section.paragraphs?.map(p => p[i]) ?? [], bullets: section.bullets?.map(p => p[i]) ?? [] }));
}
