import Link from "next/link";
import { localPath, type Locale } from "@/lib/i18n/routes";
import { LegalLinks } from "./legal-links";

// Identity must be supplied by the operator, not inferred from a GitHub account.
const controller = process.env.LEGAL_CONTROLLER_NAME?.trim();
const address = process.env.LEGAL_CONTROLLER_ADDRESS?.trim();
export function LegalPage({locale,kind}:{locale:Locale;kind:"privacy"|"terms"}) {
 const va=locale==="va", t=(es:string,translated:string)=>va?translated:es;
 return <main className="legal-page"><Link href={localPath(locale,"home")}>← Entreclases</Link><h1>{kind==="privacy"?t("Privacidad","Privacitat"):t("Condiciones de uso","Condicions d’ús")}</h1>
 <p>{t("Actualizado el 21 de septiembre de 2026.","Actualitzat el 21 de setembre de 2026.")}</p>
 <section><h2>{t("Quién gestiona Entreclases","Qui gestiona Entreclases")}</h2>{controller?<p>{controller}{address?` · ${address}`:""}</p>:<p>{t("La identificación legal del responsable está pendiente de completar. Puedes solicitarla antes de crear tu cuenta.","La identificació legal del responsable està pendent de completar. Pots sol·licitar-la abans de crear el compte.")}</p>}<p>{t("Contacto:","Contacte:")} <a href="mailto:hola@entreclases.com">hola@entreclases.com</a>.</p></section>
 {kind==="privacy"?<>
 <section><h2>{t("Datos y uso","Dades i ús")}</h2><p>{t("Utilizamos tu correo para verificar el acceso y gestionar la cuenta. El perfil, las publicaciones, los planes, las inscripciones, los grupos, los proyectos, los archivos y los mensajes permiten prestar las funciones de comunidad que utilizas. Las invitaciones guardan el correo del destinatario y su relación con la cuenta que invita para impedir reutilizaciones.","Utilitzem el correu per a verificar l’accés i gestionar el compte. El perfil, les publicacions, els plans, les inscripcions, els grups, els projectes, els arxius i els missatges permeten prestar les funcions de comunitat que utilitzes. Les invitacions guarden el correu del destinatari i la relació amb el compte que convida per a impedir reutilitzacions.")}</p></section>
 <section><h2>{t("Qué compartes","Què compartixes")}</h2><p>{t("Tu perfil y lo que publiques se muestran a las personas que pueden acceder a cada espacio. Los chats y los grupos privados tienen acceso restringido. Evita publicar datos personales de otras personas sin su permiso. Los gustos y la situación sentimental son opcionales: puedes dejarlos sin completar.","El perfil i el que publiques es mostren a les persones que poden accedir a cada espai. Els xats i els grups privats tenen accés restringit. Evita publicar dades personals d’altres persones sense permís. Els gustos i la situació sentimental són opcionals: pots deixar-los sense completar.")}</p></section>
 <section><h2>{t("Servicios y almacenamiento","Servicis i emmagatzematge")}</h2><p>{t("La plataforma utiliza Supabase para autenticación, base de datos y archivos; el envío de correo está preparado con Resend. Al abrir mapas o catálogos externos, sus proveedores reciben las solicitudes necesarias para mostrar ese contenido. El navegador conserva la sesión y algunos borradores. La demo usa perfiles ficticios y sus cambios no se comparten con usuarios reales.","La plataforma utilitza Supabase per a autenticació, base de dades i arxius; l’enviament de correu està preparat amb Resend. En obrir mapes o catàlegs externs, els proveïdors reben les peticions necessàries per a mostrar el contingut. El navegador conserva la sessió i alguns esborranys. La demo usa perfils ficticis i els canvis no es compartixen amb usuaris reals.")}</p></section>
 <section><h2>{t("Tus solicitudes","Les teues sol·licituds")}</h2><p>{t("Puedes solicitar acceso, rectificación o eliminación de tus datos, así como información sobre su tratamiento, escribiendo a hola@entreclases.com desde el correo de tu cuenta. Indica qué necesitas; no envíes tu contraseña. También puedes consultar tus derechos y presentar una reclamación ante la Agencia Española de Protección de Datos.","Pots sol·licitar accés, rectificació o eliminació de les dades, així com informació sobre el tractament, escrivint a hola@entreclases.com des del correu del compte. Indica què necessites; no envies la contrasenya. També pots consultar els drets i presentar una reclamació davant de l’Agència Espanyola de Protecció de Dades.")}</p><a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a></section>
 <section><h2>{t("Información pendiente de completar","Informació pendent de completar")}</h2><p>{t("Antes de la apertura pública, el responsable debe completar esta información con su identificación, las bases jurídicas, los plazos de conservación y las condiciones aplicables a proveedores y transferencias internacionales. Esta página describe el funcionamiento disponible; no sustituye esos datos pendientes.","Abans de l’obertura pública, el responsable ha de completar esta informació amb la identificació, les bases jurídiques, els terminis de conservació i les condicions aplicables a proveïdors i transferències internacionals. Esta pàgina descriu el funcionament disponible; no substituïx les dades pendents.")}</p></section>
 </>:<>
 <section><h2>{t("Acceso y tu +1","Accés i el teu +1")}</h2><p>{t("El acceso requiere un correo universitario admitido o una invitación personal válida y, en ambos casos, confirmar el correo. Cada cuenta universitaria puede invitar a una persona después de completar el perfil y participar. Las cuentas invitadas no generan invitaciones. No suplantes identidades ni compartas tus credenciales.","L’accés requerix un correu universitari admés o una invitació personal vàlida i, en els dos casos, confirmar el correu. Cada compte universitari pot convidar una persona després de completar el perfil i participar. Els comptes convidats no generen invitacions. No suplantes identitats ni compartisques les credencials.")}</p></section>
 <section><h2>{t("Convivencia y contenido","Convivència i contingut")}</h2><p>{t("Respeta a las demás personas. No publiques acoso, amenazas, suplantaciones, spam ni archivos que no tengas derecho a compartir. Conservas tus derechos sobre tus aportaciones; publicarlas permite mostrarlas en el espacio que elijas. Puedes comunicar incidencias a hola@entreclases.com indicando el contenido afectado.","Respecta les altres persones. No publiques assetjament, amenaces, suplantacions, spam ni arxius que no tingues dret a compartir. Conserves els drets sobre les aportacions; publicar-les permet mostrar-les en l’espai que tries. Pots comunicar incidències a hola@entreclases.com indicant el contingut afectat.")}</p></section>
 <section><h2>{t("Planes, proyectos y ClasiCoins","Plans, projectes i ClasiCoins")}</h2><p>{t("Comprueba fecha, lugar, plazas y condiciones antes de participar en un plan o proyecto. La inscripción no confirma asistencia física. Las ClasiCoins son incentivos internos: no se compran, no se venden ni se convierten en dinero. Los costes y límites se muestran antes de actuar y en el monedero.","Comprova data, lloc, places i condicions abans de participar en un pla o projecte. La inscripció no confirma assistència física. Les ClasiCoins són incentius interns: no es compren, no es venen ni es convertixen en diners. Els costos i límits es mostren abans d’actuar i en el moneder.")}</p></section>
 </>}
 <LegalLinks locale={locale}/></main>;
}
