import type { Locale } from "@/lib/i18n/routes";
import type { View } from "@/lib/community/types";
import type { Edition } from "./types";

// Platform-owned opening issue, separate from community submissions and consent.
// Editorial voice and fact-checking guidance: docs/entre-lineas-voz-editorial.md.
export const LAUNCH_EDITION_ID = "entre-lineas-bienvenida";
export type LaunchStory = {
  id: string; kind: "editorial"; title: string; body: string;
  attribution: string; section: string;
  action?: { view: View; label: string };
};

export function launchEdition(locale: Locale): { edition: Edition; introduction: string; stories: LaunchStory[] } {
  const text = (es: string, va: string) => locale === "va" ? va : es;
  const story = (id: string, section: string, title: string, body: string, action?: LaunchStory["action"]): LaunchStory => ({
    id: `bienvenida-${id}`, kind: "editorial", title, body, section,
    attribution: text("Equipo Entreclase", "Equip Entreclase"), action,
  });
  return {
    edition: { id: LAUNCH_EDITION_ID, title: text("¿Esta silla está libre?", "Esta cadira està lliure?"), date: "2026-09-20", published: true },
    introduction: text(
      "Una pregunta de cuatro palabras. Cabe un curso entero después. Abrimos Entre líneas para contarte qué puedes hacer aquí y por qué nos hemos metido en esto.",
      "Una pregunta de quatre paraules. Hi cap un curs sencer després. Obrim Entre línies per a contar-te què pots fer ací i per què ens hem ficat en açò."
    ),
    stories: [
      story("por-que", text("La silla de al lado", "La cadira del costat"), text("Le has pedido apuntes. Tres veces.", "Li has demanat apunts. Tres vegades."), text(
        "Piensa en alguien de tu clase cuyo nombre no sabes. Le reconoces la mochila, sabes dónde se sienta y quizá tienes un PDF suyo guardado. Si mañana te saluda por la calle, tienes preparado un «¡ey!» de emergencia.\n\nEntreclase empieza por ahí. Por lo fácil que es compartir meses con alguien y seguir sin saber cómo se llama. La universidad ya os ha puesto en el mismo edificio. Ahora estaría bien tener una excusa para hablar que no fuera pedirle otra vez el tema cuatro.\n\nEstamos creando una comunidad universitaria que empieza en Valencia. Entras con tu correo universitario, cuentas algo de ti y puedes encontrar gente, planes y proyectos de otras clases, carreras y campus.\n\nQuizá buscas compañía para estudiar. Quizá quieres ir a un concierto y tus amigos no conocen ni al grupo. No hace falta llegar con una gran historia. A veces empieza apartando la mochila de una silla.",
        "Pensa en algú de classe de qui no saps el nom. Li reconeixes la motxilla, saps on seu i potser tens un PDF seu guardat. Si demà et saluda pel carrer, tens preparat un «ei!» d’emergència.\n\nEntreclase comença per ací. Per com de fàcil és compartir mesos amb algú i continuar sense saber com es diu. La universitat ja vos ha posat en el mateix edifici. Ara estaria bé tindre una excusa per a parlar que no fora demanar-li una altra vegada el tema quatre.\n\nEstem creant una comunitat universitària que comença a València. Entres amb el correu universitari, contes alguna cosa de tu i pots trobar gent, plans i projectes d’altres classes, carreres i campus.\n\nPotser busques companyia per a estudiar. Potser vols anar a un concert i els teus amics no coneixen ni el grup. No cal arribar amb una gran història. A vegades comença apartant la motxilla d’una cadira."
      ), { view: "profile", label: text("Ponle nombre a tu perfil", "Posa-li nom al teu perfil") }),
      story("empezar", text("La primera vuelta", "La primera volta"), text("Tienes veinte minutos entre clases.", "Tens vint minuts entre classes."), text(
        "Te han cambiado el aula, la siguiente clase empieza dentro de veinte minutos y ya has mirado el móvil. Dos veces. Te proponemos otra forma de pasar ese rato.\n\nEn Inicio puedes ver qué se comparte, reaccionar a una publicación o abrir un hilo. Si lo que te apetece es salir del «hola, qué tal», entra en Explorar: hay planes, grupos, proyectos y juegos. Puedes curiosear antes de decidirte. Nadie te va a pasar lista.\n\nCharlas reúne el foro y el chat privado. Un sitio para preguntar si alguien entiende ese ejercicio y otro para seguir hablando con una persona. En tu perfil puedes contar qué estudias, qué te interesa y publicar cosas tuyas. Una foto, un trabajo que has terminado, algo que te apetece enseñar.\n\nCon que encuentres una cosa que te interese, basta para empezar. El resto de la web seguirá aquí cuando termine la clase.",
        "T’han canviat l’aula, la classe següent comença d’ací a vint minuts i ja has mirat el mòbil. Dos vegades. Et proposem una altra manera de passar eixe rato.\n\nEn Inici pots vore què es compartix, reaccionar a una publicació o obrir un fil. Si et ve de gust eixir del «hola, què tal», entra en Explorar: hi ha plans, grups, projectes i jocs. Pots mirar abans de decidir-te. Ningú et passarà llista.\n\nXarrades reunix el fòrum i el xat privat. Un lloc per a preguntar si algú entén eixe exercici i un altre per a continuar parlant amb una persona. En el teu perfil pots contar què estudies, què t’interessa i publicar coses teues. Una foto, un treball que has acabat, alguna cosa que et vinga de gust ensenyar.\n\nAmb trobar una cosa que t’interesse, n’hi ha prou per a començar. La resta de la web continuarà ací quan acabe la classe."
      ), { view: "explore", label: text("Ver qué me apetece hacer", "Vore què em ve de gust fer") }),
      story("planes", text("Ponerle fecha", "Posar-li data"), text("El jueves sí existe.", "El dijous sí que existix."), text(
        "«Tenemos que quedar.»\n\nLa frase tiene una ventaja estupenda: todo el mundo puede estar de acuerdo sin mover un dedo. Luego alguien manda un meme, cambia el tema y otra semana que se va.\n\nPrueba con algo más concreto: «El jueves, a las seis, café en Benimaclet. Me llevo los apuntes, por si acaso». Ya hay una hora, un lugar y algo a lo que decir que sí. O que no. Las dos respuestas sirven bastante más que un «ya veremos».\n\nPara eso están los planes de Entreclase. Puedes consultar quién se apunta, dónde se queda y si hay plazas; o proponer uno tú. Explica bien el punto de encuentro: llegar a un sitio nuevo ya da suficiente corte como para tener que adivinar cuál es la mesa.\n\nSi os apetece repetir, un grupo puede ayudar a seguir en contacto. Para estudiar, ir al cine o salir a correr. Hasta podéis quedar solo para tomar café. Los apuntes no se van a ofender.",
        "«Hem de quedar.»\n\nLa frase té un avantatge fantàstic: tothom pot estar d’acord sense moure un dit. Després algú envia un mem, canvia el tema i una altra setmana que se’n va.\n\nProva amb alguna cosa més concreta: «Dijous, a les sis, café a Benimaclet. Em porte els apunts, per si de cas». Ja hi ha una hora, un lloc i alguna cosa a la qual dir que sí. O que no. Les dos respostes servixen prou més que un «ja vorem».\n\nPer a això estan els plans d’Entreclase. Pots consultar qui s’apunta, on es queda i si hi ha places; o proposar-ne un tu. Explica bé el punt de trobada: arribar a un lloc nou ja fa prou vergonya per a haver d’endevinar quina és la taula.\n\nSi vos ve de gust repetir, un grup pot ajudar a continuar en contacte. Per a estudiar, anar al cine o eixir a córrer. Fins i tot podeu quedar només per a prendre café. Els apunts no s’ofendran."
      ), { view: "plans", label: text("Buscar un plan con fecha", "Buscar un pla amb data") }),
      story("proyectos", text("Lo que falta", "El que falta"), text("Tu idea ya tiene carpeta. Le falta equipo.", "La teua idea ja té carpeta. Li falta equip."), text(
        "Imagina que estudias moda. Tienes los diseños, las telas y una idea para enseñar cómo quedaría la colección sin coser cada prenda. Abres el portátil, buscas cómo hacer un probador virtual y, diez pestañas después, cierras el portátil.\n\nTe falta alguien que sepa hacer esa parte. A esa persona puede faltarle un proyecto donde probar lo que sabe. Quizá estudia a diez minutos de ti.\n\nLos proyectos, dentro de Explorar, sirven para que podáis encontraros. Cuenta el resultado que buscas, qué tienes ya y qué vas a aportar tú. Deja claros los puestos, el tiempo que pides y qué ofreces: aprendizaje, un trabajo para el portfolio o remuneración, si la hay. Eso permite decidir con ganas y con información.\n\nQuien quiera colaborar propone su aportación y el responsable acepta las incorporaciones. También puedes seguir los avances sin entrar en el equipo.\n\nNos gustaría que esa carpeta acabara conteniendo algo que enseñar. Y varios nombres en los créditos.",
        "Imagina que estudies moda. Tens els dissenys, les teles i una idea per a ensenyar com quedaria la col·lecció sense cosir cada peça. Obres el portàtil, busques com fer un emprovador virtual i, deu pestanyes després, tanques el portàtil.\n\nEt falta algú que sàpia fer eixa part. A eixa persona pot faltar-li un projecte on provar el que sap. Potser estudia a deu minuts de tu.\n\nEls projectes, dins d’Explorar, servixen perquè vos pugueu trobar. Conta el resultat que busques, què tens ja i què aportaràs tu. Deixa clars els llocs, el temps que demanes i què oferixes: aprenentatge, un treball per al portfolio o remuneració, si n’hi ha. Això permet decidir amb ganes i amb informació.\n\nQui vulga col·laborar proposa la seua aportació i el responsable accepta les incorporacions. També pots seguir els avanços sense entrar en l’equip.\n\nEns agradaria que eixa carpeta acabara contenint alguna cosa per a ensenyar. I uns quants noms en els crèdits."
      ), { view: "projects", label: text("Ver a quién le falta alguien", "Vore a qui li falta algú") }),
      story("objetivos", text("Para qué todo esto", "Per a què tot açò"), text("La matrícula no incluye conocer gente.", "La matrícula no inclou conéixer gent."), text(
        "Te dan un horario, un correo y unas claves. Lo de encontrar con quién comer el primer día suele venir sin instrucciones. Y puedes estar en cuarto y seguir queriendo conocer a alguien fuera de tu grupo de siempre.\n\nCon Entreclase queremos hacer más fácil ese encuentro. Entre carreras, entre campus, entre quien llega y quien ya conoce la ciudad. Que puedas entrar a un plan sin tener que conocer antes a media mesa. Que encuentres con quién sacar una idea del cajón.\n\nEstamos empezando. Queremos saber si los planes se celebran, si los equipos consiguen avanzar y si alguien vuelve porque ha encontrado gente con la que está a gusto. Todavía tenemos que demostrarlo.\n\nPor eso nos interesa que nos cuentes dónde te has perdido, qué te falta y qué repetirías. También vale decir «esto no lo entiende nadie». Preferimos enterarnos.\n\nSi dentro de un tiempo saludas por su nombre a alguien con quien antes solo compartías pasillo, habrá merecido la pena montar todo esto.",
        "Et donen un horari, un correu i unes claus. Això de trobar amb qui dinar el primer dia sol vindre sense instruccions. I pots estar en quart i continuar volent conéixer algú fora del teu grup de sempre.\n\nAmb Entreclase volem fer més fàcil eixa trobada. Entre carreres, entre campus, entre qui arriba i qui ja coneix la ciutat. Que pugues entrar a un pla sense haver de conéixer abans mitja taula. Que trobes amb qui traure una idea del calaix.\n\nEstem començant. Volem saber si els plans se celebren, si els equips aconseguixen avançar i si algú torna perquè ha trobat gent amb qui està a gust. Encara hem de demostrar-ho.\n\nPer això ens interessa que ens contes on t’has perdut, què et falta i què repetiries. També val dir «això no ho entén ningú». Preferim saber-ho.\n\nSi d’ací a un temps saludes pel seu nom algú amb qui abans només comparties corredor, haurà valgut la pena muntar tot açò."
      ), { view: "messages", label: text("Contar qué me falta", "Contar què em falta") }),
      story("editorial", text("La letra pequeña, legible", "La lletra menuda, llegible"), text("Para salir aquí, hace falta algo que contar.", "Per a eixir ací, cal tindre alguna cosa per contar."), text(
        "Un cartel de «buscamos gente» cuenta poco. Saber que alguien quiere rodar un corto, tiene cámara y necesita quien grabe el sonido ya te da una razón para seguir leyendo. A lo mejor tienes un micro cogiendo polvo.\n\nEse es el trabajo de Entre líneas: contar qué está haciendo la gente y dónde puedes entrar tú. La propuesta es una edición semanal de hasta seis piezas: proyectos, avances, planes, conversaciones e iniciativas con su fuente. También queremos contar lo que cuesta empezar, aunque todavía no haya una foto del resultado.\n\nElegiremos por utilidad, actualidad y variedad de carreras y campus. Habrá sitio para quien acaba de llegar. Los ClasiCoins no compran una página y acumular likes no garantiza salir.\n\nY el permiso va antes que la publicación. Cada autor ve y autoriza su texto y su nombre tal como aparecerán. Puede retirar esa autorización, también del archivo. Si citamos una respuesta, necesitamos el permiso de quien la escribió. Las conversaciones privadas se quedan fuera. Publicar aquí, dentro de la comunidad verificada, no autoriza a llevarlo a otras webs o redes.\n\nEn este primer número nos tocaba presentarnos. Para el siguiente, cuéntanos qué tienes entre manos. Incluso si lo que te falta es una mano.",
        "Un cartell de «busquem gent» conta poc. Saber que algú vol rodar un curt, té càmera i necessita qui grave el so ja et dona una raó per a continuar llegint. Potser tens un micro agafant pols.\n\nEixe és el treball d’Entre línies: contar què està fent la gent i on pots entrar tu. La proposta és una edició setmanal de fins a sis peces: projectes, avanços, plans, converses i iniciatives amb la seua font. També volem contar el que costa començar, encara que no hi haja una foto del resultat.\n\nTriarem per utilitat, actualitat i varietat de carreres i campus. Hi haurà lloc per a qui acaba d’arribar. Els ClasiCoins no compren una pàgina i acumular likes no garantix eixir.\n\nI el permís va abans que la publicació. Cada autor veu i autoritza el text i el nom tal com apareixeran. Pot retirar eixa autorització, també de l’arxiu. Si citem una resposta, necessitem el permís de qui l’ha escrita. Les converses privades es queden fora. Publicar ací, dins de la comunitat verificada, no autoritza a portar-ho a altres webs o xarxes.\n\nEn este primer número ens tocava presentar-nos. Per al següent, conta’ns què tens entre mans. Encara que el que et falte siga una mà."
      )),
    ],
  };
}
