"use client";
import { useState } from "react";
import { Action } from "../controls";
import { GameFrame, Say, Thread, useGame, useWords } from "./shared";

export default function CitaACiegas() {
  const g = useGame("blind"), t = useWords();
  const [adult, setAdult] = useState(false);
  return <GameFrame game={g}><p>{t("Los jueves, de 19:30 a 21:00 (hora de Valencia). Dos personas, doce minutos y ninguna foto. El nombre y el chat privado solo se desbloquean si ambos queréis. Puedes salir en cualquier momento.", "Els dijous, de 19:30 a 21:00 (hora de València). Dues persones, dotze minuts i cap foto. El nom i el xat privat només es desbloquegen si tots dos voleu. Pots eixir en qualsevol moment.")}</p>{!g.rooms.length && <div className="ec-game-form"><label className="ec-game-check"><input type="checkbox" checked={adult} onChange={e => setAdult(e.target.checked)}/>{t("Tengo 18 años o más y quiero participar.", "Tinc 18 anys o més i vull participar.")}</label><Action disabled={!adult || g.busy} onClick={() => void g.act("create", { adult })}>{t("Buscar compañía", "Buscar companyia")}</Action>{g.demo && <p>{t("En la demo puedes probarlo cualquier día.", "En la demo pots provar-ho qualsevol dia.")}</p>}</div>}{g.rooms.map(r => <article key={r.id} className="ec-game-entry"><h4>{r.count < 2 ? t("Buscando a alguien del campus…", "Buscant algú del campus…") : r.revealed ? r.owner_name : t("Ya hay alguien al otro lado", "Ja hi ha algú a l'altre costat")}</h4>{r.expires && <p>{t("La sala cierra a las", "La sala tanca a les")} {new Intl.DateTimeFormat("es-ES", { hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid" }).format(new Date(r.expires))}</p>}{r.count === 2 && <><p className="ec-game-prompt">{t("Para romper el hielo: ¿qué plan improvisado te salió sorprendentemente bien?", "Per a trencar el gel: quin pla improvisat et va eixir sorprenentment bé?")}</p><Thread room={r}/><Say label={t("Tu mensaje", "El teu missatge")} busy={g.busy} onSend={body => g.act("say", { id:r.id,body })}/>{r.revealed ? <div className="ec-game-result" role="status"><strong>{t("Los dos queréis seguir hablando.", "Els dos voleu continuar parlant.")}</strong>{r.peer_id && <Action onClick={() => void g.chat(r.peer_id!)}>{t("Continuar en privado", "Continuar en privat")}</Action>}{g.demo && <p>{t("Conexión de ejemplo. No hay una persona real en esta sala.", "Connexió d'exemple. No hi ha una persona real en esta sala.")}</p>}</div> : r.moves.some(m => m.kind === "reveal" && m.mine) ? <p role="status">{t("Has dado tu permiso. Falta el de la otra persona.", "Has donat el teu permís. Falta el de l'altra persona.")}</p> : <Action disabled={g.busy} onClick={() => void g.act("reveal", { id:r.id })}>{t("Quiero revelar mi perfil si tú también", "Vull revelar el meu perfil si tu també")}</Action>}</>}<div className="ec-game-actions">{g.demo && <Action secondary disabled={g.busy} onClick={() => void g.act("simulate", { id:r.id })}>{t("Demo: simular a la otra persona", "Demo: simular l'altra persona")}</Action>}<Action secondary disabled={g.busy} onClick={() => void g.act("leave", { id:r.id })}>{t("Salir de la cita", "Eixir de la cita")}</Action></div></article>)}</GameFrame>;
}
