"use client";
import { useState } from "react";
import { Action, TextField } from "../controls";
import { EmptyGame, GameFrame, useGame, useWords } from "./shared";

export default function DosVerdades() {
  const g = useGame("truth"), t = useWords();
  const [options, setOptions] = useState(["", "", ""]), [choice, setChoice] = useState(0);
  return <GameFrame game={g}><p>{t("Cuenta tres cosas sobre ti. Dos reales y una inventada. La solución se descubre después de apostar.", "Conta tres coses sobre tu. Dues reals i una inventada. La solució es descobrix després d'apostar.")}</p><form className="ec-game-form" onSubmit={async e => { e.preventDefault(); if (await g.act("create", { options, choice })) setOptions(["", "", ""]); }}><fieldset><legend>{t("Tu ronda: marca la mentira", "La teua ronda: marca la mentida")}</legend>{options.map((s, i) => <div className="ec-game-statement" key={i}><TextField label={`${t("Frase", "Frase")} ${i + 1}`} required maxLength={180} value={s} onChange={e => setOptions(options.map((v, j) => j === i ? e.target.value : v))}/><label className="ec-game-check"><input type="radio" name="truth-answer" checked={choice === i} onChange={() => setChoice(i)}/>{t("Es la mentira", "És la mentida")}</label></div>)}</fieldset><Action type="submit" disabled={g.busy || options.some(s => !s.trim())}>{t("Publicar mi ronda", "Publicar la meua ronda")}</Action></form>{!g.rooms.length && <EmptyGame/>}{g.rooms.map(r => <article className="ec-game-entry" key={r.id}><h4>{r.owner_name}</h4><div className="ec-game-choices">{r.options.map((s, i) => <Action secondary key={i} disabled={g.busy || r.mine || r.my_choice !== null} onClick={() => void g.act("vote", { id: r.id, choice: i })}>{s}{r.answer === i ? ` · ${t("MENTIRA", "MENTIDA")}` : ""}{r.my_choice === i ? " ✓" : ""}</Action>)}</div>{r.my_choice !== null && <p className="ec-game-result" role="status">{r.answer === r.my_choice ? t("¡Pillada! Has acertado.", "Pillada! Has encertat.") : t("Te la ha colado. Ya tienes tema de conversación.", "Te l'ha colada. Ja tens tema de conversa.")}</p>}{r.mine && <Action secondary disabled={g.busy} onClick={() => void g.act("delete", { id: r.id })}>{t("Borrar mi ronda", "Esborrar la meua ronda")}</Action>}</article>)}</GameFrame>;
}
