"use client";
import { useState } from "react";
import { Action, SelectField, TextField } from "../controls";
import { EmptyGame, GameFrame, Say, Thread, useGame, useWords } from "./shared";

export default function HayHueco() {
  const g = useGame("hangout"), t = useWords();
  const [body, setBody] = useState(""), [place, setPlace] = useState(""), [capacity, setCapacity] = useState(3), [minutes, setMinutes] = useState(40);
  return <GameFrame game={g}><p>{t("¿Tienes un rato libre? Di dónde y cuántos cabéis. Al apuntarte se abre la conversación del grupo. El encuentro desaparece al terminar el tiempo.", "Tens una estona lliure? Digues on i quants cabeu. En apuntar-te s'obri la conversa del grup. La trobada desapareix en acabar el temps.")}</p><form className="ec-game-form" onSubmit={async e => { e.preventDefault(); if (await g.act("create", { body, place, capacity, minutes })) { setBody(""); setPlace(""); } }}><TextField label={t("¿Qué te apetece?", "Què t'abellix?")} placeholder="Un café antes de clase" value={body} onChange={e => setBody(e.target.value)} maxLength={200} required/><TextField label={t("Lugar de encuentro", "Lloc de trobada")} value={place} onChange={e => setPlace(e.target.value)} maxLength={120} required/><div className="ec-game-fields"><SelectField label={t("Personas, incluyéndote", "Persones, incloent-te")} value={capacity} onChange={e => setCapacity(+e.target.value)}>{[2,3,4,5,6,7,8].map(n => <option key={n}>{n}</option>)}</SelectField><SelectField label={t("Disponible durante", "Disponible durant")} value={minutes} onChange={e => setMinutes(+e.target.value)}>{[15,30,40,60,90,120].map(n => <option key={n} value={n}>{n} min</option>)}</SelectField></div><Action type="submit" disabled={g.busy || !body.trim() || !place.trim()}>{t("Abrir hueco", "Obrir lloc")}</Action></form>{!g.rooms.length && <EmptyGame/>}{g.rooms.map(r => <article className="ec-game-entry" key={r.id}><h4>{r.body}</h4><p>{r.place} · {r.count}/{r.capacity} · {t("Hasta las", "Fins a les")} {r.expires && new Intl.DateTimeFormat("es-ES", { hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid" }).format(new Date(r.expires))}</p><p>{r.owner_name}</p>{r.joined ? <><Thread room={r}/><Say label={t("Habla con quienes se han apuntado", "Parla amb qui s'ha apuntat")} busy={g.busy} onSend={body => g.act("say", { id:r.id,body })}/><Action secondary disabled={g.busy} onClick={() => void g.act("leave", { id:r.id })}>{r.mine ? t("Cerrar el encuentro", "Tancar la trobada") : t("Liberar mi plaza", "Alliberar la meua plaça")}</Action></> : <Action disabled={g.busy || r.count >= r.capacity} onClick={() => void g.act("join", { id:r.id })}>{r.count >= r.capacity ? t("Completo", "Complet") : t("Me apunto", "M'apunte")}</Action>}</article>)}</GameFrame>;
}
