"use client";
import { useState } from "react";
import { Action, TextField } from "../controls";
import { EmptyGame, GameFrame, Say, Thread, useGame, useWords } from "./shared";

export default function JuradoDelCampus() {
  const g = useGame("jury"), t = useWords();
  const [body, setBody] = useState(""), [options, setOptions] = useState(["", ""]);
  return <GameFrame game={g}><p>{t("Un dilema del campus. Primero votas sin ver al resto; después ves el resultado y puedes explicar tu veredicto. Cuenta situaciones sin señalar a personas.", "Un dilema del campus. Primer votes sense vore la resta; després veus el resultat i pots explicar el teu veredicte. Conta situacions sense assenyalar persones.")}</p><form className="ec-game-form" onSubmit={async e => { e.preventDefault(); if (await g.act("create", { body, options })) { setBody(""); setOptions(["", ""]); } }}><TextField label={t("El dilema", "El dilema")} value={body} required maxLength={200} onChange={e => setBody(e.target.value)}/>{options.map((s,i) => <TextField key={i} label={`${t("Postura", "Postura")} ${i+1}`} value={s} required maxLength={180} onChange={e => setOptions(options.map((v,j) => i===j ? e.target.value : v))}/>)}<Action type="submit" disabled={g.busy || !body.trim() || options.some(s => !s.trim())}>{t("Abrir el caso", "Obrir el cas")}</Action></form>{!g.rooms.length && <EmptyGame/>}{g.rooms.map(r => { const total = r.votes.reduce((a,b) => a+b,0); return <article className="ec-game-entry" key={r.id}><h4>{r.body}</h4><p>{r.owner_name}</p><div className="ec-game-choices">{r.options.map((s,i) => <Action secondary key={i} disabled={g.busy || r.my_choice !== null} onClick={() => void g.act("vote", { id:r.id,choice:i })}>{s}{r.my_choice !== null ? ` · ${r.votes[i] || 0} (${total ? Math.round((r.votes[i] || 0)/total*100) : 0}%)` : ""}{r.my_choice === i ? " ✓" : ""}</Action>)}</div>{r.my_choice !== null && <><p role="status">{total} {t("votos · Tu veredicto está guardado.", "vots · El teu veredicte està guardat.")}</p><Thread room={r}/><Say label={t("Defiende tu veredicto", "Defén el teu veredicte")} busy={g.busy} onSend={body => g.act("say", { id:r.id,body })}/></>}{r.mine && <Action secondary disabled={g.busy} onClick={() => void g.act("delete", { id:r.id })}>{t("Cerrar el caso", "Tancar el cas")}</Action>}</article>; })}</GameFrame>;
}
