import type { StudyActivity, StudyLesson, StudyMode, StudySource } from "./learning";
export const sampleSubjectId="study-example-economics";
export const sampleSource:StudySource={id:"study-example-opportunity",name:"Decidir también tiene un coste · material de ejemplo",text:"El coste de oportunidad es el valor de la mejor alternativa a la que renuncias cuando tomas una decisión. No es la suma de todas las alternativas descartadas. Una decisión puede tener coste de oportunidad aunque no haya un pago de dinero. Para comparar opciones, primero identifica las alternativas viables, después valora qué aporta cada una, elige una opción y reconoce la mejor alternativa descartada. Por ejemplo, si dedicas una tarde a estudiar en lugar de trabajar o descansar, el coste de oportunidad es el valor de la mejor de esas dos alternativas, según tus prioridades. El dinero que ya has gastado y no puedes recuperar es un coste hundido; no cambia por lo que decidas ahora."};
export function exampleLesson(mode:StudyMode,minutes:number,va=false):StudyLesson{
 const t=(es:string,v:string)=>va?v:es;
 const quote="El coste de oportunidad es el valor de la mejor alternativa a la que renuncias cuando tomas una decisión.";
 const base={topic:t("Coste de oportunidad","Cost d’oportunitat"),sourceId:sampleSource.id,quote,correctOrder:[] as number[],modelAnswer:t("El valor de la mejor alternativa a la que renuncias.","El valor de la millor alternativa a què renuncies."),hint:t("Piensa en tu segunda mejor opción, no en todas a la vez.","Pensa en la teua segona millor opció, no en totes alhora."),explanation:t("Compara lo que eliges con la mejor opción que dejas pasar. Ese valor es el coste de oportunidad; puede ser tiempo, descanso o dinero.","Compara el que tries amb la millor opció que deixes passar. Eixe valor és el cost d’oportunitat: pot ser temps, descans o diners.")};
 const activities:StudyActivity[]=[
 {...base,kind:"choice",prompt:t("Si eliges una opción, ¿cuál es su coste de oportunidad?","Si tries una opció, quin és el seu cost d’oportunitat?"),options:[t("Lo que has pagado","El que has pagat"),t("La mejor alternativa descartada","La millor alternativa descartada"),t("Todas las alternativas sumadas","Totes les alternatives sumades")],answer:1},
 {...base,kind:"spot-error",prompt:t("Encuentra la afirmación que contradice los apuntes.","Troba l’afirmació que contradiu els apunts."),options:[t("Puede existir sin gastar dinero","Pot existir sense gastar diners"),t("Depende de las alternativas disponibles","Depén de les alternatives disponibles"),t("Es la suma de todo lo que no has elegido","És la suma de tot el que no has triat")],answer:2},
 {...base,kind:"case",prompt:t("Ejemplo inventado: eliges estudiar. Tu siguiente opción favorita era descansar y la tercera, trabajar. ¿A qué renuncias como coste de oportunidad?","Exemple inventat: tries estudiar. La teua segona opció era descansar i la tercera, treballar. Quin és el cost d’oportunitat?"),options:[t("Al descanso que preferías","Al descans que preferies"),t("Al descanso y al trabajo sumados","Al descans i al treball sumats"),t("A nada: estudiar es gratis","A res: estudiar és gratis")],answer:0},
 {...base,kind:"connect",prompt:t("Ordena los pasos para comparar una decisión.","Ordena els passos per a comparar una decisió."),options:[t("Elegir una opción","Triar una opció"),t("Identificar alternativas viables","Identificar alternatives viables"),t("Reconocer la mejor alternativa descartada","Reconéixer la millor alternativa descartada"),t("Valorar qué aporta cada alternativa","Valorar què aporta cada alternativa")],answer:-1,correctOrder:[1,3,0,2],quote:"Para comparar opciones, primero identifica las alternativas viables, después valora qué aporta cada una, elige una opción y reconoce la mejor alternativa descartada."},
 {...base,kind:"teach",prompt:t("Explícaselo a alguien que no conoce el concepto. Pon un ejemplo de una decisión tuya.","Explica-ho a algú que no coneix el concepte. Posa un exemple d’una decisió teua."),options:[],answer:-1},
 {...base,kind:"choice",prompt:t("Ejemplo inventado: pagaste una entrada que no puedes devolver. Ese pago ya realizado es…","Exemple inventat: vas pagar una entrada que no pots tornar. Eixe pagament és…"),options:[t("Un coste hundido","Un cost enfonsat"),t("Siempre el coste de oportunidad","Sempre el cost d’oportunitat"),t("La mejor alternativa disponible","La millor alternativa disponible")],answer:0,topic:t("Coste hundido","Cost enfonsat"),quote:"El dinero que ya has gastado y no puedes recuperar es un coste hundido; no cambia por lo que decidas ahora.",modelAnswer:t("Un coste hundido: ya no puedes recuperar ese dinero.","Un cost enfonsat: ja no pots recuperar eixos diners."),explanation:t("Ese pago pertenece al pasado. Decide lo que haces ahora comparando las alternativas que todavía tienes.","Eixe pagament pertany al passat. Decideix comparant les alternatives que encara tens."),hint:t("¿Puedes recuperar ese pago cambiando tu decisión?","Pots recuperar eixe pagament canviant la decisió?")}
 ];
 const wanted=mode==='mixed'||mode==='sprint'?activities:[activities[0],...activities.slice(1).sort((a,b)=>Number(b.kind===mode)-Number(a.kind===mode))];
 return {title:t("Elegir también es aprender","Triar també és aprendre"),objective:t("Reconocer qué dejas pasar cuando eliges.","Reconéixer què deixes passar quan tries."),introduction:base.explanation,activities:wanted.slice(0,minutes===5?3:minutes===10?4:6)};
}
