"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, Compass, Flag, Lightbulb, LoaderCircle, Play, Settings2, Sparkles, Sprout, Target } from "lucide-react";
import { useCommunity } from "../context";
import { Modal } from "../controls";
import { notesStoreKey, useNotesStore } from "@/lib/community/student/notes";
import { newId, storageKey, useToolStore } from "@/lib/community/student/storage";
import { dueConcepts, emptyLearning, emptySubjects, finishSession, nextSubject, recordAnswer, summarizeSession, type StudyMode, type StudyPreferences, type StudySession } from "@/lib/community/student/learning";
import { exampleLesson, sampleSource, sampleSubjectId } from "@/lib/community/student/learning-demo";
import { prepareLearning } from "@/lib/community/student/learning-client";
import { toolPath } from "@/lib/community/student/catalog";
import { SubjectsWorkspace } from "./subjects";
import { SessionPlayer } from "./session-player";
import { StudySync } from "./study-sync";
import "./learning-center.css";
const modes:{id:StudyMode;title:[string,string];body:[string,string]}[]=[
 {id:"mixed",title:["Un poco de todo","Un poc de tot"],body:["Preguntas, casos y explicaciones tuyas.","Preguntes, casos i explicacions teues."]},
 {id:"spot-error",title:["Encuentra el fallo","Troba l’error"],body:["Pon a prueba lo que parece correcto.","Posa a prova el que sembla correcte."]},
 {id:"teach",title:["Ahora enseñas tú","Ara ensenyes tu"],body:["Explícalo con tus propias palabras.","Explica-ho amb les teues paraules."]},
 {id:"case",title:["Resuelve el caso","Resol el cas"],body:["Lleva el tema a una situación concreta.","Porta el tema a una situació concreta."]},
 {id:"connect",title:["Conecta las piezas","Connecta les peces"],body:["Ordena los pasos y descubre la relación.","Ordena els passos i descobrix la relació."]},
 {id:"sprint",title:["Reto de cinco minutos","Repte de cinc minuts"],body:["Tres actividades para seguir avanzando.","Tres activitats per a continuar avançant."]}
];
export function LearningCenter({onFocusChange}:{onFocusChange:(focused:boolean)=>void}){
 const {locale,demo,me}=useCommunity(),va=locale==="va",t=(es:string,v:string)=>va?v:es;
 const scope={demo,userId:me.user_id},key=storageKey(scope,"learning"),subjectKey=storageKey(scope,"subjects"),notesKey=notesStoreKey(scope);
 const [state,setState,ready,status]=useToolStore(key,emptyLearning);
 const [subjectState,setSubjects,subjectsReady]=useToolStore(subjectKey,emptySubjects);
 const {docs,addDoc,ready:notesReady}=useNotesStore(notesKey);
 const [screen,setScreen]=useState<"home"|"setup"|"session"|"memory"|"history">("home"),[openedId,setOpenedId]=useState<string|null>(null),[selectedId,setSelectedId]=useState("");
 const [preferencesOpen,setPreferencesOpen]=useState(false),[draftPreferences,setDraftPreferences]=useState<StudyPreferences>(emptyLearning.preferences),[interestsText,setInterestsText]=useState("");
 const [historySearch,setHistorySearch]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const generation=useRef(0);
 useEffect(()=>{onFocusChange(screen!=="home");return()=>onFocusChange(false);},[screen,onFocusChange]);
 useEffect(()=>()=>{generation.current++;},[key]);
 const subjects=subjectState.subjects.filter(s=>!s.archived),suggested=nextSubject(subjectState.subjects,state),due=dueConcepts(state).filter(c=>subjects.some(s=>s.id===c.subjectId));
 const active=state.sessions.find(s=>s.id===state.activeId&&!s.completedAt),session=state.sessions.find(s=>s.id===openedId),chosen=subjects.find(s=>s.id===selectedId);
 const completed=[...state.sessions.filter(s=>s.completedAt),...(state.archive??[])],today=new Date().toISOString().slice(0,10),todayCount=completed.filter(s=>s.completedAt?.startsWith(today)).length;
 const history=[...state.sessions.filter(s=>s.completedAt).map(summarizeSession),...(state.archive??[])].sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).filter(s=>(s.subjectName+" "+s.title+" "+s.topics.join(" ")).toLocaleLowerCase().includes(historySearch.toLocaleLowerCase()));
 const openSession=(s:StudySession)=>{setOpenedId(s.id);setScreen("session");setError("");};
 const setup=(id?:string)=>{setSelectedId(id??suggested?.id??"");setScreen("setup");setError("");};
 const preferences=()=>{setDraftPreferences(state.preferences);setInterestsText(state.preferences.interests.join(", "));setPreferencesOpen(true);};
 const useExample=()=>{
  if(!docs.some(d=>d.id===sampleSource.id))addDoc({...sampleSource,images:[],chars:sampleSource.text.length,addedAt:new Date().toISOString()});
  setSubjects(current=>({subjects:current.subjects.some(s=>s.id===sampleSubjectId)?current.subjects.map(s=>s.id===sampleSubjectId?{...s,archived:false}:s):[...current.subjects,{id:sampleSubjectId,name:t("Economía · ejemplo","Economia · exemple"),topic:t("Decidir y entender lo que dejas pasar","Decidir i entendre el que deixes passar"),examDate:"",noteIds:[sampleSource.id],createdAt:new Date().toISOString()}]}));
  setSelectedId(sampleSubjectId);setScreen("setup");
 };
 const start=async()=>{
  if(!chosen||busy)return;setError("");setBusy(true);const requestId=++generation.current;
  try{
   const sources=docs.filter(d=>chosen.noteIds.includes(d.id)&&d.text.trim().length>=20).map(d=>({id:d.id,name:d.name,text:d.text}));
   if(!sources.length)throw new Error(t("Vincula al menos un apunte con texto para preparar la sesión.","Vincula almenys un apunt amb text per a preparar la sessió."));
   if(sources.length>12||sources.reduce((n,s)=>n+s.text.length,0)>60000)throw new Error(t("Elige hasta 12 apuntes y 60.000 caracteres para esta sesión. Puedes trabajar el resto después.","Tria fins a 12 apunts i 60.000 caràcters. Pots treballar la resta després."));
   if(demo&&chosen.id!==sampleSubjectId)throw new Error(t("La demo utiliza la asignatura de ejemplo. En tu cuenta real podrás estudiar tus propios apuntes.","La demo utilitza l’assignatura d’exemple. En el compte real podràs estudiar els teus apunts."));
   const lesson=demo?exampleLesson(state.preferences.mode,state.preferences.minutes,va):await prepareLearning({language:locale,preferences:{...state.preferences,goal:chosen.goal||state.preferences.goal},sources,subject:chosen.name,topic:chosen.topic??"",review:state.concepts.filter(c=>c.subjectId===chosen.id&&(c.lastOutcome==="review"||new Date(c.reviewAt)<=new Date())).map(c=>c.topic)});
   if(requestId!==generation.current)return;
   const next:StudySession={id:newId(),subjectId:chosen.id,subjectName:chosen.name,createdAt:new Date().toISOString(),minutes:state.preferences.minutes,lesson,sources,answers:{},drafts:{},current:0,interestContext:[...state.preferences.interests]};
   setState(current=>({...current,activeId:next.id,sessions:[next,...current.sessions]}));openSession(next);
  }catch(e){if(requestId===generation.current)setError(e instanceof Error?e.message:t("No se pudo preparar la sesión.","No s’ha pogut preparar la sessió."));}finally{if(requestId===generation.current)setBusy(false);}
 };
 if(!ready||!subjectsReady||!notesReady)return <section className="lc-loading" role="status"><LoaderCircle className="lc-spin"/>{t("Preparando tu espacio de estudio…","Preparant el teu espai d’estudi…")}</section>;
 return <div className="lc-center">
 {screen==="session"&&session?<><SessionPlayer key={session.id} session={session} preferences={state.preferences}
  onDraft={draft=>setState(current=>({...current,sessions:current.sessions.map(s=>s.id===session.id?{...s,drafts:{...s.drafts,[s.current]:draft}}:s)}))}
  onAnswer={answer=>setState(current=>recordAnswer(current,session.id,session.current,answer))}
  onNext={()=>setState(current=>session.current===session.lesson.activities.length-1?finishSession(current,session.id):{...current,sessions:current.sessions.map(s=>s.id===session.id?{...s,current:s.current+1}:s)})}
  onExit={()=>{setScreen("home");setOpenedId(null);}}/><StudySync storeKey={key} status={status}/></>:screen==="setup"?<section className="lc-setup">
  <button className="lc-text-button" disabled={busy} onClick={()=>setScreen("home")}><ArrowLeft/>{t("Volver a Estudiante","Tornar a Estudiant")}</button>
  <span className="lc-eyebrow">{t("HAZLE UN HUECO","FES-LI UN LLOC")}</span><h2>{t("¿Qué te viene bien ahora?","Què et ve bé ara?")}</h2><p>{t("Un rato para entender, practicar o seguir con lo de clase.","Una estona per a entendre, practicar o seguir amb el de classe.")}</p>
  <div className="lc-setup-grid"><div className="lc-setup-controls"><label>{t("Asignatura","Assignatura")}<select disabled={busy} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">{t("Elige una asignatura","Tria una assignatura")}</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  <fieldset disabled={busy}><legend>{t("Tiempo aproximado","Temps aproximat")}</legend><div className="lc-time-options">{([5,10,20] as const).map(minutes=><button type="button" key={minutes} aria-pressed={state.preferences.minutes===minutes} onClick={()=>setState(current=>({...current,preferences:{...current.preferences,minutes,mode:current.preferences.mode==='sprint'&&minutes!==5?'mixed':current.preferences.mode}}))}><Clock3/>{minutes} min</button>)}</div></fieldset>
  <fieldset disabled={busy}><legend>{t("Cómo quieres practicar","Com vols practicar")}</legend><div className="lc-mode-grid">{modes.map((mode,i)=><button type="button" key={mode.id} aria-pressed={state.preferences.mode===mode.id} onClick={()=>setState(current=>({...current,preferences:{...current.preferences,mode:mode.id,minutes:mode.id==='sprint'?5:current.preferences.minutes}}))}><span className="lc-mode-index">0{i+1}</span><strong>{mode.title[va?1:0]}</strong><span>{mode.body[va?1:0]}</span></button>)}</div></fieldset></div>
  <aside className="lc-session-brief"><Sprout/><h3>{chosen?.name??t("Empieza por una asignatura","Comença per una assignatura")}</h3><p>{chosen?.topic||t("La sesión se basará en los apuntes que hayas vinculado.","La sessió es basarà en els apunts vinculats.")}</p>{chosen&&<ul>{docs.filter(d=>chosen.noteIds.includes(d.id)).map(d=><li key={d.id}><BookOpen/>{d.name}</li>)}</ul>}<p>{state.preferences.goal}</p>{state.preferences.interests.length>0&&<p>{t("Ejemplos relacionados con: ","Exemples relacionats amb: ")+state.preferences.interests.join(", ")}</p>}<button type="button" className="lc-text-button" disabled={busy} onClick={preferences}><Settings2/>{t("Ajustar a mi manera","Ajustar a la meua manera")}</button>
  <button className="lc-primary" disabled={busy||!chosen||!chosen.noteIds.length||(demo&&chosen.id!==sampleSubjectId)} onClick={()=>void start()}>{busy?<LoaderCircle className="lc-spin"/>:<Play/>}{busy?t("Preparando tu sesión…","Preparant la sessió…"):t("Empezar sesión","Començar sessió")}</button>
  {chosen&&!chosen.noteIds.length&&<Link href={toolPath(locale,demo,"notes")}>{t("Primero, subir apuntes","Primer, pujar apunts")}<ArrowRight/></Link>}
  {demo&&<div className="lc-demo-note"><p>{t("Las sesiones demo usan material de ejemplo. Tus apuntes propios se trabajan con IA en una cuenta real.","Les sessions demo usen material d’exemple. Els teus apunts es treballen amb IA en un compte real.")}</p>{chosen?.id!==sampleSubjectId&&<button type="button" onClick={useExample}>{t("Cargar asignatura de ejemplo","Carregar assignatura d’exemple")}</button>}</div>}
  {error&&<p className="lc-error" role="alert">{error}</p>}</aside></div>
 </section>:screen==="history"?<section className="lc-memory">
  <button className="lc-text-button" onClick={()=>setScreen("home")}><ArrowLeft/>{t("Volver a Estudiante","Tornar a Estudiant")}</button><span className="lc-eyebrow">{t("A LO LARGO DEL CURSO","AL LLARG DEL CURS")}</span><h2>{t("Todo lo que has ido trabajando.","Tot el que has anat treballant.")}</h2><p>{t("Las últimas 20 sesiones se conservan completas. De las anteriores guardamos el resumen y tu progreso; los apuntes originales siguen en tus documentos.","Les últimes 20 sessions es conserven completes. De les anteriors guardem el resum i el progrés; els apunts originals continuen als documents.")}</p>
  <label className="lc-history-search">{t("Buscar por asignatura o tema","Buscar per assignatura o tema")}<input type="search" value={historySearch} onChange={e=>setHistorySearch(e.target.value)}/></label>
  <div className="lc-memory-grid">{history.map(s=><article key={s.id}><span className="lc-eyebrow">{s.subjectName} · {new Date(s.completedAt).toLocaleDateString(va?"ca-ES":"es-ES")}</span><h3>{s.title}</h3><p>{s.objective}</p><p>{s.activities} {t("actividades","activitats")} · {s.independent} {t("sin ayuda","sense ajuda")}</p><details><summary>{t("Conceptos practicados","Conceptes practicats")}</summary><ul>{s.topics.map(topic=><li key={topic}>{topic}</li>)}</ul></details>{state.sessions.find(item=>item.id===s.id)&&<button onClick={()=>openSession(state.sessions.find(item=>item.id===s.id)!)}>{t("Abrir sesión","Obrir sessió")}<ArrowRight/></button>}</article>)}</div>
  {!history.length&&<p>{t("Todavía no hay sesiones completadas que coincidan.","Encara no hi ha sessions completades que coincidisquen.")}</p>}
 </section>:screen==="memory"?<section className="lc-memory">
  <button className="lc-text-button" onClick={()=>setScreen("home")}><ArrowLeft/>{t("Volver a Estudiante","Tornar a Estudiant")}</button><span className="lc-eyebrow">{t("LO QUE VAMOS APRENDIENDO","EL QUE ANEM APRENENT")}</span><h2>{t("Tu progreso, con contexto.","El teu progrés, amb context.")}</h2><p>{t("Un acierto no significa dominar un tema. Observamos lo que recuerdas en días distintos y la ayuda que necesitas.","Un encert no vol dir dominar un tema. Observem el que recordes en dies diferents i l’ajuda que necessites.")}</p>
  <button className="lc-text-button" onClick={preferences}><Settings2/>{t("Ver o cambiar mis preferencias","Vore o canviar preferències")}</button>
  <div className="lc-memory-grid">{state.concepts.map(c=><article key={c.id}><span className="lc-eyebrow">{subjectState.subjects.find(s=>s.id===c.subjectId)?.name??t("Asignatura archivada","Assignatura arxivada")}</span><h3>{c.topic}</h3><span className={"lc-concept-state "+(c.lastOutcome==='review'?'review':'')}>{c.lastOutcome==='review'?t("Conviene repasarlo","Convé repassar-ho"):c.independentDays.length>=3?t("Se está afianzando","S’està consolidant"):t("Seguimos practicando","Continuem practicant")}</span><p>{c.attempts} {t("intentos","intents")} · {c.independentDays.length} {t("días resuelto sin ayuda","dies resolt sense ajuda")}</p><p>{t("Próximo repaso: ","Pròxim repàs: ")}{new Date(c.reviewAt).toLocaleDateString(va?"ca-ES":"es-ES",{day:"numeric",month:"short"})}</p><div><button onClick={()=>setup(c.subjectId)}>{t("Repasar","Repassar")}<ArrowRight/></button><button onClick={()=>{if(window.confirm(t("¿Borrar el seguimiento de este concepto? Las sesiones se conservan.","Vols esborrar el seguiment d’aquest concepte? Les sessions es conserven.")))setState(current=>({...current,concepts:current.concepts.filter(item=>item.id!==c.id)}));}}>{t("Olvidar este progreso","Oblidar aquest progrés")}</button></div></article>)}</div>
  {!state.concepts.length&&<div className="lc-empty"><Sprout/><p>{t("Tu primera sesión dará forma a este espacio.","La primera sessió donarà forma a aquest espai.")}</p><button className="lc-primary" onClick={()=>setup()}>{t("Preparar una sesión","Preparar una sessió")}<ArrowRight/></button></div>}
 </section>:<>
  <div className="lc-dashboard"><section className="lc-today"><div className="lc-today-top"><span className="lc-eyebrow"><span className="lc-live-dot"/>{active?t("SESIÓN A MEDIAS","SESSIÓ A MITGES"):due.length?t("TOCA REPASAR","TOCA REPASSAR"):todayCount?t("EL SIGUIENTE PASO","EL PAS SEGÜENT"):t("EMPIEZA POR UN TEMA","COMENÇA PER UN TEMA")}</span><button aria-label={t("Mis preferencias de estudio","Les meues preferències d’estudi")} onClick={preferences}><Settings2/></button></div><h2>{active?t("Tu sesión sigue aquí.","La teua sessió continua ací."):due.length?t("Hay temas que toca recuperar.","Hi ha temes que toca recuperar."):todayCount?t("Hoy ya has practicado.","Hui ja has practicat."):t("Deja de releerlo. Ponlo a prueba.","Deixa de rellegir-ho. Posa-ho a prova.")}</h2><p>{active?`${active.subjectName} · ${Object.keys(active.answers).length}/${active.lesson.activities.length} ${t("actividades hechas","activitats fetes")}`:due.length?t(`Tienes ${due.length} ${due.length===1?"concepto pendiente":"conceptos pendientes"} de repaso.`,`Tens ${due.length} ${due.length===1?"concepte pendent":"conceptes pendents"} de repàs.`):suggested?t(`Empieza por ${suggested.name}${suggested.topic?' · '+suggested.topic:''}. Comprueba qué entiendes y qué falta repasar.`,`Comença per ${suggested.name}${suggested.topic?' · '+suggested.topic:''}. Comprova què entens i què falta repassar.`):t("Elige un tema y añade tus apuntes. Practica con preguntas de clase y descubre qué te falta entender.","Tria un tema i afig els teus apunts. Practica amb preguntes de classe i descobrix què et falta entendre.")}</p>
   <div className="lc-today-actions"><button className="lc-primary" onClick={()=>active?openSession(active):setup()}>{active?<Play/>:<ArrowRight/>}{active?t("Continuar sesión","Continuar sessió"):t("Preparar una sesión","Preparar una sessió")}</button>{active?<button className="lc-text-button" onClick={()=>setup()}>{t("Preparar otra sesión","Preparar una altra sessió")}</button>:<span><Clock3/>{state.preferences.minutes} {t("minutos para empezar","minuts per a començar")}</span>}</div><div className="lc-today-decoration" aria-hidden="true"><span/><span/><BookOpen/></div>
  </section><aside className="lc-rhythm"><span className="lc-rhythm-icon"><Sprout/></span><span className="lc-eyebrow">{t("TU AVANCE","EL TEU AVANÇ")}</span><h3>{t("Lo que llevas estudiado.","El que portes estudiat.")}</h3><div className="lc-rhythm-counts"><span><strong>{completed.length}</strong>{t("sesiones","sessions")}</span><span><strong>{state.concepts.length}</strong>{t("conceptos","conceptes")}</span></div><button className="lc-text-button" onClick={()=>setScreen("memory")}>{t("Ver temas y repasos","Vore temes i repassos")}<ArrowRight/></button></aside></div>
  <div className="lc-intentions" aria-label={t("Qué necesitas hoy","Què necessites hui")}>{[[BookOpen,t("Me he perdido en clase","M’he perdut en classe")],[Lightbulb,t("No entiendo un tema","No entenc un tema")],[Flag,t("Tengo una entrega","Tinc una entrega")],[Target,t("Necesito repasar","Necessite repassar")]].map(([Icon,label])=>{const Symbol=Icon as typeof BookOpen;return <button key={String(label)} onClick={()=>{setState(current=>({...current,preferences:{...current.preferences,goal:String(label)}}));setup();}}><Symbol/><span>{String(label)}</span><ArrowRight/></button>;})}</div>
  {demo&&!state.sessions.length&&<div className="lc-example"><Sparkles/><div><strong>{t("Pruébalo antes de subir tus apuntes.","Prova-ho abans de pujar els apunts.")}</strong><p>{t("Una asignatura de ejemplo y una sesión completa para conocer cómo funciona.","Una assignatura d’exemple i una sessió completa per a conéixer com funciona.")}</p></div><button onClick={useExample}>{t("Probar una sesión","Provar una sessió")}<ArrowRight/></button></div>}
  <SubjectsWorkspace onStudy={setup}/>
  {state.sessions.length>0&&<section className="lc-recent"><div><span className="lc-eyebrow">{t("EL HILO SIGUE AQUÍ","EL FIL SEGUEIX ACÍ")}</span><h3>{t("Tus últimas sesiones","Les últimes sessions")}</h3><button className="lc-text-button" onClick={()=>setScreen("history")}>{t("Ver historial del curso","Vore historial del curs")}<ArrowRight/></button></div><div className="lc-recent-list">{state.sessions.slice(0,4).map(s=><button key={s.id} onClick={()=>openSession(s)}><span className="lc-recent-symbol">{s.completedAt?<Check/>:<Play/>}</span><span><strong>{s.lesson.title}</strong><small>{s.subjectName} · {new Date(s.createdAt).toLocaleDateString(va?'ca-ES':'es-ES',{day:'numeric',month:'short'})}</small></span><span>{s.completedAt?t("Ver sesión","Vore sessió"):t("Continuar","Continuar")}</span><ArrowRight/></button>)}</div></section>}
  <StudySync storeKey={key} status={status}/>
 </>}
 <Modal open={preferencesOpen} onOpenChange={setPreferencesOpen} title={t("A tu manera.","A la teua manera.")} description={t("Tú decides lo que el tutor tiene en cuenta. Puedes cambiarlo cuando quieras.","Tu decideixes què té en compte el tutor. Pots canviar-ho quan vulgues.")}>
 <form className="lc-form" onSubmit={e=>{e.preventDefault();const interests=interestsText.split(',').map(s=>s.trim().slice(0,80)).filter(Boolean).slice(0,8);setState(current=>({...current,preferences:{...draftPreferences,interests}}));setPreferencesOpen(false);}}>
  <label>{t("¿Para qué estudias ahora?","Per a què estudies ara?")}<input required maxLength={160} value={draftPreferences.goal} onChange={e=>setDraftPreferences({...draftPreferences,goal:e.target.value})}/></label>
  <label>{t("¿Qué sabes ya? (opcional)","Què saps ja? (opcional)")}<textarea rows={2} maxLength={500} placeholder={t("Empiezo desde cero, o ya entiendo…","Comence de zero, o ja entenc…")} value={draftPreferences.experience} onChange={e=>setDraftPreferences({...draftPreferences,experience:e.target.value})}/></label>
  <label>{t("Cómo prefieres las explicaciones","Com prefereixes les explicacions")}<select value={draftPreferences.tone} onChange={e=>setDraftPreferences({...draftPreferences,tone:e.target.value as StudyPreferences['tone']})}><option value="peer">{t("Como un compañero","Com un company")}</option><option value="simple">{t("Desde lo más sencillo","Des del més senzill")}</option><option value="teacher">{t("Con estructura y detalle","Amb estructura i detall")}</option></select></label>
  <label>{t("Intereses para los ejemplos (opcional)","Interessos per als exemples (opcional)")}<input maxLength={650} placeholder={t("Música, videojuegos, deporte…","Música, videojocs, esport…")} value={interestsText} onChange={e=>setInterestsText(e.target.value)}/></label><p className="lc-muted">{t("Separados por comas, hasta 8. Solo usamos lo que elijas aquí.","Separats per comes, fins a 8. Només usem el que tries ací.")}</p>
  {me.interests?.length>0&&<button className="lc-text-button" type="button" onClick={()=>setInterestsText(me.interests.slice(0,8).join(', '))}><Compass/>{t("Usar los intereses de mi perfil","Usar els interessos del meu perfil")}</button>}
  <div className="u-form-actions"><button className="st-button" type="button" onClick={()=>setPreferencesOpen(false)}>{t("Cancelar","Cancel·lar")}</button><button className="lc-primary" type="submit">{t("Guardar preferencias","Guardar preferències")}<Check/></button></div>
 </form></Modal>
 </div>;
}
