"use client";
import { useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BookOpen, Check, Flag, Lightbulb, LoaderCircle, MessageCircle, RotateCcw } from "lucide-react";
import { useCommunity } from "../context";
import { askTutor } from "@/lib/community/student/ai";
import { evaluateLearning } from "@/lib/community/student/learning-client";
import { choiceCorrect, type AnswerRecord, type StudyPreferences, type StudySession } from "@/lib/community/student/learning";
import { renderMarkdown } from "@/lib/community/student/notes";
export function SessionPlayer({session,preferences,onDraft,onAnswer,onNext,onExit}:{session:StudySession;preferences:StudyPreferences;onDraft:(draft:{answer:string;hinted:boolean;revealed?:boolean})=>void;onAnswer:(answer:AnswerRecord)=>void;onNext:()=>void;onExit:()=>void}){
 const {locale,demo}=useCommunity(),t=(es:string,va:string)=>locale==="va"?va:es;
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[alternative,setAlternative]=useState("");
 const index=session.current,activity=session.lesson.activities[index],saved=session.answers[index];
 const draft=session.drafts?.[index]??{answer:"",hinted:false,revealed:false};
 const source=session.sources.find(s=>s.id===activity.sourceId);
 const kindLabels={choice:t("Vamos a situarnos","Anem a situar-nos"),"spot-error":t("Encuentra el fallo","Troba l’error"),case:t("Resuelve el caso","Resol el cas"),connect:t("Conecta las piezas","Connecta les peces"),teach:t("Ahora enseñas tú","Ara ensenyes tu")};
 const order=draft.answer?draft.answer.split(",").map(Number):activity.options.map((_,i)=>i);
 const move=(position:number,delta:number)=>{const next=[...order];[next[position],next[position+delta]]=[next[position+delta],next[position]];onDraft({...draft,answer:next.join(",")});};
 const submit=async()=>{
  if(saved||busy)return;setError("");
  if(activity.kind==="teach"&&demo){onDraft({...draft,revealed:true,hinted:true});return;}
  const answer=activity.kind==="connect"?order.join(","):draft.answer;
  if(!answer.trim())return;
  setBusy(true);
  try{
   const correct=choiceCorrect(activity,answer);
   const feedback=activity.kind==="teach"?await evaluateLearning({language:locale,preferences,sources:session.sources,activity,answer}):{verdict:correct?"correct" as const:"revisit" as const,feedback:activity.explanation,nextQuestion:correct?"":activity.hint};
   onAnswer({answer,correct:feedback.verdict==="correct",hinted:draft.hinted,feedback,at:new Date().toISOString()});
  }catch(e){setError(e instanceof Error?e.message:t("No se pudo evaluar. Inténtalo de nuevo.","No s’ha pogut avaluar. Torna-ho a provar."));}finally{setBusy(false);}
 };
 const explainAgain=async()=>{setBusy(true);setError("");try{
  if(demo)setAlternative(t("Imagina que tienes una tarde libre. Eliges una actividad, pero había otra que también te apetecía. El valor de esa segunda opción es lo que sacrificas. No sumes todos los planes que descartaste.","Imagina que tens una vesprada lliure. Tries una activitat, però n’hi havia una altra que també t’abellia. El valor d’eixa segona opció és el que sacrifiques. No sumes tots els plans descartats."));
  else {const result=await askTutor({mode:"explain",language:locale,notes:source?.text??"",question:`Explica de otra forma el concepto de esta actividad: ${activity.prompt}. La respuesta del alumno fue: ${saved?.answer}. Su duda es entender el razonamiento. Usa un ejemplo identificado como inventado si ayuda.`,style:{tone:"simple",length:"short"}},{demo:false});setAlternative(result.text??"");}
 }catch(e){setError(e instanceof Error?e.message:"No se pudo explicar.");}finally{setBusy(false);}};
 if(session.completedAt){const records=Object.values(session.answers),independent=records.filter(a=>a.correct&&!a.hinted).length;
  return <section className="lc-finish"><span className="lc-finish-mark"><Check/></span><span className="lc-eyebrow">{t("POR HOY, UN PASO MÁS","PER HUI, UN PAS MÉS")}</span><h2>{t("Esto ya lo has trabajado.","Açò ja ho has treballat.")}</h2><p>{session.lesson.objective}</p><div className="lc-finish-stats"><div><strong>{records.length}</strong><span>{t("actividades completadas","activitats completades")}</span></div><div><strong>{independent}</strong><span>{t("resueltas sin ayuda","resoltes sense ajuda")}</span></div><div><strong>{new Set(session.lesson.activities.map(a=>a.topic)).size}</strong><span>{t("conceptos practicados","conceptes practicats")}</span></div></div><p>{t("Tus próximos repasos ya están preparados. Volveremos a comprobar lo que recuerdas otro día.","Els pròxims repassos ja estan preparats. Tornarem a comprovar el que recordes un altre dia.")}</p><div className="lc-session-review">{session.lesson.activities.map((a,i)=><details key={i}><summary>{i+1}. {a.prompt}</summary><p><b>{t("Tu respuesta: ","La teua resposta: ")}</b>{a.kind==="connect"?session.answers[i].answer.split(',').map(n=>a.options[Number(n)]).join(' → '):a.kind==="teach"?session.answers[i].answer:a.options[Number(session.answers[i].answer)]}</p><p>{session.answers[i].feedback.feedback}</p><p>{a.modelAnswer}</p><blockquote>{a.quote}</blockquote></details>)}</div><button className="lc-primary" onClick={onExit}>{t("Volver a mi mesa","Tornar a la meua taula")}<ArrowRight/></button></section>;
 }
 return <section className="lc-session" aria-label={t("Sesión de estudio","Sessió d’estudi")}>
  <div className="lc-session-top"><button className="lc-text-button" onClick={onExit} disabled={busy}><ArrowLeft/>{t("Guardar y salir","Guardar i eixir")}</button><span>{session.subjectName} · {index+1}/{session.lesson.activities.length}</span></div>
  <div className="lc-progress" role="progressbar" aria-label={t("Actividades completadas","Activitats completades")} aria-valuenow={Object.keys(session.answers).length} aria-valuemin={0} aria-valuemax={session.lesson.activities.length}>{session.lesson.activities.map((_,i)=><span key={i} className={session.answers[i]?"done":i===index?"current":""}/>)}</div>
  <div className="lc-session-grid"><div className="lc-exercise" key={index}>
   <div className="lc-exercise-label"><span><Flag size={15}/>{kindLabels[activity.kind]}</span><span>{index===0?t("Primero, una pregunta","Primer, una pregunta"):activity.topic}</span></div>
   {index===1&&<div className="lc-mini-lesson"><BookOpen/><p>{session.lesson.introduction}</p></div>}
   <h2 tabIndex={-1}>{activity.prompt}</h2>
   {activity.kind==="teach"?<label className="lc-teach-label">{t("Con tus palabras","Amb les teues paraules")}<textarea rows={5} maxLength={4000} disabled={!!saved||busy} value={draft.answer} onChange={e=>onDraft({...draft,answer:e.target.value})} placeholder={t("Yo lo explicaría así…","Jo ho explicaria així…")}/></label>:activity.kind==="connect"?<ol className="lc-order">{order.map((option,i)=><li key={option}><span className="lc-option-number">{i+1}</span><span>{activity.options[option]}</span><div><button disabled={!!saved||i===0||busy} aria-label={t("Subir ","Pujar ")+activity.options[option]} onClick={()=>move(i,-1)}><ArrowUp/></button><button disabled={!!saved||i===order.length-1||busy} aria-label={t("Bajar ","Baixar ")+activity.options[option]} onClick={()=>move(i,1)}><ArrowDown/></button></div></li>)}</ol>:<div className="lc-options" role="group" aria-label={t("Elige una respuesta","Tria una resposta")}>{activity.options.map((option,i)=><button type="button" key={i} aria-pressed={draft.answer===String(i)} disabled={!!saved||busy} className={saved&&i===activity.answer?"correct":draft.answer===String(i)?"selected":""} onClick={()=>onDraft({...draft,answer:String(i)})}><span className="lc-option-number">{String.fromCharCode(65+i)}</span><span>{option}</span>{saved&&i===activity.answer&&<Check/>}</button>)}</div>}
   {!saved&&draft.hinted&&<div className="lc-hint"><Lightbulb/><p>{activity.hint}</p></div>}
   {!saved&&!draft.revealed&&<div className="lc-exercise-actions"><button className="lc-text-button" disabled={busy||draft.hinted} onClick={()=>onDraft({...draft,hinted:true})}><Lightbulb/>{t("Dame una pista","Dona’m una pista")}</button><button className="lc-primary" disabled={busy||(activity.kind!=="connect"&&!draft.answer.trim())} onClick={()=>void submit()}>{busy?<LoaderCircle className="lc-spin"/>:<ArrowRight/>}{busy?t("Revisando…","Revisant…"):t("Comprobar","Comprovar")}</button></div>}
   {!saved&&draft.revealed&&demo&&<div className="lc-feedback"><strong>{t("En la demo, tú comparas tu explicación","En la demo, tu compares l’explicació")}</strong><p>{activity.modelAnswer}</p><p>{t("Esta respuesta no la está evaluando una IA real.","Aquesta resposta no l’està avaluant una IA real.")}</p><div className="lc-self-review">{([['correct',t('Lo expliqué','Ho he explicat')],['partial',t('Me faltaba algo','Em faltava alguna cosa')],['revisit',t('Quiero repasarlo','Vull repassar-ho')]] as const).map(([verdict,label])=><button key={verdict} onClick={()=>onAnswer({answer:draft.answer,correct:verdict==='correct',hinted:true,feedback:{verdict,feedback:t("Autoevaluación de ejemplo. ","Autoavaluació d’exemple. ")+activity.explanation,nextQuestion:""},at:new Date().toISOString()})}>{label}</button>)}</div></div>}
   {saved&&<div className={"lc-feedback "+(saved.correct?"is-correct":"is-review")} aria-live="polite"><strong>{saved.correct?t("Bien razonado.","Ben raonat."):t("Vamos a aclararlo.","Anem a aclarir-ho.")}</strong><p>{saved.feedback.feedback}</p>{!saved.correct&&<p><b>{t("La idea que buscábamos: ","La idea que buscàvem: ")}</b>{activity.modelAnswer}</p>}{saved.feedback.nextQuestion&&<p className="lc-feedback-question">{saved.feedback.nextQuestion}</p>}{alternative&&<div className="lc-alternative">{renderMarkdown(alternative)}</div>}<div className="lc-exercise-actions"><button className="lc-text-button" onClick={()=>void explainAgain()} disabled={busy}><MessageCircle/>{t("Explícamelo de otra forma","Explica-m’ho d’una altra manera")}</button><button className="lc-primary" disabled={busy} onClick={()=>{setAlternative("");setError("");onNext();}}>{index===session.lesson.activities.length-1?t("Terminar sesión","Acabar sessió"):t("Seguir","Seguir")}<ArrowRight/></button></div></div>}
   {error&&<p role="alert" className="lc-error">{error} <button onClick={()=>setError("")}><RotateCcw size={14}/>{t("Entendido","Entés")}</button></p>}
  </div><aside className="lc-source-panel" key={`source-${index}`}><span className="lc-eyebrow">{t("TUS APUNTES, A MANO","ELS TEUS APUNTS, A MÀ")}</span><h3>{source?.name}</h3><p>{t("Puedes consultar el material cuando lo necesites. Se contará como una ayuda.","Pots consultar el material quan ho necessites. Comptarà com una ajuda.")}</p><details onToggle={e=>{if(e.currentTarget.open&&!saved&&!draft.hinted)onDraft({...draft,hinted:true});}}><summary><BookOpen/>{t("Ver fragmento original","Vore fragment original")}</summary><blockquote>{activity.quote}</blockquote><details><summary>{t("Abrir texto del documento","Obrir text del document")}</summary><pre>{source?.text}</pre></details></details><span className="lc-source-footnote">{t("Las citas se comprueban contra el material de esta sesión.","Les cites es comproven amb el material d’aquesta sessió.")}</span></aside></div>
 </section>;
}
