"use client";
import { CloudCheck, CloudOff, LoaderCircle } from "lucide-react";
import { acceptCloudStore, currentStoreValue, retryStore, type SyncStatus } from "@/lib/community/student/storage";
import { useCommunity } from "../context";
export function StudySync({storeKey,status}:{storeKey:string;status:SyncStatus}){
 const {locale,demo}=useCommunity();const t=(es:string,va:string)=>locale==="va"?va:es;
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(currentStoreValue(storeKey),null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="entreclases-estudio.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const label=status==="synced"?t("Guardado en tu cuenta","Guardat en el teu compte"):status==="local"?t("Demo · guardado en este navegador","Demo · guardat en aquest navegador"):status==="loading"||status==="saving"?t("Sincronizando…","Sincronitzant…"):status==="full"?t("El navegador no tiene espacio. Descarga una copia de tus cambios.","El navegador no té espai. Descarrega una còpia dels canvis."):status==="conflict"?t("Hay otra versión en tu cuenta. Conservamos tus cambios aquí.","Hi ha una altra versió en el teu compte. Conservem els canvis ací."):t("Guardado aquí. No se ha podido sincronizar con tu cuenta.","Guardat ací. No s’ha pogut sincronitzar amb el teu compte.");
 return <div className="lc-sync" role="status">{status==="synced"?<CloudCheck size={14}/>:status==="saving"||status==="loading"?<LoaderCircle size={14} className="lc-spin"/>:<CloudOff size={14}/>}<span>{label}</span>{status==="error"&&<button type="button" onClick={()=>retryStore(storeKey)}>{t("Reintentar","Tornar a provar")}</button>}{["error","conflict","full"].includes(status)&&<button type="button" onClick={download}>{t("Descargar copia","Descarregar còpia")}</button>}{status==="conflict"&&!demo&&<button type="button" onClick={()=>{if(window.confirm(t("Se descargará una copia de tus cambios antes de cargar la versión de tu cuenta.","Es descarregarà una còpia dels canvis abans de carregar la versió del compte."))){download();acceptCloudStore(storeKey);}}}>{t("Cargar versión de mi cuenta","Carregar versió del compte")}</button>}</div>;
}
